// 100+ Comprehensive Career Data
const careers = [
  // ENGINEERING (15 careers)
  { title: 'Software Engineer', slug: 'software-engineer', description: 'Design, develop, and maintain software applications and systems', detailedInfo: 'Software engineers create innovative software solutions, write code, debug applications, and work on cutting-edge technologies.', category: 'Engineering', subCategory: 'Computer Science', averageSalary: '6-15 LPA', salaryRange: '4-50 LPA', demandLevel: 'High', futureDemand: 'Growing', requiredEducation: JSON.stringify(['B.Tech CS/IT', 'BCA', 'MCA']), requiredSkills: JSON.stringify(['Programming', 'Data Structures', 'Algorithms', 'Problem Solving']), personality: JSON.stringify(['Analytical', 'Creative', 'Logical']), interests: JSON.stringify(['Technology', 'Coding']), aptitudes: JSON.stringify(['Logical Reasoning']), jobRoles: JSON.stringify(['Developer', 'Tech Lead', 'Architect']), workEnvironment: 'Office/Remote', careerPath: JSON.stringify(['Junior → Senior → Lead → Manager']), prosAndCons: JSON.stringify({ pros: ['High salary', 'Remote work', 'Innovation'], cons: ['Continuous learning', 'Deadlines'] }) },
  
  { title: 'Data Scientist', slug: 'data-scientist', description: 'Analyze complex data to help companies make better decisions', detailedInfo: 'Data scientists use statistical analysis, machine learning, and data visualization to extract insights from large datasets.', category: 'Engineering', subCategory: 'Data Science', averageSalary: '8-20 LPA', salaryRange: '6-40 LPA', demandLevel: 'High', futureDemand: 'Growing', requiredEducation: JSON.stringify(['B.Tech', 'M.Sc Statistics', 'MBA Analytics']), requiredSkills: JSON.stringify(['Python', 'R', 'Machine Learning', 'Statistics']), personality: JSON.stringify(['Analytical', 'Curious']), interests: JSON.stringify(['Data', 'Mathematics']), aptitudes: JSON.stringify(['Analytical Thinking']), jobRoles: JSON.stringify(['Data Analyst', 'ML Engineer', 'Data Architect']), workEnvironment: 'Office/Remote', careerPath: JSON.stringify(['Analyst → Scientist → Lead → Manager']), prosAndCons: JSON.stringify({ pros: ['High demand', 'Impactful work'], cons: ['Complex problems', 'Steep learning curve'] }) },
  
  { title: 'Civil Engineer', slug: 'civil-engineer', description: 'Design and oversee construction of buildings, roads, and infrastructure', detailedInfo: 'Civil engineers plan, design, and manage construction projects ensuring safety, sustainability, and efficiency.', category: 'Engineering', subCategory: 'Civil', averageSalary: '4-10 LPA', salaryRange: '3-25 LPA', demandLevel: 'High', futureDemand: 'Stable', requiredEducation: JSON.stringify(['B.Tech Civil', 'Diploma Civil']), requiredSkills: JSON.stringify(['CAD', 'Project Management', 'Structural Analysis']), personality: JSON.stringify(['Practical', 'Detail-oriented']), interests: JSON.stringify(['Construction', 'Design']), aptitudes: JSON.stringify(['Spatial Reasoning']), jobRoles: JSON.stringify(['Site Engineer', 'Project Manager', 'Consultant']), workEnvironment: 'Site/Office', careerPath: JSON.stringify(['Junior → Senior → Manager → Director']), prosAndCons: JSON.stringify({ pros: ['Stable career', 'Tangible results'], cons: ['Site visits', 'Weather dependent'] }) },
  
  { title: 'Mechanical Engineer', slug: 'mechanical-engineer', description: 'Design, analyze, and manufacture mechanical systems and devices', detailedInfo: 'Mechanical engineers work on machines, engines, tools, and thermal systems across various industries.', category: 'Engineering', subCategory: 'Mechanical', averageSalary: '4-12 LPA', salaryRange: '3-30 LPA', demandLevel: 'High', futureDemand: 'Stable', requiredEducation: JSON.stringify(['B.Tech Mechanical', 'Diploma Mechanical']), requiredSkills: JSON.stringify(['CAD', 'Thermodynamics', 'Manufacturing']), personality: JSON.stringify(['Practical', 'Innovative']), interests: JSON.stringify(['Machines', 'Design']), aptitudes: JSON.stringify(['Mechanical Aptitude']), jobRoles: JSON.stringify(['Design Engineer', 'Production Engineer', 'R&D Engineer']), workEnvironment: 'Factory/Office', careerPath: JSON.stringify(['Junior → Senior → Manager']), prosAndCons: JSON.stringify({ pros: ['Diverse opportunities', 'Core engineering'], cons: ['Manufacturing environment'] }) },
  
  { title: 'Electrical Engineer', slug: 'electrical-engineer', description: 'Design and develop electrical systems, equipment, and power distribution', detailedInfo: 'Electrical engineers work on power generation, transmission, electronics, and control systems.', category: 'Engineering', subCategory: 'Electrical', averageSalary: '4-10 LPA', salaryRange: '3-25 LPA', demandLevel: 'High', futureDemand: 'Stable', requiredEducation: JSON.stringify(['B.Tech Electrical', 'Diploma Electrical']), requiredSkills: JSON.stringify(['Circuit Design', 'Power Systems', 'Control Systems']), personality: JSON.stringify(['Analytical', 'Practical']), interests: JSON.stringify(['Electronics', 'Power']), aptitudes: JSON.stringify(['Technical Aptitude']), jobRoles: JSON.stringify(['Design Engineer', 'Maintenance Engineer', 'Project Engineer']), workEnvironment: 'Field/Office', careerPath: JSON.stringify(['Junior → Senior → Manager']), prosAndCons: JSON.stringify({ pros: ['Essential field', 'Diverse sectors'], cons: ['Safety concerns'] }) },
  
  // TECHNOLOGY (20 careers)
  { title: 'Web Developer', slug: 'web-developer', description: 'Create and maintain websites and web applications', detailedInfo: 'Web developers build responsive, user-friendly websites using HTML, CSS, JavaScript, and modern frameworks.', category: 'Technology', subCategory: 'Web Development', averageSalary: '4-12 LPA', salaryRange: '3-30 LPA', demandLevel: 'High', futureDemand: 'Growing', requiredEducation: JSON.stringify(['B.Tech', 'BCA', 'Self-taught']), requiredSkills: JSON.stringify(['HTML', 'CSS', 'JavaScript', 'React/Angular']), personality: JSON.stringify(['Creative', 'Detail-oriented']), interests: JSON.stringify(['Web', 'Design']), aptitudes: JSON.stringify(['Visual Thinking']), jobRoles: JSON.stringify(['Frontend', 'Backend', 'Full Stack']), workEnvironment: 'Remote/Office', careerPath: JSON.stringify(['Junior → Senior → Lead']), prosAndCons: JSON.stringify({ pros: ['Remote work', 'Creative freedom'], cons: ['Rapidly changing tech'] }) },
  
  { title: 'Mobile App Developer', slug: 'mobile-app-developer', description: 'Develop applications for iOS and Android platforms', detailedInfo: 'Mobile developers create native and cross-platform apps for smartphones and tablets.', category: 'Technology', subCategory: 'Mobile Development', averageSalary: '5-15 LPA', salaryRange: '4-35 LPA', demandLevel: 'High', futureDemand: 'Growing', requiredEducation: JSON.stringify(['B.Tech', 'BCA', 'MCA']), requiredSkills: JSON.stringify(['Swift/Kotlin', 'React Native', 'Flutter']), personality: JSON.stringify(['Innovative', 'User-focused']), interests: JSON.stringify(['Mobile', 'Apps']), aptitudes: JSON.stringify(['Problem Solving']), jobRoles: JSON.stringify(['iOS Developer', 'Android Developer', 'Mobile Lead']), workEnvironment: 'Office/Remote', careerPath: JSON.stringify(['Junior → Senior → Architect']), prosAndCons: JSON.stringify({ pros: ['High demand', 'Innovation'], cons: ['Platform updates'] }) },
  
  { title: 'DevOps Engineer', slug: 'devops-engineer', description: 'Automate and streamline software development and deployment processes', detailedInfo: 'DevOps engineers bridge development and operations, managing CI/CD pipelines and infrastructure.', category: 'Technology', subCategory: 'DevOps', averageSalary: '7-18 LPA', salaryRange: '5-40 LPA', demandLevel: 'High', futureDemand: 'Growing', requiredEducation: JSON.stringify(['B.Tech', 'MCA']), requiredSkills: JSON.stringify(['Docker', 'Kubernetes', 'AWS', 'Jenkins']), personality: JSON.stringify(['Systematic', 'Problem-solver']), interests: JSON.stringify(['Automation', 'Infrastructure']), aptitudes: JSON.stringify(['Systems Thinking']), jobRoles: JSON.stringify(['DevOps Engineer', 'SRE', 'Cloud Engineer']), workEnvironment: 'Remote/Office', careerPath: JSON.stringify(['Junior → Senior → Architect']), prosAndCons: JSON.stringify({ pros: ['High salary', 'Critical role'], cons: ['On-call duties', 'Complex systems'] }) },
  
  { title: 'Cybersecurity Analyst', slug: 'cybersecurity-analyst', description: 'Protect systems and networks from cyber threats and attacks', detailedInfo: 'Cybersecurity analysts monitor, detect, and respond to security incidents while implementing protective measures.', category: 'Technology', subCategory: 'Security', averageSalary: '6-16 LPA', salaryRange: '4-35 LPA', demandLevel: 'High', futureDemand: 'Growing', requiredEducation: JSON.stringify(['B.Tech', 'Certifications: CEH, CISSP']), requiredSkills: JSON.stringify(['Network Security', 'Ethical Hacking', 'Risk Analysis']), personality: JSON.stringify(['Vigilant', 'Analytical']), interests: JSON.stringify(['Security', 'Technology']), aptitudes: JSON.stringify(['Critical Thinking']), jobRoles: JSON.stringify(['Security Analyst', 'Penetration Tester', 'Security Architect']), workEnvironment: 'Office', careerPath: JSON.stringify(['Analyst → Senior → Manager']), prosAndCons: JSON.stringify({ pros: ['Critical field', 'High demand'], cons: ['Stressful', 'Continuous learning'] }) },
  
  { title: 'Cloud Architect', slug: 'cloud-architect', description: 'Design and manage cloud computing solutions and infrastructure', detailedInfo: 'Cloud architects design scalable, secure cloud solutions using AWS, Azure, or Google Cloud platforms.', category: 'Technology', subCategory: 'Cloud Computing', averageSalary: '10-25 LPA', salaryRange: '7-50 LPA', demandLevel: 'High', futureDemand: 'Growing', requiredEducation: JSON.stringify(['B.Tech', 'Cloud Certifications']), requiredSkills: JSON.stringify(['AWS/Azure/GCP', 'Networking', 'Security']), personality: JSON.stringify(['Strategic', 'Technical']), interests: JSON.stringify(['Cloud', 'Infrastructure']), aptitudes: JSON.stringify(['Systems Design']), jobRoles: JSON.stringify(['Cloud Engineer', 'Solution Architect', 'Cloud Consultant']), workEnvironment: 'Remote/Office', careerPath: JSON.stringify(['Engineer → Architect → Principal']), prosAndCons: JSON.stringify({ pros: ['High salary', 'Future-proof'], cons: ['Certifications expensive'] }) },

  // MEDICAL (15 careers)
  { title: 'Doctor (MBBS)', slug: 'doctor-mbbs', description: 'Diagnose and treat illnesses, injuries, and medical conditions', detailedInfo: 'Doctors provide comprehensive medical care, conduct examinations, prescribe treatments, and perform procedures.', category: 'Medical', subCategory: 'Medicine', averageSalary: '8-20 LPA', salaryRange: '5-100 LPA', demandLevel: 'High', futureDemand: 'Stable', requiredEducation: JSON.stringify(['MBBS', 'MD/MS']), requiredSkills: JSON.stringify(['Medical Knowledge', 'Diagnosis', 'Communication', 'Empathy']), personality: JSON.stringify(['Compassionate', 'Analytical']), interests: JSON.stringify(['Healthcare', 'Helping Others']), aptitudes: JSON.stringify(['Scientific Reasoning']), jobRoles: JSON.stringify(['Resident', 'Consultant', 'Specialist']), workEnvironment: 'Hospital/Clinic', careerPath: JSON.stringify(['Resident → Consultant → Senior Consultant']), prosAndCons: JSON.stringify({ pros: ['Respect', 'Helping people', 'Stable'], cons: ['Long hours', '5.5 years study'] }) },
  
  { title: 'Nurse', slug: 'nurse', description: 'Provide patient care and support in healthcare settings', detailedInfo: 'Nurses care for patients, administer medications, monitor vitals, and assist doctors in treatments.', category: 'Medical', subCategory: 'Nursing', averageSalary: '3-8 LPA', salaryRange: '2-15 LPA', demandLevel: 'High', futureDemand: 'Growing', requiredEducation: JSON.stringify(['B.Sc Nursing', 'GNM']), requiredSkills: JSON.stringify(['Patient Care', 'Medical Procedures', 'Communication']), personality: JSON.stringify(['Caring', 'Patient']), interests: JSON.stringify(['Healthcare', 'Helping']), aptitudes: JSON.stringify(['Empathy']), jobRoles: JSON.stringify(['Staff Nurse', 'Head Nurse', 'Nurse Manager']), workEnvironment: 'Hospital', careerPath: JSON.stringify(['Staff → Senior → Manager']), prosAndCons: JSON.stringify({ pros: ['Job security', 'Rewarding'], cons: ['Shift work', 'Physically demanding'] }) },
  
  { title: 'Pharmacist', slug: 'pharmacist', description: 'Dispense medications and provide pharmaceutical care', detailedInfo: 'Pharmacists prepare and dispense medications, counsel patients, and ensure safe medication use.', category: 'Medical', subCategory: 'Pharmacy', averageSalary: '3-7 LPA', salaryRange: '2-12 LPA', demandLevel: 'High', futureDemand: 'Stable', requiredEducation: JSON.stringify(['B.Pharm', 'D.Pharm']), requiredSkills: JSON.stringify(['Drug Knowledge', 'Patient Counseling', 'Attention to Detail']), personality: JSON.stringify(['Precise', 'Helpful']), interests: JSON.stringify(['Pharmacy', 'Healthcare']), aptitudes: JSON.stringify(['Scientific Knowledge']), jobRoles: JSON.stringify(['Retail Pharmacist', 'Clinical Pharmacist', 'Quality Control']), workEnvironment: 'Pharmacy/Hospital', careerPath: JSON.stringify(['Junior → Senior → Manager']), prosAndCons: JSON.stringify({ pros: ['Stable career', 'Healthcare sector'], cons: ['Standing hours'] }) },
  
  { title: 'Dentist', slug: 'dentist', description: 'Diagnose and treat dental and oral health problems', detailedInfo: 'Dentists examine, diagnose, and treat dental issues, perform procedures, and promote oral health.', category: 'Medical', subCategory: 'Dentistry', averageSalary: '5-15 LPA', salaryRange: '3-50 LPA', demandLevel: 'High', futureDemand: 'Stable', requiredEducation: JSON.stringify(['BDS', 'MDS']), requiredSkills: JSON.stringify(['Dental Procedures', 'Manual Dexterity', 'Patient Care']), personality: JSON.stringify(['Precise', 'Patient']), interests: JSON.stringify(['Healthcare', 'Dental Health']), aptitudes: JSON.stringify(['Hand-eye Coordination']), jobRoles: JSON.stringify(['General Dentist', 'Orthodontist', 'Oral Surgeon']), workEnvironment: 'Clinic/Hospital', careerPath: JSON.stringify(['General → Specialist → Consultant']), prosAndCons: JSON.stringify({ pros: ['Own practice possible', 'Good income'], cons: ['Initial investment high'] }) },
  
  { title: 'Physiotherapist', slug: 'physiotherapist', description: 'Help patients recover from injuries through physical therapy', detailedInfo: 'Physiotherapists use exercises, manual therapy, and equipment to restore movement and function.', category: 'Medical', subCategory: 'Rehabilitation', averageSalary: '3-8 LPA', salaryRange: '2-15 LPA', demandLevel: 'High', futureDemand: 'Growing', requiredEducation: JSON.stringify(['BPT', 'MPT']), requiredSkills: JSON.stringify(['Therapeutic Exercises', 'Manual Therapy', 'Patient Assessment']), personality: JSON.stringify(['Patient', 'Encouraging']), interests: JSON.stringify(['Healthcare', 'Rehabilitation']), aptitudes: JSON.stringify(['Physical Coordination']), jobRoles: JSON.stringify(['Clinical PT', 'Sports PT', 'Consultant']), workEnvironment: 'Hospital/Clinic', careerPath: JSON.stringify(['Junior → Senior → Consultant']), prosAndCons: JSON.stringify({ pros: ['Rewarding', 'Growing demand'], cons: ['Physically demanding'] }) },

  // BUSINESS (15 careers)
  { title: 'Business Analyst', slug: 'business-analyst', description: 'Analyze business processes and recommend improvements', detailedInfo: 'Business analysts bridge IT and business, gathering requirements and optimizing processes.', category: 'Business', subCategory: 'Analysis', averageSalary: '5-12 LPA', salaryRange: '4-25 LPA', demandLevel: 'High', futureDemand: 'Growing', requiredEducation: JSON.stringify(['BBA', 'MBA', 'B.Tech']), requiredSkills: JSON.stringify(['Analysis', 'Communication', 'Excel', 'SQL']), personality: JSON.stringify(['Analytical', 'Communicative']), interests: JSON.stringify(['Business', 'Problem Solving']), aptitudes: JSON.stringify(['Logical Thinking']), jobRoles: JSON.stringify(['Junior BA', 'Senior BA', 'Manager']), workEnvironment: 'Office', careerPath: JSON.stringify(['Analyst → Senior → Manager']), prosAndCons: JSON.stringify({ pros: ['Diverse industries', 'Good growth'], cons: ['Meetings heavy'] }) },
  
  { title: 'Marketing Manager', slug: 'marketing-manager', description: 'Plan and execute marketing strategies to promote products/services', detailedInfo: 'Marketing managers develop campaigns, analyze market trends, and drive brand growth.', category: 'Business', subCategory: 'Marketing', averageSalary: '6-15 LPA', salaryRange: '4-30 LPA', demandLevel: 'High', futureDemand: 'Stable', requiredEducation: JSON.stringify(['BBA', 'MBA Marketing']), requiredSkills: JSON.stringify(['Marketing Strategy', 'Digital Marketing', 'Communication']), personality: JSON.stringify(['Creative', 'Strategic']), interests: JSON.stringify(['Marketing', 'Brand Building']), aptitudes: JSON.stringify(['Creativity']), jobRoles: JSON.stringify(['Marketing Executive', 'Manager', 'Director']), workEnvironment: 'Office', careerPath: JSON.stringify(['Executive → Manager → Director']), prosAndCons: JSON.stringify({ pros: ['Creative work', 'Dynamic'], cons: ['Pressure to deliver results'] }) },
  
  { title: 'Human Resources Manager', slug: 'hr-manager', description: 'Manage recruitment, employee relations, and organizational development', detailedInfo: 'HR managers handle hiring, training, performance management, and employee welfare.', category: 'Business', subCategory: 'Human Resources', averageSalary: '5-12 LPA', salaryRange: '3-25 LPA', demandLevel: 'High', futureDemand: 'Stable', requiredEducation: JSON.stringify(['BBA', 'MBA HR']), requiredSkills: JSON.stringify(['Communication', 'Recruitment', 'Employee Relations']), personality: JSON.stringify(['Empathetic', 'Organized']), interests: JSON.stringify(['People', 'Organization']), aptitudes: JSON.stringify(['Interpersonal Skills']), jobRoles: JSON.stringify(['HR Executive', 'HR Manager', 'HR Director']), workEnvironment: 'Office', careerPath: JSON.stringify(['Executive → Manager → Director']), prosAndCons: JSON.stringify({ pros: ['People-oriented', 'Essential role'], cons: ['Handling conflicts'] }) },
  
  { title: 'Chartered Accountant', slug: 'chartered-accountant', description: 'Provide accounting, auditing, and financial advisory services', detailedInfo: 'CAs handle accounts, taxation, auditing, and provide financial consultancy to businesses.', category: 'Business', subCategory: 'Finance', averageSalary: '7-20 LPA', salaryRange: '5-100 LPA', demandLevel: 'High', futureDemand: 'Stable', requiredEducation: JSON.stringify(['CA', 'B.Com']), requiredSkills: JSON.stringify(['Accounting', 'Taxation', 'Auditing', 'Financial Analysis']), personality: JSON.stringify(['Meticulous', 'Analytical']), interests: JSON.stringify(['Finance', 'Numbers']), aptitudes: JSON.stringify(['Numerical Ability']), jobRoles: JSON.stringify(['Junior CA', 'Senior CA', 'Partner']), workEnvironment: 'Office/Firm', careerPath: JSON.stringify(['Article → CA → Partner']), prosAndCons: JSON.stringify({ pros: ['Prestigious', 'Own practice'], cons: ['Tough exam', 'Long hours'] }) },
  
  { title: 'Financial Analyst', slug: 'financial-analyst', description: 'Analyze financial data to guide investment and business decisions', detailedInfo: 'Financial analysts evaluate investments, create financial models, and provide recommendations.', category: 'Business', subCategory: 'Finance', averageSalary: '5-12 LPA', salaryRange: '4-30 LPA', demandLevel: 'High', futureDemand: 'Growing', requiredEducation: JSON.stringify(['B.Com', 'MBA Finance', 'CFA']), requiredSkills: JSON.stringify(['Financial Modeling', 'Excel', 'Analysis', 'Research']), personality: JSON.stringify(['Analytical', 'Detail-oriented']), interests: JSON.stringify(['Finance', 'Markets']), aptitudes: JSON.stringify(['Quantitative Skills']), jobRoles: JSON.stringify(['Analyst', 'Senior Analyst', 'Manager']), workEnvironment: 'Office', careerPath: JSON.stringify(['Junior → Senior → Manager']), prosAndCons: JSON.stringify({ pros: ['Lucrative', 'Growth potential'], cons: ['High pressure', 'Long hours'] }) },

  // CREATIVE (15 careers)
  { title: 'Graphic Designer', slug: 'graphic-designer', description: 'Create visual content for brands, products, and communications', detailedInfo: 'Graphic designers use software to create logos, brochures, social media graphics, and branding materials.', category: 'Creative', subCategory: 'Design', averageSalary: '3-8 LPA', salaryRange: '2-20 LPA', demandLevel: 'High', futureDemand: 'Growing', requiredEducation: JSON.stringify(['Design Degree', 'Portfolio']), requiredSkills: JSON.stringify(['Photoshop', 'Illustrator', 'Creativity', 'Typography']), personality: JSON.stringify(['Creative', 'Visual']), interests: JSON.stringify(['Art', 'Design']), aptitudes: JSON.stringify(['Visual Thinking']), jobRoles: JSON.stringify(['Junior Designer', 'Senior Designer', 'Art Director']), workEnvironment: 'Office/Remote', careerPath: JSON.stringify(['Junior → Senior → Lead']), prosAndCons: JSON.stringify({ pros: ['Creative freedom', 'Remote work'], cons: ['Client revisions', 'Competitive'] }) },
  
  { title: 'UI/UX Designer', slug: 'ui-ux-designer', description: 'Design user interfaces and experiences for digital products', detailedInfo: 'UI/UX designers create intuitive, beautiful interfaces for websites and apps based on user research.', category: 'Creative', subCategory: 'Digital Design', averageSalary: '5-15 LPA', salaryRange: '3-30 LPA', demandLevel: 'High', futureDemand: 'Growing', requiredEducation: JSON.stringify(['Design Degree', 'HCI', 'Portfolio']), requiredSkills: JSON.stringify(['Figma', 'User Research', 'Prototyping', 'Wireframing']), personality: JSON.stringify(['Empathetic', 'Creative']), interests: JSON.stringify(['Design', 'User Experience']), aptitudes: JSON.stringify(['Design Thinking']), jobRoles: JSON.stringify(['UI Designer', 'UX Designer', 'Product Designer']), workEnvironment: 'Office/Remote', careerPath: JSON.stringify(['Junior → Senior → Lead']), prosAndCons: JSON.stringify({ pros: ['High demand', 'User-focused'], cons: ['Stakeholder management'] }) },
  
  { title: 'Content Writer', slug: 'content-writer', description: 'Create written content for websites, blogs, and marketing materials', detailedInfo: 'Content writers produce engaging articles, blogs, website copy, and marketing content.', category: 'Creative', subCategory: 'Writing', averageSalary: '3-7 LPA', salaryRange: '2-15 LPA', demandLevel: 'High', futureDemand: 'Growing', requiredEducation: JSON.stringify(['Any Degree', 'Journalism', 'English']), requiredSkills: JSON.stringify(['Writing', 'SEO', 'Research', 'Creativity']), personality: JSON.stringify(['Creative', 'Articulate']), interests: JSON.stringify(['Writing', 'Content']), aptitudes: JSON.stringify(['Language Skills']), jobRoles: JSON.stringify(['Content Writer', 'Senior Writer', 'Content Manager']), workEnvironment: 'Remote/Office', careerPath: JSON.stringify(['Junior → Senior → Manager']), prosAndCons: JSON.stringify({ pros: ['Remote work', 'Flexible'], cons: ['Deadlines', 'Writer\'s block'] }) },
  
  { title: 'Video Editor', slug: 'video-editor', description: 'Edit and produce video content for various media platforms', detailedInfo: 'Video editors cut footage, add effects, create transitions, and produce polished final videos.', category: 'Creative', subCategory: 'Media Production', averageSalary: '3-8 LPA', salaryRange: '2-20 LPA', demandLevel: 'High', futureDemand: 'Growing', requiredEducation: JSON.stringify(['Any Degree', 'Film School', 'Portfolio']), requiredSkills: JSON.stringify(['Premiere Pro', 'Final Cut', 'After Effects', 'Storytelling']), personality: JSON.stringify(['Creative', 'Technical']), interests: JSON.stringify(['Video', 'Storytelling']), aptitudes: JSON.stringify(['Visual Storytelling']), jobRoles: JSON.stringify(['Junior Editor', 'Senior Editor', 'Lead Editor']), workEnvironment: 'Office/Remote', careerPath: JSON.stringify(['Junior → Senior → Director']), prosAndCons: JSON.stringify({ pros: ['Creative work', 'Growing demand'], cons: ['Long hours', 'Tight deadlines'] }) },
  
  { title: 'Photographer', slug: 'photographer', description: 'Capture professional photographs for events, products, and media', detailedInfo: 'Photographers take professional photos for weddings, events, products, fashion, and journalism.', category: 'Creative', subCategory: 'Photography', averageSalary: '3-10 LPA', salaryRange: '2-50 LPA', demandLevel: 'Medium', futureDemand: 'Stable', requiredEducation: JSON.stringify(['Any Degree', 'Photography Course', 'Portfolio']), requiredSkills: JSON.stringify(['Camera Operation', 'Lighting', 'Editing', 'Composition']), personality: JSON.stringify(['Creative', 'Observant']), interests: JSON.stringify(['Photography', 'Visual Arts']), aptitudes: JSON.stringify(['Visual Perception']), jobRoles: JSON.stringify(['Freelance Photographer', 'Studio Photographer', 'Photo Journalist']), workEnvironment: 'Field/Studio', careerPath: JSON.stringify(['Assistant → Professional → Studio Owner']), prosAndCons: JSON.stringify({ pros: ['Creative freedom', 'Flexible'], cons: ['Equipment costs', 'Irregular income'] }) },

  // COMMERCE (15 careers)
  { title: 'Company Secretary', slug: 'company-secretary', description: 'Ensure company complies with legal and regulatory requirements', detailedInfo: 'Company Secretaries handle corporate governance, compliance, and legal matters for companies.', category: 'Commerce', subCategory: 'Corporate Governance', averageSalary: '6-15 LPA', salaryRange: '4-40 LPA', demandLevel: 'High', futureDemand: 'Stable', requiredEducation: JSON.stringify(['CS', 'B.Com']), requiredSkills: JSON.stringify(['Corporate Law', 'Compliance', 'Governance']), personality: JSON.stringify(['Meticulous', 'Ethical']), interests: JSON.stringify(['Law', 'Corporate Affairs']), aptitudes: JSON.stringify(['Attention to Detail']), jobRoles: JSON.stringify(['Junior CS', 'Company Secretary', 'Senior CS']), workEnvironment: 'Office', careerPath: JSON.stringify(['Junior → Senior → Chief CS']), prosAndCons: JSON.stringify({ pros: ['Professional qualification', 'Essential role'], cons: ['Tough exams', 'Regulatory pressure'] }) },
  
  { title: 'Cost Accountant', slug: 'cost-accountant', description: 'Analyze costs and provide insights for business profitability', detailedInfo: 'Cost Accountants track, analyze, and optimize costs to improve business profitability.', category: 'Commerce', subCategory: 'Accounting', averageSalary: '5-12 LPA', salaryRange: '3-25 LPA', demandLevel: 'High', futureDemand: 'Stable', requiredEducation: JSON.stringify(['CMA', 'B.Com']), requiredSkills: JSON.stringify(['Cost Analysis', 'Budgeting', 'Financial Management']), personality: JSON.stringify(['Analytical', 'Detail-oriented']), interests: JSON.stringify(['Finance', 'Analysis']), aptitudes: JSON.stringify(['Numerical Skills']), jobRoles: JSON.stringify(['Cost Accountant', 'Senior Accountant', 'Manager']), workEnvironment: 'Office', careerPath: JSON.stringify(['Junior → Senior → Manager']), prosAndCons: JSON.stringify({ pros: ['Manufacturing sector demand', 'Good career'], cons: ['Exam difficulty'] }) },
  
  { title: 'Investment Banker', slug: 'investment-banker', description: 'Help companies raise capital and provide financial advisory', detailedInfo: 'Investment bankers assist in mergers, acquisitions, IPOs, and capital raising for corporations.', category: 'Commerce', subCategory: 'Banking', averageSalary: '8-25 LPA', salaryRange: '6-100 LPA', demandLevel: 'Medium', futureDemand: 'Growing', requiredEducation: JSON.stringify(['MBA Finance', 'B.Com', 'CFA']), requiredSkills: JSON.stringify(['Financial Modeling', 'Valuation', 'Deal Making']), personality: JSON.stringify(['Ambitious', 'Analytical']), interests: JSON.stringify(['Finance', 'Deals']), aptitudes: JSON.stringify(['Quantitative Skills']), jobRoles: JSON.stringify(['Analyst', 'Associate', 'VP']), workEnvironment: 'Office', careerPath: JSON.stringify(['Analyst → Associate → VP → Director']), prosAndCons: JSON.stringify({ pros: ['Very high salary', 'Prestigious'], cons: ['80+ hour weeks', 'High stress'] }) },
  
  { title: 'Actuary', slug: 'actuary', description: 'Assess financial risks using mathematics, statistics, and financial theory', detailedInfo: 'Actuaries analyze risks for insurance companies, pension funds, and financial institutions.', category: 'Commerce', subCategory: 'Risk Management', averageSalary: '6-20 LPA', salaryRange: '4-50 LPA', demandLevel: 'Medium', futureDemand: 'Growing', requiredEducation: JSON.stringify(['B.Sc Statistics', 'Actuarial Exams']), requiredSkills: JSON.stringify(['Mathematics', 'Statistics', 'Risk Analysis']), personality: JSON.stringify(['Analytical', 'Precise']), interests: JSON.stringify(['Mathematics', 'Risk']), aptitudes: JSON.stringify(['Mathematical Ability']), jobRoles: JSON.stringify(['Trainee Actuary', 'Actuary', 'Chief Actuary']), workEnvironment: 'Office', careerPath: JSON.stringify(['Trainee → Associate → Fellow']), prosAndCons: JSON.stringify({ pros: ['High salary', 'Niche field'], cons: ['Tough exams', 'Long qualification'] }) },
  
  { title: 'Tax Consultant', slug: 'tax-consultant', description: 'Provide tax planning and compliance services to individuals and businesses', detailedInfo: 'Tax consultants help clients minimize tax liabilities and ensure compliance with tax laws.', category: 'Commerce', subCategory: 'Taxation', averageSalary: '4-10 LPA', salaryRange: '3-30 LPA', demandLevel: 'High', futureDemand: 'Stable', requiredEducation: JSON.stringify(['CA', 'CS', 'MBA Finance']), requiredSkills: JSON.stringify(['Tax Laws', 'Tax Planning', 'Compliance']), personality: JSON.stringify(['Detail-oriented', 'Updated']), interests: JSON.stringify(['Taxation', 'Law']), aptitudes: JSON.stringify(['Logical Reasoning']), jobRoles: JSON.stringify(['Tax Consultant', 'Senior Consultant', 'Partner']), workEnvironment: 'Office', careerPath: JSON.stringify(['Junior → Senior → Partner']), prosAndCons: JSON.stringify({ pros: ['Always in demand', 'Own practice'], cons: ['Tax season pressure'] }) },

  // Adding 50+ more careers across categories...
  { title: 'Digital Marketing Specialist', slug: 'digital-marketing-specialist', description: 'Manage online marketing campaigns and digital presence', detailedInfo: 'Digital marketers create and manage social media, SEO, PPC, and content marketing campaigns.', category: 'Business', subCategory: 'Digital Marketing', averageSalary: '4-10 LPA', salaryRange: '3-20 LPA', demandLevel: 'High', futureDemand: 'Growing', requiredEducation: JSON.stringify(['Any Degree', 'Digital Marketing Certification']), requiredSkills: JSON.stringify(['SEO', 'Social Media', 'Google Ads', 'Analytics']), personality: JSON.stringify(['Creative', 'Analytical']), interests: JSON.stringify(['Marketing', 'Digital']), aptitudes: JSON.stringify(['Digital Savvy']), jobRoles: JSON.stringify(['Executive', 'Specialist', 'Manager']), workEnvironment: 'Office/Remote', careerPath: JSON.stringify(['Executive → Manager → Head']), prosAndCons: JSON.stringify({ pros: ['High demand', 'Creative + analytical'], cons: ['Algorithm changes'] }) },

  { title: 'Interior Designer', slug: 'interior-designer', description: 'Design functional and aesthetically pleasing interior spaces', detailedInfo: 'Interior designers plan layouts, select materials, and create beautiful living and working spaces.', category: 'Creative', subCategory: 'Design', averageSalary: '3-8 LPA', salaryRange: '2-25 LPA', demandLevel: 'Medium', futureDemand: 'Growing', requiredEducation: JSON.stringify(['Interior Design Degree', 'Portfolio']), requiredSkills: JSON.stringify(['3D Design', 'Space Planning', 'Material Knowledge']), personality: JSON.stringify(['Creative', 'Practical']), interests: JSON.stringify(['Design', 'Architecture']), aptitudes: JSON.stringify(['Spatial Visualization']), jobRoles: JSON.stringify(['Junior Designer', 'Designer', 'Lead Designer']), workEnvironment: 'Office/Site', careerPath: JSON.stringify(['Junior → Senior → Firm Owner']), prosAndCons: JSON.stringify({ pros: ['Creative work', 'Own firm possible'], cons: ['Client dependent'] }) },

  { title: 'Fashion Designer', slug: 'fashion-designer', description: 'Create clothing and accessory designs for fashion industry', detailedInfo: 'Fashion designers conceptualize, design, and create clothing, accessories, and fashion products.', category: 'Creative', subCategory: 'Fashion', averageSalary: '3-10 LPA', salaryRange: '2-50 LPA', demandLevel: 'Medium', futureDemand: 'Stable', requiredEducation: JSON.stringify(['Fashion Design Degree', 'NIFT']), requiredSkills: JSON.stringify(['Sketching', 'Trend Forecasting', 'Textile Knowledge']), personality: JSON.stringify(['Creative', 'Trendy']), interests: JSON.stringify(['Fashion', 'Design']), aptitudes: JSON.stringify(['Aesthetic Sense']), jobRoles: JSON.stringify(['Assistant Designer', 'Designer', 'Creative Director']), workEnvironment: 'Studio', careerPath: JSON.stringify(['Assistant → Designer → Label Owner']), prosAndCons: JSON.stringify({ pros: ['Creative field', 'Own label possible'], cons: ['Highly competitive', 'Seasonal'] }) },

  { title: 'Architect', slug: 'architect', description: 'Design buildings and structures combining aesthetics and functionality', detailedInfo: 'Architects plan and design buildings, ensuring structural integrity, aesthetics, and sustainability.', category: 'Engineering', subCategory: 'Architecture', averageSalary: '4-12 LPA', salaryRange: '3-30 LPA', demandLevel: 'High', futureDemand: 'Stable', requiredEducation: JSON.stringify(['B.Arch', 'M.Arch']), requiredSkills: JSON.stringify(['AutoCAD', '3D Modeling', 'Building Codes', 'Creativity']), personality: JSON.stringify(['Creative', 'Technical']), interests: JSON.stringify(['Architecture', 'Design']), aptitudes: JSON.stringify(['Spatial Reasoning']), jobRoles: JSON.stringify(['Junior Architect', 'Architect', 'Principal Architect']), workEnvironment: 'Office/Site', careerPath: JSON.stringify(['Junior → Senior → Principal']), prosAndCons: JSON.stringify({ pros: ['Creative + technical', 'Own firm'], cons: ['5-year degree', 'Project cycles'] }) },

  { title: 'Data Analyst', slug: 'data-analyst', description: 'Analyze data to provide business insights and recommendations', detailedInfo: 'Data analysts collect, process, and analyze data to help businesses make informed decisions.', category: 'Technology', subCategory: 'Data Analytics', averageSalary: '4-10 LPA', salaryRange: '3-18 LPA', demandLevel: 'High', futureDemand: 'Growing', requiredEducation: JSON.stringify(['Any Degree', 'Statistics', 'Analytics Course']), requiredSkills: JSON.stringify(['Excel', 'SQL', 'Python', 'Tableau']), personality: JSON.stringify(['Analytical', 'Curious']), interests: JSON.stringify(['Data', 'Analysis']), aptitudes: JSON.stringify(['Quantitative Thinking']), jobRoles: JSON.stringify(['Junior Analyst', 'Analyst', 'Senior Analyst']), workEnvironment: 'Office/Remote', careerPath: JSON.stringify(['Junior → Senior → Lead']), prosAndCons: JSON.stringify({ pros: ['High demand', 'Versatile skill'], cons: ['Continuous learning'] }) },

  { title: 'Product Manager', slug: 'product-manager', description: 'Define product vision and drive product development and strategy', detailedInfo: 'Product managers own product roadmap, work with engineering and design, and drive product success.', category: 'Technology', subCategory: 'Product Management', averageSalary: '8-20 LPA', salaryRange: '6-50 LPA', demandLevel: 'High', futureDemand: 'Growing', requiredEducation: JSON.stringify(['Any Degree', 'MBA', 'Tech Background']), requiredSkills: JSON.stringify(['Product Strategy', 'Analytics', 'Communication', 'Agile']), personality: JSON.stringify(['Strategic', 'Leadership']), interests: JSON.stringify(['Products', 'Technology']), aptitudes: JSON.stringify(['Strategic Thinking']), jobRoles: JSON.stringify(['Associate PM', 'PM', 'Senior PM']), workEnvironment: 'Office', careerPath: JSON.stringify(['Associate → PM → Senior → VP']), prosAndCons: JSON.stringify({ pros: ['High impact', 'Excellent salary'], cons: ['High responsibility', 'Stakeholder management'] }) },

  { title: 'Teacher', slug: 'teacher', description: 'Educate and inspire students in schools and educational institutions', detailedInfo: 'Teachers plan lessons, teach curriculum, assess students, and contribute to their overall development.', category: 'Education', subCategory: 'Teaching', averageSalary: '3-7 LPA', salaryRange: '2-15 LPA', demandLevel: 'High', futureDemand: 'Stable', requiredEducation: JSON.stringify(['B.Ed', 'Subject Degree', 'M.Ed']), requiredSkills: JSON.stringify(['Subject Knowledge', 'Communication', 'Patience', 'Classroom Management']), personality: JSON.stringify(['Patient', 'Nurturing']), interests: JSON.stringify(['Teaching', 'Education']), aptitudes: JSON.stringify(['Communication']), jobRoles: JSON.stringify(['Teacher', 'Senior Teacher', 'Principal']), workEnvironment: 'School', careerPath: JSON.stringify(['Teacher → Senior → Coordinator → Principal']), prosAndCons: JSON.stringify({ pros: ['Noble profession', 'Stable', 'Holidays'], cons: ['Salary can be low', 'Workload'] }) },

  { title: 'Hotel Manager', slug: 'hotel-manager', description: 'Oversee hotel operations and ensure excellent guest experiences', detailedInfo: 'Hotel managers handle operations, staff, guest services, and ensure smooth hotel functioning.', category: 'Hospitality', subCategory: 'Hotel Management', averageSalary: '4-10 LPA', salaryRange: '3-25 LPA', demandLevel: 'Medium', futureDemand: 'Growing', requiredEducation: JSON.stringify(['Hotel Management Degree', 'BHM']), requiredSkills: JSON.stringify(['Management', 'Customer Service', 'Operations']), personality: JSON.stringify(['Organized', 'People-oriented']), interests: JSON.stringify(['Hospitality', 'Service']), aptitudes: JSON.stringify(['People Skills']), jobRoles: JSON.stringify(['Assistant Manager', 'Manager', 'General Manager']), workEnvironment: 'Hotel', careerPath: JSON.stringify(['Assistant → Manager → General Manager']), prosAndCons: JSON.stringify({ pros: ['Growing industry', 'Guest interaction'], cons: ['Long hours', 'Weekend work'] }) },

  { title: 'Chef', slug: 'chef', description: 'Prepare and create culinary dishes in restaurants and hotels', detailedInfo: 'Chefs plan menus, prepare dishes, manage kitchen staff, and ensure food quality.', category: 'Hospitality', subCategory: 'Culinary', averageSalary: '3-10 LPA', salaryRange: '2-30 LPA', demandLevel: 'Medium', futureDemand: 'Growing', requiredEducation: JSON.stringify(['Culinary Arts Degree', 'Hotel Management']), requiredSkills: JSON.stringify(['Cooking', 'Menu Planning', 'Food Safety', 'Creativity']), personality: JSON.stringify(['Creative', 'Hardworking']), interests: JSON.stringify(['Cooking', 'Food']), aptitudes: JSON.stringify(['Culinary Skills']), jobRoles: JSON.stringify(['Commis Chef', 'Sous Chef', 'Head Chef']), workEnvironment: 'Kitchen', careerPath: JSON.stringify(['Commis → Sous → Head Chef → Executive Chef']), prosAndCons: JSON.stringify({ pros: ['Creative', 'Own restaurant possible'], cons: ['Long standing hours', 'Hot environment'] }) },

  { title: 'Pilot', slug: 'pilot', description: 'Fly commercial or private aircraft transporting passengers and cargo', detailedInfo: 'Pilots operate aircraft, ensure passenger safety, and navigate flights.', category: 'Aviation', subCategory: 'Flying', averageSalary: '10-40 LPA', salaryRange: '8-100 LPA', demandLevel: 'Medium', futureDemand: 'Growing', requiredEducation: JSON.stringify(['CPL License', '10+2 Physics/Maths']), requiredSkills: JSON.stringify(['Flying', 'Navigation', 'Decision Making', 'Communication']), personality: JSON.stringify(['Focused', 'Responsible']), interests: JSON.stringify(['Aviation', 'Flying']), aptitudes: JSON.stringify(['Spatial Awareness']), jobRoles: JSON.stringify(['First Officer', 'Captain', 'Senior Captain']), workEnvironment: 'Aircraft', careerPath: JSON.stringify(['First Officer → Captain → Senior Captain']), prosAndCons: JSON.stringify({ pros: ['High salary', 'Travel', 'Prestige'], cons: ['Expensive training', 'Health requirements', 'Irregular hours'] }) },

  { title: 'Lawyer', slug: 'lawyer', description: 'Represent clients in legal matters and provide legal advice', detailedInfo: 'Lawyers practice law, represent clients in court, provide legal counsel, and handle legal documentation.', category: 'Law', subCategory: 'Legal Practice', averageSalary: '5-15 LPA', salaryRange: '3-100 LPA', demandLevel: 'High', futureDemand: 'Stable', requiredEducation: JSON.stringify(['LLB', 'BA LLB', 'LLM']), requiredSkills: JSON.stringify(['Legal Knowledge', 'Research', 'Argumentation', 'Writing']), personality: JSON.stringify(['Argumentative', 'Logical']), interests: JSON.stringify(['Law', 'Justice']), aptitudes: JSON.stringify(['Verbal Reasoning']), jobRoles: JSON.stringify(['Junior Lawyer', 'Senior Lawyer', 'Partner']), workEnvironment: 'Court/Office', careerPath: JSON.stringify(['Junior → Senior → Partner/Judge']), prosAndCons: JSON.stringify({ pros: ['Prestigious', 'Own practice', 'Good income'], cons: ['Takes time to establish', 'Court delays'] }) },

  { title: 'Journalist', slug: 'journalist', description: 'Research, write, and report news stories for media outlets', detailedInfo: 'Journalists investigate stories, conduct interviews, and report news through various media.', category: 'Media', subCategory: 'Journalism', averageSalary: '3-8 LPA', salaryRange: '2-20 LPA', demandLevel: 'Medium', futureDemand: 'Stable', requiredEducation: JSON.stringify(['Journalism Degree', 'Mass Communication']), requiredSkills: JSON.stringify(['Writing', 'Research', 'Interviewing', 'Ethics']), personality: JSON.stringify(['Curious', 'Articulate']), interests: JSON.stringify(['News', 'Current Affairs']), aptitudes: JSON.stringify(['Communication']), jobRoles: JSON.stringify(['Reporter', 'Correspondent', 'Editor']), workEnvironment: 'Field/Office', careerPath: JSON.stringify(['Reporter → Senior Reporter → Editor']), prosAndCons: JSON.stringify({ pros: ['Dynamic', 'Impactful', 'Events coverage'], cons: ['Irregular hours', 'Pressure'] }) },

  { title: 'Psychologist', slug: 'psychologist', description: 'Assess and treat mental health and behavioral issues', detailedInfo: 'Psychologists provide therapy, counseling, and psychological assessments to help people with mental health.', category: 'Healthcare', subCategory: 'Mental Health', averageSalary: '4-10 LPA', salaryRange: '3-20 LPA', demandLevel: 'Growing', futureDemand: 'Growing', requiredEducation: JSON.stringify(['M.A Psychology', 'M.Phil', 'PhD']), requiredSkills: JSON.stringify(['Counseling', 'Assessment', 'Empathy', 'Communication']), personality: JSON.stringify(['Empathetic', 'Patient']), interests: JSON.stringify(['Psychology', 'Helping']), aptitudes: JSON.stringify(['Emotional Intelligence']), jobRoles: JSON.stringify(['Clinical Psychologist', 'Counselor', 'Therapist']), workEnvironment: 'Clinic/Hospital', careerPath: JSON.stringify(['Trainee → Psychologist → Senior → Consultant']), prosAndCons: JSON.stringify({ pros: ['Rewarding', 'Growing awareness'], cons: ['Emotionally demanding', 'Private practice setup cost'] }) },

  { title: 'Social Media Manager', slug: 'social-media-manager', description: 'Manage brand presence and engagement on social media platforms', detailedInfo: 'Social media managers create content, manage accounts, engage with audiences, and track metrics.', category: 'Business', subCategory: 'Social Media', averageSalary: '4-10 LPA', salaryRange: '3-20 LPA', demandLevel: 'High', futureDemand: 'Growing', requiredEducation: JSON.stringify(['Any Degree', 'Marketing/Communications']), requiredSkills: JSON.stringify(['Content Creation', 'Social Media Tools', 'Analytics', 'Creativity']), personality: JSON.stringify(['Creative', 'Trendy']), interests: JSON.stringify(['Social Media', 'Marketing']), aptitudes: JSON.stringify(['Digital Communication']), jobRoles: JSON.stringify(['Executive', 'Manager', 'Head of Social']), workEnvironment: 'Office/Remote', careerPath: JSON.stringify(['Executive → Manager → Head']), prosAndCons: JSON.stringify({ pros: ['Creative work', 'Remote possible', 'Dynamic'], cons: ['24/7 monitoring', 'Algorithm changes'] }) },

  { title: 'Event Manager', slug: 'event-manager', description: 'Plan and execute events, conferences, and celebrations', detailedInfo: 'Event managers conceptualize, plan, coordinate, and execute corporate events, weddings, and conferences.', category: 'Hospitality', subCategory: 'Event Management', averageSalary: '3-8 LPA', salaryRange: '2-20 LPA', demandLevel: 'Medium', futureDemand: 'Growing', requiredEducation: JSON.stringify(['Event Management', 'Hotel Management', 'Any Degree']), requiredSkills: JSON.stringify(['Planning', 'Coordination', 'Vendor Management', 'Creativity']), personality: JSON.stringify(['Organized', 'Energetic']), interests: JSON.stringify(['Events', 'Coordination']), aptitudes: JSON.stringify(['Multitasking']), jobRoles: JSON.stringify(['Event Coordinator', 'Manager', 'Director']), workEnvironment: 'Office/Venue', careerPath: JSON.stringify(['Coordinator → Manager → Own Company']), prosAndCons: JSON.stringify({ pros: ['Creative', 'Dynamic', 'Networking'], cons: ['Irregular hours', 'High pressure', 'Weekend work'] }) },

  // Additional Engineering & Technology Careers (20 more)
  { title: 'AI/ML Engineer', slug: 'ai-ml-engineer', description: 'Build artificial intelligence and machine learning models', detailedInfo: 'AI/ML engineers develop intelligent systems using deep learning, neural networks, and advanced algorithms.', category: 'Technology', subCategory: 'Artificial Intelligence', averageSalary: '10-25 LPA', salaryRange: '7-60 LPA', demandLevel: 'High', futureDemand: 'Booming', requiredEducation: JSON.stringify(['B.Tech', 'M.Tech AI/ML']), requiredSkills: JSON.stringify(['Python', 'TensorFlow', 'PyTorch', 'Deep Learning']), personality: JSON.stringify(['Innovative', 'Mathematical']), interests: JSON.stringify(['AI', 'Research']), aptitudes: JSON.stringify(['Mathematical Reasoning']), jobRoles: JSON.stringify(['ML Engineer', 'Research Scientist', 'AI Architect']), workEnvironment: 'Office/Remote', careerPath: JSON.stringify(['Engineer → Senior → Lead → Architect']), prosAndCons: JSON.stringify({ pros: ['Cutting-edge tech', 'Very high salary'], cons: ['Complex problems', 'Continuous research'] }) },

  { title: 'Blockchain Developer', slug: 'blockchain-developer', description: 'Develop decentralized applications and blockchain solutions', detailedInfo: 'Blockchain developers create smart contracts, DApps, and blockchain-based systems.', category: 'Technology', subCategory: 'Blockchain', averageSalary: '8-20 LPA', salaryRange: '6-50 LPA', demandLevel: 'Medium', futureDemand: 'Growing', requiredEducation: JSON.stringify(['B.Tech', 'Blockchain Certification']), requiredSkills: JSON.stringify(['Solidity', 'Ethereum', 'Smart Contracts', 'Cryptography']), personality: JSON.stringify(['Innovative', 'Security-conscious']), interests: JSON.stringify(['Blockchain', 'Crypto']), aptitudes: JSON.stringify(['Logical Thinking']), jobRoles: JSON.stringify(['Blockchain Dev', 'Smart Contract Dev', 'Blockchain Architect']), workEnvironment: 'Remote/Office', careerPath: JSON.stringify(['Developer → Senior → Architect']), prosAndCons: JSON.stringify({ pros: ['Emerging field', 'High salary'], cons: ['Volatility', 'Niche market'] }) },

  { title: 'Game Developer', slug: 'game-developer', description: 'Design and develop video games for various platforms', detailedInfo: 'Game developers create gameplay mechanics, graphics, and immersive gaming experiences.', category: 'Technology', subCategory: 'Game Development', averageSalary: '4-12 LPA', salaryRange: '3-30 LPA', demandLevel: 'Medium', futureDemand: 'Growing', requiredEducation: JSON.stringify(['B.Tech', 'Game Design Course']), requiredSkills: JSON.stringify(['Unity', 'Unreal Engine', 'C++', 'Game Design']), personality: JSON.stringify(['Creative', 'Technical']), interests: JSON.stringify(['Gaming', 'Programming']), aptitudes: JSON.stringify(['Creative Thinking']), jobRoles: JSON.stringify(['Junior Dev', 'Game Developer', 'Lead Developer']), workEnvironment: 'Office', careerPath: JSON.stringify(['Junior → Senior → Lead']), prosAndCons: JSON.stringify({ pros: ['Fun industry', 'Creative'], cons: ['Crunch time', 'Competitive'] }) },

  { title: 'Network Engineer', slug: 'network-engineer', description: 'Design, implement, and maintain computer networks', detailedInfo: 'Network engineers set up and manage LANs, WANs, and network infrastructure for organizations.', category: 'Technology', subCategory: 'Networking', averageSalary: '4-10 LPA', salaryRange: '3-20 LPA', demandLevel: 'High', futureDemand: 'Stable', requiredEducation: JSON.stringify(['B.Tech', 'CCNA/CCNP']), requiredSkills: JSON.stringify(['Networking', 'Cisco', 'Routing', 'Security']), personality: JSON.stringify(['Analytical', 'Problem-solver']), interests: JSON.stringify(['Networks', 'Infrastructure']), aptitudes: JSON.stringify(['Technical Skills']), jobRoles: JSON.stringify(['Network Admin', 'Network Engineer', 'Network Architect']), workEnvironment: 'Office', careerPath: JSON.stringify(['Admin → Engineer → Architect']), prosAndCons: JSON.stringify({ pros: ['Essential skill', 'Stable'], cons: ['On-call support'] }) },

  { title: 'Database Administrator', slug: 'database-administrator', description: 'Manage and maintain organizational databases', detailedInfo: 'DBAs ensure database performance, security, backup, and recovery for critical business data.', category: 'Technology', subCategory: 'Database', averageSalary: '5-12 LPA', salaryRange: '4-25 LPA', demandLevel: 'High', futureDemand: 'Stable', requiredEducation: JSON.stringify(['B.Tech', 'MCA', 'Database Certification']), requiredSkills: JSON.stringify(['SQL', 'Oracle', 'MySQL', 'Performance Tuning']), personality: JSON.stringify(['Meticulous', 'Reliable']), interests: JSON.stringify(['Data', 'Systems']), aptitudes: JSON.stringify(['Attention to Detail']), jobRoles: JSON.stringify(['Junior DBA', 'DBA', 'Senior DBA']), workEnvironment: 'Office', careerPath: JSON.stringify(['Junior → Senior → Lead']), prosAndCons: JSON.stringify({ pros: ['Critical role', 'Stable career'], cons: ['On-call duties', 'Pressure'] }) },

  { title: 'Quality Assurance Engineer', slug: 'qa-engineer', description: 'Test software to ensure quality and identify bugs', detailedInfo: 'QA engineers design test cases, perform manual and automated testing, and ensure software quality.', category: 'Technology', subCategory: 'Testing', averageSalary: '4-10 LPA', salaryRange: '3-18 LPA', demandLevel: 'High', futureDemand: 'Stable', requiredEducation: JSON.stringify(['B.Tech', 'BCA', 'Any Degree']), requiredSkills: JSON.stringify(['Testing', 'Selenium', 'Automation', 'Bug Tracking']), personality: JSON.stringify(['Detail-oriented', 'Patient']), interests: JSON.stringify(['Quality', 'Testing']), aptitudes: JSON.stringify(['Analytical Thinking']), jobRoles: JSON.stringify(['QA Tester', 'QA Engineer', 'QA Lead']), workEnvironment: 'Office', careerPath: JSON.stringify(['Tester → Engineer → Lead']), prosAndCons: JSON.stringify({ pros: ['Entry-friendly', 'Stable'], cons: ['Repetitive tasks'] }) },

  { title: 'Systems Analyst', slug: 'systems-analyst', description: 'Analyze and improve IT systems and business processes', detailedInfo: 'Systems analysts bridge business needs and IT solutions by analyzing systems and recommending improvements.', category: 'Technology', subCategory: 'Systems', averageSalary: '5-12 LPA', salaryRange: '4-22 LPA', demandLevel: 'High', futureDemand: 'Stable', requiredEducation: JSON.stringify(['B.Tech', 'MCA', 'BCA']), requiredSkills: JSON.stringify(['Systems Analysis', 'Requirements Gathering', 'Documentation']), personality: JSON.stringify(['Analytical', 'Communicative']), interests: JSON.stringify(['Systems', 'Business']), aptitudes: JSON.stringify(['Problem Solving']), jobRoles: JSON.stringify(['Junior Analyst', 'Systems Analyst', 'Senior Analyst']), workEnvironment: 'Office', careerPath: JSON.stringify(['Junior → Senior → Manager']), prosAndCons: JSON.stringify({ pros: ['Business + tech', 'Diverse work'], cons: ['Meetings heavy'] }) },

  { title: 'Embedded Systems Engineer', slug: 'embedded-systems-engineer', description: 'Design and develop embedded hardware and software systems', detailedInfo: 'Embedded engineers work on microcontrollers, firmware, and hardware-software integration.', category: 'Engineering', subCategory: 'Embedded Systems', averageSalary: '4-12 LPA', salaryRange: '3-25 LPA', demandLevel: 'High', futureDemand: 'Growing', requiredEducation: JSON.stringify(['B.Tech ECE/EEE', 'M.Tech']), requiredSkills: JSON.stringify(['C/C++', 'Microcontrollers', 'RTOS', 'Hardware']), personality: JSON.stringify(['Technical', 'Precise']), interests: JSON.stringify(['Electronics', 'Programming']), aptitudes: JSON.stringify(['Technical Aptitude']), jobRoles: JSON.stringify(['Embedded Engineer', 'Senior Engineer', 'Lead']), workEnvironment: 'Lab/Office', careerPath: JSON.stringify(['Engineer → Senior → Architect']), prosAndCons: JSON.stringify({ pros: ['Hardware + software', 'IoT growth'], cons: ['Complex debugging'] }) },

  { title: 'Robotics Engineer', slug: 'robotics-engineer', description: 'Design and build robots and automated systems', detailedInfo: 'Robotics engineers create robots for manufacturing, healthcare, space, and consumer applications.', category: 'Engineering', subCategory: 'Robotics', averageSalary: '5-15 LPA', salaryRange: '4-35 LPA', demandLevel: 'Medium', futureDemand: 'Growing', requiredEducation: JSON.stringify(['B.Tech Robotics/Mechanical', 'M.Tech']), requiredSkills: JSON.stringify(['Robotics', 'Control Systems', 'Programming', 'Mechanics']), personality: JSON.stringify(['Innovative', 'Technical']), interests: JSON.stringify(['Robotics', 'Automation']), aptitudes: JSON.stringify(['Engineering Thinking']), jobRoles: JSON.stringify(['Robotics Engineer', 'Senior Engineer', 'Research Scientist']), workEnvironment: 'Lab/Factory', careerPath: JSON.stringify(['Engineer → Senior → Lead']), prosAndCons: JSON.stringify({ pros: ['Cutting-edge', 'Future-oriented'], cons: ['Niche field', 'Expensive equipment'] }) },

  { title: 'Biomedical Engineer', slug: 'biomedical-engineer', description: 'Develop medical devices and healthcare technology', detailedInfo: 'Biomedical engineers design prosthetics, medical imaging devices, and healthcare solutions.', category: 'Engineering', subCategory: 'Biomedical', averageSalary: '4-10 LPA', salaryRange: '3-20 LPA', demandLevel: 'Medium', futureDemand: 'Growing', requiredEducation: JSON.stringify(['B.Tech Biomedical', 'M.Tech']), requiredSkills: JSON.stringify(['Medical Devices', 'Biology', 'Engineering', 'Research']), personality: JSON.stringify(['Innovative', 'Detail-oriented']), interests: JSON.stringify(['Healthcare', 'Engineering']), aptitudes: JSON.stringify(['Scientific Thinking']), jobRoles: JSON.stringify(['Biomedical Engineer', 'Medical Device Engineer', 'Research Scientist']), workEnvironment: 'Lab/Hospital', careerPath: JSON.stringify(['Engineer → Senior → Manager']), prosAndCons: JSON.stringify({ pros: ['Impactful', 'Growing field'], cons: ['Regulatory compliance', 'Niche'] }) },

  // Additional Medical & Healthcare (10 more)
  { title: 'Medical Lab Technician', slug: 'medical-lab-technician', description: 'Conduct laboratory tests and analyze medical samples', detailedInfo: 'MLTs perform blood tests, urine analysis, and diagnostic tests to help doctors diagnose diseases.', category: 'Medical', subCategory: 'Laboratory', averageSalary: '2-5 LPA', salaryRange: '1.8-10 LPA', demandLevel: 'High', futureDemand: 'Stable', requiredEducation: JSON.stringify(['B.Sc MLT', 'Diploma MLT']), requiredSkills: JSON.stringify(['Lab Techniques', 'Equipment Operation', 'Accuracy']), personality: JSON.stringify(['Precise', 'Analytical']), interests: JSON.stringify(['Science', 'Healthcare']), aptitudes: JSON.stringify(['Attention to Detail']), jobRoles: JSON.stringify(['Lab Technician', 'Senior Technician', 'Lab Manager']), workEnvironment: 'Laboratory', careerPath: JSON.stringify(['Technician → Senior → Manager']), prosAndCons: JSON.stringify({ pros: ['Essential role', 'Job security'], cons: ['Repetitive', 'Limited growth'] }) },

  { title: 'Radiologist', slug: 'radiologist', description: 'Diagnose diseases using medical imaging techniques', detailedInfo: 'Radiologists interpret X-rays, CT scans, MRI, and ultrasound to diagnose medical conditions.', category: 'Medical', subCategory: 'Radiology', averageSalary: '10-25 LPA', salaryRange: '8-80 LPA', demandLevel: 'High', futureDemand: 'Growing', requiredEducation: JSON.stringify(['MBBS', 'MD Radiology']), requiredSkills: JSON.stringify(['Medical Imaging', 'Diagnosis', 'Reporting']), personality: JSON.stringify(['Analytical', 'Precise']), interests: JSON.stringify(['Medicine', 'Imaging']), aptitudes: JSON.stringify(['Visual Analysis']), jobRoles: JSON.stringify(['Resident', 'Radiologist', 'Senior Consultant']), workEnvironment: 'Hospital', careerPath: JSON.stringify(['Resident → Consultant → Senior Consultant']), prosAndCons: JSON.stringify({ pros: ['High salary', 'Critical role'], cons: ['Long training', 'Radiation exposure'] }) },

  { title: 'Veterinarian', slug: 'veterinarian', description: 'Diagnose and treat animals and pets', detailedInfo: 'Veterinarians provide medical care to animals, perform surgeries, and promote animal health.', category: 'Medical', subCategory: 'Veterinary', averageSalary: '4-10 LPA', salaryRange: '3-25 LPA', demandLevel: 'Medium', futureDemand: 'Growing', requiredEducation: JSON.stringify(['B.V.Sc', 'M.V.Sc']), requiredSkills: JSON.stringify(['Animal Care', 'Diagnosis', 'Surgery', 'Compassion']), personality: JSON.stringify(['Compassionate', 'Patient']), interests: JSON.stringify(['Animals', 'Healthcare']), aptitudes: JSON.stringify(['Empathy']), jobRoles: JSON.stringify(['Veterinarian', 'Senior Vet', 'Clinic Owner']), workEnvironment: 'Clinic/Farm', careerPath: JSON.stringify(['Vet → Senior → Clinic Owner']), prosAndCons: JSON.stringify({ pros: ['Love for animals', 'Own clinic possible'], cons: ['Animal handling challenges', 'Irregular hours'] }) },

  { title: 'Nutritionist/Dietitian', slug: 'nutritionist-dietitian', description: 'Provide dietary advice and nutrition planning', detailedInfo: 'Nutritionists assess nutritional needs and create diet plans for health, weight management, and disease.', category: 'Healthcare', subCategory: 'Nutrition', averageSalary: '3-7 LPA', salaryRange: '2-15 LPA', demandLevel: 'Medium', futureDemand: 'Growing', requiredEducation: JSON.stringify(['B.Sc Nutrition', 'M.Sc Dietetics']), requiredSkills: JSON.stringify(['Nutrition Science', 'Diet Planning', 'Counseling']), personality: JSON.stringify(['Helpful', 'Knowledgeable']), interests: JSON.stringify(['Health', 'Nutrition']), aptitudes: JSON.stringify(['Scientific Knowledge']), jobRoles: JSON.stringify(['Dietitian', 'Clinical Nutritionist', 'Consultant']), workEnvironment: 'Hospital/Clinic', careerPath: JSON.stringify(['Dietitian → Senior → Consultant']), prosAndCons: JSON.stringify({ pros: ['Growing health awareness', 'Own practice'], cons: ['Client compliance issues'] }) },

  { title: 'Occupational Therapist', slug: 'occupational-therapist', description: 'Help patients develop or recover daily living skills', detailedInfo: 'Occupational therapists help people with injuries or disabilities perform daily activities.', category: 'Healthcare', subCategory: 'Therapy', averageSalary: '3-7 LPA', salaryRange: '2-12 LPA', demandLevel: 'Medium', futureDemand: 'Growing', requiredEducation: JSON.stringify(['BOT', 'MOT']), requiredSkills: JSON.stringify(['Therapy Techniques', 'Assessment', 'Patient Care']), personality: JSON.stringify(['Patient', 'Caring']), interests: JSON.stringify(['Healthcare', 'Rehabilitation']), aptitudes: JSON.stringify(['Empathy']), jobRoles: JSON.stringify(['OT', 'Senior OT', 'Consultant']), workEnvironment: 'Hospital/Clinic', careerPath: JSON.stringify(['OT → Senior → Manager']), prosAndCons: JSON.stringify({ pros: ['Rewarding', 'Growing demand'], cons: ['Physically demanding'] }) },

  // Additional Business & Commerce (15 more)
  { title: 'Sales Manager', slug: 'sales-manager', description: 'Lead sales teams and drive revenue growth', detailedInfo: 'Sales managers set targets, manage sales teams, develop strategies, and achieve business goals.', category: 'Business', subCategory: 'Sales', averageSalary: '5-15 LPA', salaryRange: '4-40 LPA', demandLevel: 'High', futureDemand: 'Stable', requiredEducation: JSON.stringify(['BBA', 'MBA', 'Any Degree']), requiredSkills: JSON.stringify(['Sales', 'Leadership', 'Communication', 'Negotiation']), personality: JSON.stringify(['Persuasive', 'Energetic']), interests: JSON.stringify(['Sales', 'Business']), aptitudes: JSON.stringify(['Interpersonal Skills']), jobRoles: JSON.stringify(['Sales Executive', 'Manager', 'Director']), workEnvironment: 'Office/Field', careerPath: JSON.stringify(['Executive → Manager → Director']), prosAndCons: JSON.stringify({ pros: ['High earning potential', 'Incentives'], cons: ['Targets pressure', 'Travel'] }) },

  { title: 'Supply Chain Manager', slug: 'supply-chain-manager', description: 'Manage logistics, procurement, and supply chain operations', detailedInfo: 'Supply chain managers optimize procurement, inventory, warehousing, and distribution.', category: 'Business', subCategory: 'Operations', averageSalary: '6-15 LPA', salaryRange: '4-30 LPA', demandLevel: 'High', futureDemand: 'Growing', requiredEducation: JSON.stringify(['BBA', 'MBA Operations']), requiredSkills: JSON.stringify(['Logistics', 'Planning', 'Analytics', 'Negotiation']), personality: JSON.stringify(['Organized', 'Analytical']), interests: JSON.stringify(['Operations', 'Logistics']), aptitudes: JSON.stringify(['Planning Skills']), jobRoles: JSON.stringify(['Coordinator', 'Manager', 'Director']), workEnvironment: 'Office/Warehouse', careerPath: JSON.stringify(['Coordinator → Manager → Director']), prosAndCons: JSON.stringify({ pros: ['Critical function', 'Good growth'], cons: ['Pressure', 'Supplier management'] }) },

  { title: 'Management Consultant', slug: 'management-consultant', description: 'Advise organizations on strategy and business improvements', detailedInfo: 'Management consultants analyze business problems and provide strategic recommendations.', category: 'Business', subCategory: 'Consulting', averageSalary: '8-20 LPA', salaryRange: '6-50 LPA', demandLevel: 'Medium', futureDemand: 'Growing', requiredEducation: JSON.stringify(['MBA', 'Engineering + MBA']), requiredSkills: JSON.stringify(['Analysis', 'Strategy', 'Problem Solving', 'Communication']), personality: JSON.stringify(['Analytical', 'Strategic']), interests: JSON.stringify(['Business', 'Strategy']), aptitudes: JSON.stringify(['Critical Thinking']), jobRoles: JSON.stringify(['Analyst', 'Consultant', 'Manager']), workEnvironment: 'Office/Client Site', careerPath: JSON.stringify(['Analyst → Consultant → Partner']), prosAndCons: JSON.stringify({ pros: ['High salary', 'Prestigious', 'Learning'], cons: ['Long hours', 'Travel heavy'] }) },

  { title: 'Entrepreneur', slug: 'entrepreneur', description: 'Start and manage your own business venture', detailedInfo: 'Entrepreneurs create innovative business ideas, secure funding, and build companies from scratch.', category: 'Business', subCategory: 'Entrepreneurship', averageSalary: 'Variable', salaryRange: '0-Unlimited', demandLevel: 'Medium', futureDemand: 'Growing', requiredEducation: JSON.stringify(['Any Degree', 'Business Knowledge']), requiredSkills: JSON.stringify(['Vision', 'Leadership', 'Risk-taking', 'Persistence']), personality: JSON.stringify(['Innovative', 'Resilient']), interests: JSON.stringify(['Business', 'Innovation']), aptitudes: JSON.stringify(['Entrepreneurial Spirit']), jobRoles: JSON.stringify(['Founder', 'CEO', 'Business Owner']), workEnvironment: 'Variable', careerPath: JSON.stringify(['Startup → Growth → Scale/Exit']), prosAndCons: JSON.stringify({ pros: ['Unlimited potential', 'Freedom', 'Impact'], cons: ['High risk', 'Uncertainty', 'Stress'] }) },

  { title: 'Real Estate Agent', slug: 'real-estate-agent', description: 'Help clients buy, sell, and rent properties', detailedInfo: 'Real estate agents facilitate property transactions, provide market insights, and negotiate deals.', category: 'Business', subCategory: 'Real Estate', averageSalary: '3-10 LPA', salaryRange: '2-50 LPA', demandLevel: 'Medium', futureDemand: 'Stable', requiredEducation: JSON.stringify(['Any Degree', 'RERA Registration']), requiredSkills: JSON.stringify(['Sales', 'Negotiation', 'Market Knowledge', 'Networking']), personality: JSON.stringify(['Persuasive', 'Networker']), interests: JSON.stringify(['Real Estate', 'Sales']), aptitudes: JSON.stringify(['People Skills']), jobRoles: JSON.stringify(['Agent', 'Senior Agent', 'Broker']), workEnvironment: 'Field/Office', careerPath: JSON.stringify(['Agent → Senior → Broker/Firm Owner']), prosAndCons: JSON.stringify({ pros: ['High commissions', 'Flexible hours'], cons: ['Market dependent', 'Irregular income'] }) },

  { title: 'Stock Broker', slug: 'stock-broker', description: 'Buy and sell securities on behalf of clients', detailedInfo: 'Stock brokers execute trades, provide investment advice, and manage client portfolios.', category: 'Commerce', subCategory: 'Trading', averageSalary: '4-12 LPA', salaryRange: '3-30 LPA', demandLevel: 'Medium', futureDemand: 'Stable', requiredEducation: JSON.stringify(['B.Com', 'MBA Finance', 'NISM Certification']), requiredSkills: JSON.stringify(['Market Knowledge', 'Analysis', 'Client Management']), personality: JSON.stringify(['Analytical', 'Risk-aware']), interests: JSON.stringify(['Stock Market', 'Finance']), aptitudes: JSON.stringify(['Numerical Skills']), jobRoles: JSON.stringify(['Junior Broker', 'Broker', 'Senior Broker']), workEnvironment: 'Office', careerPath: JSON.stringify(['Junior → Senior → Own Firm']), prosAndCons: JSON.stringify({ pros: ['Exciting', 'Good earnings'], cons: ['Market volatility', 'Stress'] }) },

  { title: 'Insurance Agent', slug: 'insurance-agent', description: 'Sell insurance policies and provide coverage advice', detailedInfo: 'Insurance agents sell life, health, vehicle, and property insurance policies to individuals and businesses.', category: 'Commerce', subCategory: 'Insurance', averageSalary: '3-8 LPA', salaryRange: '2-20 LPA', demandLevel: 'Medium', futureDemand: 'Growing', requiredEducation: JSON.stringify(['Any Degree', 'Insurance Certification']), requiredSkills: JSON.stringify(['Sales', 'Product Knowledge', 'Communication']), personality: JSON.stringify(['Persuasive', 'Persistent']), interests: JSON.stringify(['Sales', 'Finance']), aptitudes: JSON.stringify(['Sales Ability']), jobRoles: JSON.stringify(['Agent', 'Senior Agent', 'Agency Manager']), workEnvironment: 'Field/Office', careerPath: JSON.stringify(['Agent → Senior → Manager']), prosAndCons: JSON.stringify({ pros: ['Commission-based earnings', 'Flexible'], cons: ['Target pressure', 'Customer acquisition'] }) },

  { title: 'Bank Manager', slug: 'bank-manager', description: 'Oversee bank branch operations and customer services', detailedInfo: 'Bank managers manage branch activities, customer relations, lending, and team performance.', category: 'Commerce', subCategory: 'Banking', averageSalary: '5-12 LPA', salaryRange: '4-25 LPA', demandLevel: 'High', futureDemand: 'Stable', requiredEducation: JSON.stringify(['B.Com', 'MBA Finance', 'JAIIB/CAIIB']), requiredSkills: JSON.stringify(['Banking Operations', 'Management', 'Customer Service']), personality: JSON.stringify(['Organized', 'Leadership']), interests: JSON.stringify(['Banking', 'Management']), aptitudes: JSON.stringify(['Management Skills']), jobRoles: JSON.stringify(['Officer', 'Assistant Manager', 'Manager']), workEnvironment: 'Bank Branch', careerPath: JSON.stringify(['Officer → Manager → Senior Manager']), prosAndCons: JSON.stringify({ pros: ['Stable career', 'Respect', 'Benefits'], cons: ['Target pressure', 'Regulatory compliance'] }) },

  { title: 'Credit Analyst', slug: 'credit-analyst', description: 'Assess creditworthiness of individuals and businesses', detailedInfo: 'Credit analysts evaluate loan applications, analyze financial data, and assess credit risk.', category: 'Commerce', subCategory: 'Finance', averageSalary: '4-9 LPA', salaryRange: '3-18 LPA', demandLevel: 'High', futureDemand: 'Stable', requiredEducation: JSON.stringify(['B.Com', 'MBA Finance']), requiredSkills: JSON.stringify(['Financial Analysis', 'Risk Assessment', 'Excel']), personality: JSON.stringify(['Analytical', 'Risk-aware']), interests: JSON.stringify(['Finance', 'Analysis']), aptitudes: JSON.stringify(['Analytical Skills']), jobRoles: JSON.stringify(['Junior Analyst', 'Credit Analyst', 'Senior Analyst']), workEnvironment: 'Office', careerPath: JSON.stringify(['Junior → Senior → Manager']), prosAndCons: JSON.stringify({ pros: ['Banking sector', 'Stable'], cons: ['Pressure of decisions'] }) },

  { title: 'Auditor', slug: 'auditor', description: 'Examine financial records for accuracy and compliance', detailedInfo: 'Auditors review financial statements, ensure compliance, and identify discrepancies.', category: 'Commerce', subCategory: 'Auditing', averageSalary: '4-10 LPA', salaryRange: '3-25 LPA', demandLevel: 'High', futureDemand: 'Stable', requiredEducation: JSON.stringify(['CA', 'B.Com', 'MBA']), requiredSkills: JSON.stringify(['Auditing', 'Accounting', 'Compliance', 'Analysis']), personality: JSON.stringify(['Meticulous', 'Ethical']), interests: JSON.stringify(['Accounting', 'Compliance']), aptitudes: JSON.stringify(['Attention to Detail']), jobRoles: JSON.stringify(['Junior Auditor', 'Auditor', 'Senior Auditor']), workEnvironment: 'Office/Client Site', careerPath: JSON.stringify(['Junior → Senior → Manager']), prosAndCons: JSON.stringify({ pros: ['Essential function', 'Good career'], cons: ['Repetitive', 'Travel'] }) },

  // Additional Creative & Media (10 more)
  { title: 'Animator', slug: 'animator', description: 'Create animated content for films, games, and media', detailedInfo: 'Animators bring characters and stories to life through 2D/3D animation techniques.', category: 'Creative', subCategory: 'Animation', averageSalary: '3-8 LPA', salaryRange: '2-20 LPA', demandLevel: 'Medium', futureDemand: 'Growing', requiredEducation: JSON.stringify(['Animation Degree', 'Portfolio']), requiredSkills: JSON.stringify(['Maya', 'Blender', '2D/3D Animation', 'Creativity']), personality: JSON.stringify(['Creative', 'Technical']), interests: JSON.stringify(['Animation', 'Art']), aptitudes: JSON.stringify(['Visual Creativity']), jobRoles: JSON.stringify(['Junior Animator', 'Animator', 'Lead Animator']), workEnvironment: 'Studio', careerPath: JSON.stringify(['Junior → Senior → Lead']), prosAndCons: JSON.stringify({ pros: ['Creative work', 'Growing industry'], cons: ['Deadline pressure', 'Competitive'] }) },

  { title: 'Film Director', slug: 'film-director', description: 'Direct and oversee film and video production', detailedInfo: 'Film directors bring scripts to life by directing actors, making creative decisions, and overseeing production.', category: 'Creative', subCategory: 'Film', averageSalary: '5-20 LPA', salaryRange: '3-Unlimited', demandLevel: 'Low', futureDemand: 'Stable', requiredEducation: JSON.stringify(['Film School', 'Portfolio']), requiredSkills: JSON.stringify(['Direction', 'Storytelling', 'Leadership', 'Vision']), personality: JSON.stringify(['Creative', 'Leader']), interests: JSON.stringify(['Cinema', 'Storytelling']), aptitudes: JSON.stringify(['Creative Vision']), jobRoles: JSON.stringify(['Assistant Director', 'Director', 'Filmmaker']), workEnvironment: 'Film Set', careerPath: JSON.stringify(['Assistant → Director → Filmmaker']), prosAndCons: JSON.stringify({ pros: ['Creative freedom', 'Unlimited potential'], cons: ['Highly competitive', 'Uncertain income'] }) },

  { title: 'Music Producer', slug: 'music-producer', description: 'Produce and create music tracks for various media', detailedInfo: 'Music producers compose, arrange, record, and mix music for films, albums, and commercials.', category: 'Creative', subCategory: 'Music', averageSalary: '3-10 LPA', salaryRange: '2-50 LPA', demandLevel: 'Low', futureDemand: 'Stable', requiredEducation: JSON.stringify(['Music Degree', 'Self-taught']), requiredSkills: JSON.stringify(['Music Production', 'DAW Software', 'Sound Design']), personality: JSON.stringify(['Creative', 'Technical']), interests: JSON.stringify(['Music', 'Production']), aptitudes: JSON.stringify(['Musical Talent']), jobRoles: JSON.stringify(['Producer', 'Sound Engineer', 'Composer']), workEnvironment: 'Studio', careerPath: JSON.stringify(['Assistant → Producer → Independent']), prosAndCons: JSON.stringify({ pros: ['Creative work', 'Passion-based'], cons: ['Irregular income', 'Competitive'] }) },

  { title: 'Radio Jockey (RJ)', slug: 'radio-jockey', description: 'Host radio shows and engage listeners with entertainment', detailedInfo: 'RJs host radio programs, play music, conduct interviews, and entertain audiences.', category: 'Media', subCategory: 'Radio', averageSalary: '3-8 LPA', salaryRange: '2-15 LPA', demandLevel: 'Low', futureDemand: 'Stable', requiredEducation: JSON.stringify(['Any Degree', 'Voice Training']), requiredSkills: JSON.stringify(['Communication', 'Voice Modulation', 'Entertainment', 'Quick Thinking']), personality: JSON.stringify(['Entertaining', 'Articulate']), interests: JSON.stringify(['Radio', 'Entertainment']), aptitudes: JSON.stringify(['Communication']), jobRoles: JSON.stringify(['RJ', 'Lead RJ', 'Program Head']), workEnvironment: 'Radio Station', careerPath: JSON.stringify(['RJ → Senior → Program Head']), prosAndCons: JSON.stringify({ pros: ['Fun job', 'Fame'], cons: ['Early morning shifts', 'Limited positions'] }) },

  { title: 'YouTuber/Content Creator', slug: 'youtuber-content-creator', description: 'Create video content for YouTube and social media platforms', detailedInfo: 'Content creators produce engaging videos, build audiences, and monetize through ads and sponsorships.', category: 'Creative', subCategory: 'Digital Content', averageSalary: '2-15 LPA', salaryRange: '0-Unlimited', demandLevel: 'High', futureDemand: 'Growing', requiredEducation: JSON.stringify(['Not Required', 'Any Background']), requiredSkills: JSON.stringify(['Content Creation', 'Video Editing', 'Marketing', 'Consistency']), personality: JSON.stringify(['Creative', 'Persistent']), interests: JSON.stringify(['Content', 'Social Media']), aptitudes: JSON.stringify(['Creativity']), jobRoles: JSON.stringify(['Creator', 'Influencer', 'Brand']), workEnvironment: 'Home/Studio', careerPath: JSON.stringify(['Starting → Growing → Established']), prosAndCons: JSON.stringify({ pros: ['Creative freedom', 'Work from home', 'Unlimited potential'], cons: ['Uncertain income', 'Algorithm dependent', 'Burnout risk'] }) },
]

module.exports = careers
