// 100+ Comprehensive Job Listings
const jobs = [
  {
    title: 'Software Developer',
    company: 'Digital Solutions',
    location: 'Hyderabad',
    type: 'Full-time',
    salary: '6-12 LPA',
    experience: '2-4 years',
    skills: JSON.stringify(["JavaScript","React","Node.js"]),
    requirements: JSON.stringify(["Relevant degree","2-4 years","Required skills"]),
    description: 'Exciting opportunity to work on challenging projects. Join our dynamic team.',
    applyLink: 'https://careers.example.com/job1',
    category: 'Technology',
    postedDate: new Date('2026-08-15')
  },
  {
    title: 'Software Developer',
    company: 'Smart Systems',
    location: 'Pune',
    type: 'Part-time',
    salary: '6-12 LPA',
    experience: '2-4 years',
    skills: JSON.stringify(["JavaScript","React","Node.js"]),
    requirements: JSON.stringify(["Relevant degree","2-4 years","Required skills"]),
    description: 'Flexible part-time opportunity with good compensation. Work-life balance.',
    applyLink: 'https://careers.example.com/job2',
    category: 'Technology',
    postedDate: new Date('2026-08-07')
  },
  {
    title: 'Software Developer',
    company: 'Digital Solutions',
    location: 'Remote',
    type: 'Full-time',
    salary: '6-12 LPA',
    experience: '2-4 years',
    skills: JSON.stringify(["JavaScript","React","Node.js"]),
    requirements: JSON.stringify(["Relevant degree","2-4 years","Required skills"]),
    description: 'Exciting opportunity to work on challenging projects. Join our dynamic team.',
    applyLink: 'https://careers.example.com/job3',
    category: 'Technology',
    postedDate: new Date('2026-08-10')
  },
  {
    title: 'Full Stack Developer',
    company: 'Tech Corp',
    location: 'Mumbai',
    type: 'Full-time',
    salary: '8-15 LPA',
    experience: '3-5 years',
    skills: JSON.stringify(["React","Node.js","MongoDB"]),
    requirements: JSON.stringify(["Relevant degree","3-5 years","Required skills"]),
    description: 'Exciting opportunity to work on challenging projects. Join our dynamic team.',
    applyLink: 'https://careers.example.com/job4',
    category: 'Technology',
    postedDate: new Date('2026-08-16')
  },
  {
    title: 'Full Stack Developer',
    company: 'Data Insights',
    location: 'Hyderabad',
    type: 'Part-time',
    salary: '8-15 LPA',
    experience: '3-5 years',
    skills: JSON.stringify(["React","Node.js","MongoDB"]),
    requirements: JSON.stringify(["Relevant degree","3-5 years","Required skills"]),
    description: 'Flexible part-time opportunity with good compensation. Work-life balance.',
    applyLink: 'https://careers.example.com/job5',
    category: 'Technology',
    postedDate: new Date('2026-08-18')
  },
  {
    title: 'Full Stack Developer',
    company: 'Innovation Ltd',
    location: 'Remote',
    type: 'Full-time',
    salary: '8-15 LPA',
    experience: '3-5 years',
    skills: JSON.stringify(["React","Node.js","MongoDB"]),
    requirements: JSON.stringify(["Relevant degree","3-5 years","Required skills"]),
    description: 'Exciting opportunity to work on challenging projects. Join our dynamic team.',
    applyLink: 'https://careers.example.com/job6',
    category: 'Technology',
    postedDate: new Date('2026-08-21')
  },
  {
    title: 'Backend Developer',
    company: 'Data Insights',
    location: 'Gurgaon',
    type: 'Full-time',
    salary: '7-14 LPA',
    experience: '2-5 years',
    skills: JSON.stringify(["Python","Django","PostgreSQL"]),
    requirements: JSON.stringify(["Relevant degree","2-5 years","Required skills"]),
    description: 'Exciting opportunity to work on challenging projects. Join our dynamic team.',
    applyLink: 'https://careers.example.com/job7',
    category: 'Technology',
    postedDate: new Date('2026-08-14')
  },
  {
    title: 'Backend Developer',
    company: 'Smart Systems',
    location: 'Pune',
    type: 'Part-time',
    salary: '7-14 LPA',
    experience: '2-5 years',
    skills: JSON.stringify(["Python","Django","PostgreSQL"]),
    requirements: JSON.stringify(["Relevant degree","2-5 years","Required skills"]),
    description: 'Flexible part-time opportunity with good compensation. Work-life balance.',
    applyLink: 'https://careers.example.com/job8',
    category: 'Technology',
    postedDate: new Date('2026-08-08')
  },
  {
    title: 'Backend Developer',
    company: 'Innovation Ltd',
    location: 'Delhi',
    type: 'Full-time',
    salary: '7-14 LPA',
    experience: '2-5 years',
    skills: JSON.stringify(["Python","Django","PostgreSQL"]),
    requirements: JSON.stringify(["Relevant degree","2-5 years","Required skills"]),
    description: 'Exciting opportunity to work on challenging projects. Join our dynamic team.',
    applyLink: 'https://careers.example.com/job9',
    category: 'Technology',
    postedDate: new Date('2026-08-10')
  },
  {
    title: 'Frontend Developer',
    company: 'Data Insights',
    location: 'Gurgaon',
    type: 'Full-time',
    salary: '6-12 LPA',
    experience: '2-4 years',
    skills: JSON.stringify(["React","TypeScript","CSS"]),
    requirements: JSON.stringify(["Relevant degree","2-4 years","Required skills"]),
    description: 'Exciting opportunity to work on challenging projects. Join our dynamic team.',
    applyLink: 'https://careers.example.com/job10',
    category: 'Technology',
    postedDate: new Date('2026-08-27')
  },
  {
    title: 'Frontend Developer',
    company: 'Data Insights',
    location: 'Noida',
    type: 'Part-time',
    salary: '6-12 LPA',
    experience: '2-4 years',
    skills: JSON.stringify(["React","TypeScript","CSS"]),
    requirements: JSON.stringify(["Relevant degree","2-4 years","Required skills"]),
    description: 'Flexible part-time opportunity with good compensation. Work-life balance.',
    applyLink: 'https://careers.example.com/job11',
    category: 'Technology',
    postedDate: new Date('2026-08-07')
  },
  {
    title: 'Frontend Developer',
    company: 'Future Tech',
    location: 'Remote',
    type: 'Full-time',
    salary: '6-12 LPA',
    experience: '2-4 years',
    skills: JSON.stringify(["React","TypeScript","CSS"]),
    requirements: JSON.stringify(["Relevant degree","2-4 years","Required skills"]),
    description: 'Exciting opportunity to work on challenging projects. Join our dynamic team.',
    applyLink: 'https://careers.example.com/job12',
    category: 'Technology',
    postedDate: new Date('2026-08-03')
  },
  {
    title: 'Mobile Developer',
    company: 'Cloud First',
    location: 'Gurgaon',
    type: 'Full-time',
    salary: '7-14 LPA',
    experience: '2-5 years',
    skills: JSON.stringify(["React Native","Flutter","Firebase"]),
    requirements: JSON.stringify(["Relevant degree","2-5 years","Required skills"]),
    description: 'Exciting opportunity to work on challenging projects. Join our dynamic team.',
    applyLink: 'https://careers.example.com/job13',
    category: 'Technology',
    postedDate: new Date('2026-08-03')
  },
  {
    title: 'Mobile Developer',
    company: 'AI Labs',
    location: 'Mumbai',
    type: 'Part-time',
    salary: '7-14 LPA',
    experience: '2-5 years',
    skills: JSON.stringify(["React Native","Flutter","Firebase"]),
    requirements: JSON.stringify(["Relevant degree","2-5 years","Required skills"]),
    description: 'Flexible part-time opportunity with good compensation. Work-life balance.',
    applyLink: 'https://careers.example.com/job14',
    category: 'Technology',
    postedDate: new Date('2026-08-08')
  },
  {
    title: 'Mobile Developer',
    company: 'Smart Systems',
    location: 'Delhi',
    type: 'Full-time',
    salary: '7-14 LPA',
    experience: '2-5 years',
    skills: JSON.stringify(["React Native","Flutter","Firebase"]),
    requirements: JSON.stringify(["Relevant degree","2-5 years","Required skills"]),
    description: 'Exciting opportunity to work on challenging projects. Join our dynamic team.',
    applyLink: 'https://careers.example.com/job15',
    category: 'Technology',
    postedDate: new Date('2026-08-10')
  },
  {
    title: 'DevOps Engineer',
    company: 'Innovation Ltd',
    location: 'Remote',
    type: 'Full-time',
    salary: '10-18 LPA',
    experience: '3-6 years',
    skills: JSON.stringify(["Docker","Kubernetes","AWS"]),
    requirements: JSON.stringify(["Relevant degree","3-6 years","Required skills"]),
    description: 'Exciting opportunity to work on challenging projects. Join our dynamic team.',
    applyLink: 'https://careers.example.com/job16',
    category: 'Technology',
    postedDate: new Date('2026-08-28')
  },
  {
    title: 'DevOps Engineer',
    company: 'Innovation Ltd',
    location: 'Gurgaon',
    type: 'Part-time',
    salary: '10-18 LPA',
    experience: '3-6 years',
    skills: JSON.stringify(["Docker","Kubernetes","AWS"]),
    requirements: JSON.stringify(["Relevant degree","3-6 years","Required skills"]),
    description: 'Flexible part-time opportunity with good compensation. Work-life balance.',
    applyLink: 'https://careers.example.com/job17',
    category: 'Technology',
    postedDate: new Date('2026-08-13')
  },
  {
    title: 'DevOps Engineer',
    company: 'Data Insights',
    location: 'Remote',
    type: 'Full-time',
    salary: '10-18 LPA',
    experience: '3-6 years',
    skills: JSON.stringify(["Docker","Kubernetes","AWS"]),
    requirements: JSON.stringify(["Relevant degree","3-6 years","Required skills"]),
    description: 'Exciting opportunity to work on challenging projects. Join our dynamic team.',
    applyLink: 'https://careers.example.com/job18',
    category: 'Technology',
    postedDate: new Date('2026-08-17')
  },
  {
    title: 'Data Scientist',
    company: 'Innovation Ltd',
    location: 'Delhi',
    type: 'Full-time',
    salary: '12-22 LPA',
    experience: '3-6 years',
    skills: JSON.stringify(["Python","ML","TensorFlow"]),
    requirements: JSON.stringify(["Relevant degree","3-6 years","Required skills"]),
    description: 'Exciting opportunity to work on challenging projects. Join our dynamic team.',
    applyLink: 'https://careers.example.com/job19',
    category: 'Technology',
    postedDate: new Date('2026-08-17')
  },
  {
    title: 'Data Scientist',
    company: 'Cloud First',
    location: 'Hyderabad',
    type: 'Part-time',
    salary: '12-22 LPA',
    experience: '3-6 years',
    skills: JSON.stringify(["Python","ML","TensorFlow"]),
    requirements: JSON.stringify(["Relevant degree","3-6 years","Required skills"]),
    description: 'Flexible part-time opportunity with good compensation. Work-life balance.',
    applyLink: 'https://careers.example.com/job20',
    category: 'Technology',
    postedDate: new Date('2026-08-24')
  },
  {
    title: 'Data Scientist',
    company: 'Future Tech',
    location: 'Mumbai',
    type: 'Full-time',
    salary: '12-22 LPA',
    experience: '3-6 years',
    skills: JSON.stringify(["Python","ML","TensorFlow"]),
    requirements: JSON.stringify(["Relevant degree","3-6 years","Required skills"]),
    description: 'Exciting opportunity to work on challenging projects. Join our dynamic team.',
    applyLink: 'https://careers.example.com/job21',
    category: 'Technology',
    postedDate: new Date('2026-08-12')
  },
  {
    title: 'QA Engineer',
    company: 'Digital Solutions',
    location: 'Noida',
    type: 'Full-time',
    salary: '5-10 LPA',
    experience: '2-4 years',
    skills: JSON.stringify(["Selenium","Testing","Automation"]),
    requirements: JSON.stringify(["Relevant degree","2-4 years","Required skills"]),
    description: 'Exciting opportunity to work on challenging projects. Join our dynamic team.',
    applyLink: 'https://careers.example.com/job22',
    category: 'Technology',
    postedDate: new Date('2026-08-16')
  },
  {
    title: 'QA Engineer',
    company: 'Data Insights',
    location: 'Gurgaon',
    type: 'Part-time',
    salary: '5-10 LPA',
    experience: '2-4 years',
    skills: JSON.stringify(["Selenium","Testing","Automation"]),
    requirements: JSON.stringify(["Relevant degree","2-4 years","Required skills"]),
    description: 'Flexible part-time opportunity with good compensation. Work-life balance.',
    applyLink: 'https://careers.example.com/job23',
    category: 'Technology',
    postedDate: new Date('2026-08-17')
  },
  {
    title: 'QA Engineer',
    company: 'Future Tech',
    location: 'Pune',
    type: 'Full-time',
    salary: '5-10 LPA',
    experience: '2-4 years',
    skills: JSON.stringify(["Selenium","Testing","Automation"]),
    requirements: JSON.stringify(["Relevant degree","2-4 years","Required skills"]),
    description: 'Exciting opportunity to work on challenging projects. Join our dynamic team.',
    applyLink: 'https://careers.example.com/job24',
    category: 'Technology',
    postedDate: new Date('2026-08-30')
  },
  {
    title: 'Cloud Architect',
    company: 'Smart Systems',
    location: 'Pune',
    type: 'Full-time',
    salary: '15-25 LPA',
    experience: '5-8 years',
    skills: JSON.stringify(["AWS","Azure","Architecture"]),
    requirements: JSON.stringify(["Relevant degree","5-8 years","Required skills"]),
    description: 'Exciting opportunity to work on challenging projects. Join our dynamic team.',
    applyLink: 'https://careers.example.com/job25',
    category: 'Technology',
    postedDate: new Date('2026-08-28')
  },
  {
    title: 'Cloud Architect',
    company: 'Tech Corp',
    location: 'Mumbai',
    type: 'Part-time',
    salary: '15-25 LPA',
    experience: '5-8 years',
    skills: JSON.stringify(["AWS","Azure","Architecture"]),
    requirements: JSON.stringify(["Relevant degree","5-8 years","Required skills"]),
    description: 'Flexible part-time opportunity with good compensation. Work-life balance.',
    applyLink: 'https://careers.example.com/job26',
    category: 'Technology',
    postedDate: new Date('2026-08-02')
  },
  {
    title: 'Cloud Architect',
    company: 'Cloud First',
    location: 'Noida',
    type: 'Full-time',
    salary: '15-25 LPA',
    experience: '5-8 years',
    skills: JSON.stringify(["AWS","Azure","Architecture"]),
    requirements: JSON.stringify(["Relevant degree","5-8 years","Required skills"]),
    description: 'Exciting opportunity to work on challenging projects. Join our dynamic team.',
    applyLink: 'https://careers.example.com/job27',
    category: 'Technology',
    postedDate: new Date('2026-08-27')
  },
  {
    title: 'Cybersecurity Analyst',
    company: 'Tech Corp',
    location: 'Pune',
    type: 'Full-time',
    salary: '10-18 LPA',
    experience: '3-6 years',
    skills: JSON.stringify(["Security","SIEM","Pentesting"]),
    requirements: JSON.stringify(["Relevant degree","3-6 years","Required skills"]),
    description: 'Exciting opportunity to work on challenging projects. Join our dynamic team.',
    applyLink: 'https://careers.example.com/job28',
    category: 'Technology',
    postedDate: new Date('2026-08-21')
  },
  {
    title: 'Cybersecurity Analyst',
    company: 'Future Tech',
    location: 'Noida',
    type: 'Part-time',
    salary: '10-18 LPA',
    experience: '3-6 years',
    skills: JSON.stringify(["Security","SIEM","Pentesting"]),
    requirements: JSON.stringify(["Relevant degree","3-6 years","Required skills"]),
    description: 'Flexible part-time opportunity with good compensation. Work-life balance.',
    applyLink: 'https://careers.example.com/job29',
    category: 'Technology',
    postedDate: new Date('2026-08-28')
  },
  {
    title: 'Cybersecurity Analyst',
    company: 'Data Insights',
    location: 'Noida',
    type: 'Full-time',
    salary: '10-18 LPA',
    experience: '3-6 years',
    skills: JSON.stringify(["Security","SIEM","Pentesting"]),
    requirements: JSON.stringify(["Relevant degree","3-6 years","Required skills"]),
    description: 'Exciting opportunity to work on challenging projects. Join our dynamic team.',
    applyLink: 'https://careers.example.com/job30',
    category: 'Technology',
    postedDate: new Date('2026-08-19')
  },
  {
    title: 'AI/ML Engineer',
    company: 'Future Tech',
    location: 'Mumbai',
    type: 'Full-time',
    salary: '15-28 LPA',
    experience: '4-7 years',
    skills: JSON.stringify(["Deep Learning","PyTorch","NLP"]),
    requirements: JSON.stringify(["Relevant degree","4-7 years","Required skills"]),
    description: 'Exciting opportunity to work on challenging projects. Join our dynamic team.',
    applyLink: 'https://careers.example.com/job31',
    category: 'Technology',
    postedDate: new Date('2026-08-08')
  },
  {
    title: 'AI/ML Engineer',
    company: 'AI Labs',
    location: 'Bangalore',
    type: 'Part-time',
    salary: '15-28 LPA',
    experience: '4-7 years',
    skills: JSON.stringify(["Deep Learning","PyTorch","NLP"]),
    requirements: JSON.stringify(["Relevant degree","4-7 years","Required skills"]),
    description: 'Flexible part-time opportunity with good compensation. Work-life balance.',
    applyLink: 'https://careers.example.com/job32',
    category: 'Technology',
    postedDate: new Date('2026-08-10')
  },
  {
    title: 'AI/ML Engineer',
    company: 'Smart Systems',
    location: 'Hyderabad',
    type: 'Full-time',
    salary: '15-28 LPA',
    experience: '4-7 years',
    skills: JSON.stringify(["Deep Learning","PyTorch","NLP"]),
    requirements: JSON.stringify(["Relevant degree","4-7 years","Required skills"]),
    description: 'Exciting opportunity to work on challenging projects. Join our dynamic team.',
    applyLink: 'https://careers.example.com/job33',
    category: 'Technology',
    postedDate: new Date('2026-08-20')
  },
  {
    title: 'Database Administrator',
    company: 'Smart Systems',
    location: 'Mumbai',
    type: 'Full-time',
    salary: '7-14 LPA',
    experience: '3-6 years',
    skills: JSON.stringify(["SQL","Oracle","MySQL"]),
    requirements: JSON.stringify(["Relevant degree","3-6 years","Required skills"]),
    description: 'Exciting opportunity to work on challenging projects. Join our dynamic team.',
    applyLink: 'https://careers.example.com/job34',
    category: 'Technology',
    postedDate: new Date('2026-08-04')
  },
  {
    title: 'Database Administrator',
    company: 'AI Labs',
    location: 'Mumbai',
    type: 'Part-time',
    salary: '7-14 LPA',
    experience: '3-6 years',
    skills: JSON.stringify(["SQL","Oracle","MySQL"]),
    requirements: JSON.stringify(["Relevant degree","3-6 years","Required skills"]),
    description: 'Flexible part-time opportunity with good compensation. Work-life balance.',
    applyLink: 'https://careers.example.com/job35',
    category: 'Technology',
    postedDate: new Date('2026-08-13')
  },
  {
    title: 'Database Administrator',
    company: 'Smart Systems',
    location: 'Pune',
    type: 'Full-time',
    salary: '7-14 LPA',
    experience: '3-6 years',
    skills: JSON.stringify(["SQL","Oracle","MySQL"]),
    requirements: JSON.stringify(["Relevant degree","3-6 years","Required skills"]),
    description: 'Exciting opportunity to work on challenging projects. Join our dynamic team.',
    applyLink: 'https://careers.example.com/job36',
    category: 'Technology',
    postedDate: new Date('2026-08-17')
  },
  {
    title: 'UI/UX Designer',
    company: 'AI Labs',
    location: 'Ahmedabad',
    type: 'Full-time',
    salary: '6-12 LPA',
    experience: '2-5 years',
    skills: JSON.stringify(["Figma","Design","Prototyping"]),
    requirements: JSON.stringify(["Relevant degree","2-5 years","Required skills"]),
    description: 'Exciting opportunity to work on challenging projects. Join our dynamic team.',
    applyLink: 'https://careers.example.com/job37',
    category: 'Technology',
    postedDate: new Date('2026-08-07')
  },
  {
    title: 'UI/UX Designer',
    company: 'Data Insights',
    location: 'Hyderabad',
    type: 'Part-time',
    salary: '6-12 LPA',
    experience: '2-5 years',
    skills: JSON.stringify(["Figma","Design","Prototyping"]),
    requirements: JSON.stringify(["Relevant degree","2-5 years","Required skills"]),
    description: 'Flexible part-time opportunity with good compensation. Work-life balance.',
    applyLink: 'https://careers.example.com/job38',
    category: 'Technology',
    postedDate: new Date('2026-08-14')
  },
  {
    title: 'UI/UX Designer',
    company: 'Tech Corp',
    location: 'Ahmedabad',
    type: 'Full-time',
    salary: '6-12 LPA',
    experience: '2-5 years',
    skills: JSON.stringify(["Figma","Design","Prototyping"]),
    requirements: JSON.stringify(["Relevant degree","2-5 years","Required skills"]),
    description: 'Exciting opportunity to work on challenging projects. Join our dynamic team.',
    applyLink: 'https://careers.example.com/job39',
    category: 'Technology',
    postedDate: new Date('2026-08-10')
  },
  {
    title: 'Product Manager',
    company: 'Tech Corp',
    location: 'Delhi',
    type: 'Full-time',
    salary: '15-25 LPA',
    experience: '4-8 years',
    skills: JSON.stringify(["Product Strategy","Agile","Analytics"]),
    requirements: JSON.stringify(["Relevant degree","4-8 years","Required skills"]),
    description: 'Exciting opportunity to work on challenging projects. Join our dynamic team.',
    applyLink: 'https://careers.example.com/job40',
    category: 'Technology',
    postedDate: new Date('2026-08-06')
  },
  {
    title: 'Product Manager',
    company: 'Future Tech',
    location: 'Kolkata',
    type: 'Part-time',
    salary: '15-25 LPA',
    experience: '4-8 years',
    skills: JSON.stringify(["Product Strategy","Agile","Analytics"]),
    requirements: JSON.stringify(["Relevant degree","4-8 years","Required skills"]),
    description: 'Flexible part-time opportunity with good compensation. Work-life balance.',
    applyLink: 'https://careers.example.com/job41',
    category: 'Technology',
    postedDate: new Date('2026-08-25')
  },
  {
    title: 'Product Manager',
    company: 'AI Labs',
    location: 'Gurgaon',
    type: 'Full-time',
    salary: '15-25 LPA',
    experience: '4-8 years',
    skills: JSON.stringify(["Product Strategy","Agile","Analytics"]),
    requirements: JSON.stringify(["Relevant degree","4-8 years","Required skills"]),
    description: 'Exciting opportunity to work on challenging projects. Join our dynamic team.',
    applyLink: 'https://careers.example.com/job42',
    category: 'Technology',
    postedDate: new Date('2026-08-02')
  },
  {
    title: 'Technical Writer',
    company: 'Digital Solutions',
    location: 'Chennai',
    type: 'Full-time',
    salary: '4-8 LPA',
    experience: '1-3 years',
    skills: JSON.stringify(["Documentation","Technical Writing"]),
    requirements: JSON.stringify(["Relevant degree","1-3 years","Required skills"]),
    description: 'Exciting opportunity to work on challenging projects. Join our dynamic team.',
    applyLink: 'https://careers.example.com/job43',
    category: 'Technology',
    postedDate: new Date('2026-08-25')
  },
  {
    title: 'Technical Writer',
    company: 'Future Tech',
    location: 'Noida',
    type: 'Part-time',
    salary: '4-8 LPA',
    experience: '1-3 years',
    skills: JSON.stringify(["Documentation","Technical Writing"]),
    requirements: JSON.stringify(["Relevant degree","1-3 years","Required skills"]),
    description: 'Flexible part-time opportunity with good compensation. Work-life balance.',
    applyLink: 'https://careers.example.com/job44',
    category: 'Technology',
    postedDate: new Date('2026-08-05')
  },
  {
    title: 'Technical Writer',
    company: 'Data Insights',
    location: 'Mumbai',
    type: 'Full-time',
    salary: '4-8 LPA',
    experience: '1-3 years',
    skills: JSON.stringify(["Documentation","Technical Writing"]),
    requirements: JSON.stringify(["Relevant degree","1-3 years","Required skills"]),
    description: 'Exciting opportunity to work on challenging projects. Join our dynamic team.',
    applyLink: 'https://careers.example.com/job45',
    category: 'Technology',
    postedDate: new Date('2026-08-26')
  },
  {
    title: 'Business Analyst',
    company: 'AI Labs',
    location: 'Noida',
    type: 'Full-time',
    salary: '6-12 LPA',
    experience: '2-5 years',
    skills: JSON.stringify(["Analysis","SQL","Excel"]),
    requirements: JSON.stringify(["Relevant degree","2-5 years","Required skills"]),
    description: 'Exciting opportunity to work on challenging projects. Join our dynamic team.',
    applyLink: 'https://careers.example.com/job46',
    category: 'Business',
    postedDate: new Date('2026-08-08')
  },
  {
    title: 'Business Analyst',
    company: 'Tech Corp',
    location: 'Kolkata',
    type: 'Part-time',
    salary: '6-12 LPA',
    experience: '2-5 years',
    skills: JSON.stringify(["Analysis","SQL","Excel"]),
    requirements: JSON.stringify(["Relevant degree","2-5 years","Required skills"]),
    description: 'Flexible part-time opportunity with good compensation. Work-life balance.',
    applyLink: 'https://careers.example.com/job47',
    category: 'Business',
    postedDate: new Date('2026-08-10')
  },
  {
    title: 'Business Analyst',
    company: 'Data Insights',
    location: 'Bangalore',
    type: 'Full-time',
    salary: '6-12 LPA',
    experience: '2-5 years',
    skills: JSON.stringify(["Analysis","SQL","Excel"]),
    requirements: JSON.stringify(["Relevant degree","2-5 years","Required skills"]),
    description: 'Exciting opportunity to work on challenging projects. Join our dynamic team.',
    applyLink: 'https://careers.example.com/job48',
    category: 'Business',
    postedDate: new Date('2026-08-16')
  },
  {
    title: 'Marketing Manager',
    company: 'Smart Systems',
    location: 'Chennai',
    type: 'Full-time',
    salary: '8-15 LPA',
    experience: '3-6 years',
    skills: JSON.stringify(["Marketing","Strategy","Digital"]),
    requirements: JSON.stringify(["Relevant degree","3-6 years","Required skills"]),
    description: 'Exciting opportunity to work on challenging projects. Join our dynamic team.',
    applyLink: 'https://careers.example.com/job49',
    category: 'Business',
    postedDate: new Date('2026-08-04')
  },
  {
    title: 'Marketing Manager',
    company: 'Digital Solutions',
    location: 'Hyderabad',
    type: 'Part-time',
    salary: '8-15 LPA',
    experience: '3-6 years',
    skills: JSON.stringify(["Marketing","Strategy","Digital"]),
    requirements: JSON.stringify(["Relevant degree","3-6 years","Required skills"]),
    description: 'Flexible part-time opportunity with good compensation. Work-life balance.',
    applyLink: 'https://careers.example.com/job50',
    category: 'Business',
    postedDate: new Date('2026-08-29')
  },
  {
    title: 'Marketing Manager',
    company: 'Data Insights',
    location: 'Chennai',
    type: 'Full-time',
    salary: '8-15 LPA',
    experience: '3-6 years',
    skills: JSON.stringify(["Marketing","Strategy","Digital"]),
    requirements: JSON.stringify(["Relevant degree","3-6 years","Required skills"]),
    description: 'Exciting opportunity to work on challenging projects. Join our dynamic team.',
    applyLink: 'https://careers.example.com/job51',
    category: 'Business',
    postedDate: new Date('2026-08-14')
  },
  {
    title: 'Sales Manager',
    company: 'AI Labs',
    location: 'Chennai',
    type: 'Full-time',
    salary: '8-16 LPA',
    experience: '4-7 years',
    skills: JSON.stringify(["Sales","Leadership","CRM"]),
    requirements: JSON.stringify(["Relevant degree","4-7 years","Required skills"]),
    description: 'Exciting opportunity to work on challenging projects. Join our dynamic team.',
    applyLink: 'https://careers.example.com/job52',
    category: 'Business',
    postedDate: new Date('2026-08-22')
  },
  {
    title: 'Sales Manager',
    company: 'AI Labs',
    location: 'Chennai',
    type: 'Part-time',
    salary: '8-16 LPA',
    experience: '4-7 years',
    skills: JSON.stringify(["Sales","Leadership","CRM"]),
    requirements: JSON.stringify(["Relevant degree","4-7 years","Required skills"]),
    description: 'Flexible part-time opportunity with good compensation. Work-life balance.',
    applyLink: 'https://careers.example.com/job53',
    category: 'Business',
    postedDate: new Date('2026-08-24')
  },
  {
    title: 'Sales Manager',
    company: 'Tech Corp',
    location: 'Chennai',
    type: 'Full-time',
    salary: '8-16 LPA',
    experience: '4-7 years',
    skills: JSON.stringify(["Sales","Leadership","CRM"]),
    requirements: JSON.stringify(["Relevant degree","4-7 years","Required skills"]),
    description: 'Exciting opportunity to work on challenging projects. Join our dynamic team.',
    applyLink: 'https://careers.example.com/job54',
    category: 'Business',
    postedDate: new Date('2026-08-30')
  },
  {
    title: 'HR Manager',
    company: 'Digital Solutions',
    location: 'Hyderabad',
    type: 'Full-time',
    salary: '7-14 LPA',
    experience: '4-7 years',
    skills: JSON.stringify(["Recruitment","HR","Employee Relations"]),
    requirements: JSON.stringify(["Relevant degree","4-7 years","Required skills"]),
    description: 'Exciting opportunity to work on challenging projects. Join our dynamic team.',
    applyLink: 'https://careers.example.com/job55',
    category: 'Business',
    postedDate: new Date('2026-08-24')
  },
  {
    title: 'HR Manager',
    company: 'Data Insights',
    location: 'Delhi',
    type: 'Part-time',
    salary: '7-14 LPA',
    experience: '4-7 years',
    skills: JSON.stringify(["Recruitment","HR","Employee Relations"]),
    requirements: JSON.stringify(["Relevant degree","4-7 years","Required skills"]),
    description: 'Flexible part-time opportunity with good compensation. Work-life balance.',
    applyLink: 'https://careers.example.com/job56',
    category: 'Business',
    postedDate: new Date('2026-08-28')
  },
  {
    title: 'HR Manager',
    company: 'Digital Solutions',
    location: 'Remote',
    type: 'Full-time',
    salary: '7-14 LPA',
    experience: '4-7 years',
    skills: JSON.stringify(["Recruitment","HR","Employee Relations"]),
    requirements: JSON.stringify(["Relevant degree","4-7 years","Required skills"]),
    description: 'Exciting opportunity to work on challenging projects. Join our dynamic team.',
    applyLink: 'https://careers.example.com/job57',
    category: 'Business',
    postedDate: new Date('2026-08-06')
  },
  {
    title: 'Digital Marketing Specialist',
    company: 'Tech Corp',
    location: 'Bangalore',
    type: 'Full-time',
    salary: '4-10 LPA',
    experience: '2-4 years',
    skills: JSON.stringify(["SEO","Social Media","Google Ads"]),
    requirements: JSON.stringify(["Relevant degree","2-4 years","Required skills"]),
    description: 'Exciting opportunity to work on challenging projects. Join our dynamic team.',
    applyLink: 'https://careers.example.com/job58',
    category: 'Business',
    postedDate: new Date('2026-08-28')
  },
  {
    title: 'Digital Marketing Specialist',
    company: 'Data Insights',
    location: 'Remote',
    type: 'Part-time',
    salary: '4-10 LPA',
    experience: '2-4 years',
    skills: JSON.stringify(["SEO","Social Media","Google Ads"]),
    requirements: JSON.stringify(["Relevant degree","2-4 years","Required skills"]),
    description: 'Flexible part-time opportunity with good compensation. Work-life balance.',
    applyLink: 'https://careers.example.com/job59',
    category: 'Business',
    postedDate: new Date('2026-08-12')
  },
  {
    title: 'Digital Marketing Specialist',
    company: 'Innovation Ltd',
    location: 'Hyderabad',
    type: 'Full-time',
    salary: '4-10 LPA',
    experience: '2-4 years',
    skills: JSON.stringify(["SEO","Social Media","Google Ads"]),
    requirements: JSON.stringify(["Relevant degree","2-4 years","Required skills"]),
    description: 'Exciting opportunity to work on challenging projects. Join our dynamic team.',
    applyLink: 'https://careers.example.com/job60',
    category: 'Business',
    postedDate: new Date('2026-08-13')
  },
  {
    title: 'Operations Manager',
    company: 'Cloud First',
    location: 'Bangalore',
    type: 'Full-time',
    salary: '8-15 LPA',
    experience: '4-7 years',
    skills: JSON.stringify(["Operations","Supply Chain","Management"]),
    requirements: JSON.stringify(["Relevant degree","4-7 years","Required skills"]),
    description: 'Exciting opportunity to work on challenging projects. Join our dynamic team.',
    applyLink: 'https://careers.example.com/job61',
    category: 'Business',
    postedDate: new Date('2026-08-15')
  },
  {
    title: 'Operations Manager',
    company: 'Data Insights',
    location: 'Remote',
    type: 'Part-time',
    salary: '8-15 LPA',
    experience: '4-7 years',
    skills: JSON.stringify(["Operations","Supply Chain","Management"]),
    requirements: JSON.stringify(["Relevant degree","4-7 years","Required skills"]),
    description: 'Flexible part-time opportunity with good compensation. Work-life balance.',
    applyLink: 'https://careers.example.com/job62',
    category: 'Business',
    postedDate: new Date('2026-08-14')
  },
  {
    title: 'Operations Manager',
    company: 'Digital Solutions',
    location: 'Gurgaon',
    type: 'Full-time',
    salary: '8-15 LPA',
    experience: '4-7 years',
    skills: JSON.stringify(["Operations","Supply Chain","Management"]),
    requirements: JSON.stringify(["Relevant degree","4-7 years","Required skills"]),
    description: 'Exciting opportunity to work on challenging projects. Join our dynamic team.',
    applyLink: 'https://careers.example.com/job63',
    category: 'Business',
    postedDate: new Date('2026-08-06')
  },
  {
    title: 'Business Development Executive',
    company: 'Cloud First',
    location: 'Pune',
    type: 'Full-time',
    salary: '4-9 LPA',
    experience: '1-4 years',
    skills: JSON.stringify(["Sales","Communication","Negotiation"]),
    requirements: JSON.stringify(["Relevant degree","1-4 years","Required skills"]),
    description: 'Exciting opportunity to work on challenging projects. Join our dynamic team.',
    applyLink: 'https://careers.example.com/job64',
    category: 'Business',
    postedDate: new Date('2026-08-06')
  },
  {
    title: 'Business Development Executive',
    company: 'AI Labs',
    location: 'Kolkata',
    type: 'Part-time',
    salary: '4-9 LPA',
    experience: '1-4 years',
    skills: JSON.stringify(["Sales","Communication","Negotiation"]),
    requirements: JSON.stringify(["Relevant degree","1-4 years","Required skills"]),
    description: 'Flexible part-time opportunity with good compensation. Work-life balance.',
    applyLink: 'https://careers.example.com/job65',
    category: 'Business',
    postedDate: new Date('2026-08-11')
  },
  {
    title: 'Business Development Executive',
    company: 'Digital Solutions',
    location: 'Delhi',
    type: 'Full-time',
    salary: '4-9 LPA',
    experience: '1-4 years',
    skills: JSON.stringify(["Sales","Communication","Negotiation"]),
    requirements: JSON.stringify(["Relevant degree","1-4 years","Required skills"]),
    description: 'Exciting opportunity to work on challenging projects. Join our dynamic team.',
    applyLink: 'https://careers.example.com/job66',
    category: 'Business',
    postedDate: new Date('2026-08-08')
  },
  {
    title: 'Project Manager',
    company: 'Data Insights',
    location: 'Noida',
    type: 'Full-time',
    salary: '10-18 LPA',
    experience: '5-8 years',
    skills: JSON.stringify(["Project Management","Agile","Leadership"]),
    requirements: JSON.stringify(["Relevant degree","5-8 years","Required skills"]),
    description: 'Exciting opportunity to work on challenging projects. Join our dynamic team.',
    applyLink: 'https://careers.example.com/job67',
    category: 'Business',
    postedDate: new Date('2026-08-24')
  },
  {
    title: 'Project Manager',
    company: 'Cloud First',
    location: 'Hyderabad',
    type: 'Part-time',
    salary: '10-18 LPA',
    experience: '5-8 years',
    skills: JSON.stringify(["Project Management","Agile","Leadership"]),
    requirements: JSON.stringify(["Relevant degree","5-8 years","Required skills"]),
    description: 'Flexible part-time opportunity with good compensation. Work-life balance.',
    applyLink: 'https://careers.example.com/job68',
    category: 'Business',
    postedDate: new Date('2026-08-07')
  },
  {
    title: 'Project Manager',
    company: 'Tech Corp',
    location: 'Remote',
    type: 'Full-time',
    salary: '10-18 LPA',
    experience: '5-8 years',
    skills: JSON.stringify(["Project Management","Agile","Leadership"]),
    requirements: JSON.stringify(["Relevant degree","5-8 years","Required skills"]),
    description: 'Exciting opportunity to work on challenging projects. Join our dynamic team.',
    applyLink: 'https://careers.example.com/job69',
    category: 'Business',
    postedDate: new Date('2026-08-16')
  },
  {
    title: 'Financial Analyst',
    company: 'Tech Corp',
    location: 'Bangalore',
    type: 'Full-time',
    salary: '6-12 LPA',
    experience: '2-5 years',
    skills: JSON.stringify(["Finance","Excel","Modeling"]),
    requirements: JSON.stringify(["Relevant degree","2-5 years","Required skills"]),
    description: 'Exciting opportunity to work on challenging projects. Join our dynamic team.',
    applyLink: 'https://careers.example.com/job70',
    category: 'Business',
    postedDate: new Date('2026-08-23')
  },
  {
    title: 'Financial Analyst',
    company: 'Digital Solutions',
    location: 'Kolkata',
    type: 'Part-time',
    salary: '6-12 LPA',
    experience: '2-5 years',
    skills: JSON.stringify(["Finance","Excel","Modeling"]),
    requirements: JSON.stringify(["Relevant degree","2-5 years","Required skills"]),
    description: 'Flexible part-time opportunity with good compensation. Work-life balance.',
    applyLink: 'https://careers.example.com/job71',
    category: 'Business',
    postedDate: new Date('2026-08-11')
  },
  {
    title: 'Financial Analyst',
    company: 'Innovation Ltd',
    location: 'Chennai',
    type: 'Full-time',
    salary: '6-12 LPA',
    experience: '2-5 years',
    skills: JSON.stringify(["Finance","Excel","Modeling"]),
    requirements: JSON.stringify(["Relevant degree","2-5 years","Required skills"]),
    description: 'Exciting opportunity to work on challenging projects. Join our dynamic team.',
    applyLink: 'https://careers.example.com/job72',
    category: 'Business',
    postedDate: new Date('2026-08-19')
  },
  {
    title: 'Content Marketing Manager',
    company: 'Data Insights',
    location: 'Chennai',
    type: 'Full-time',
    salary: '5-10 LPA',
    experience: '2-5 years',
    skills: JSON.stringify(["Content","Writing","Strategy"]),
    requirements: JSON.stringify(["Relevant degree","2-5 years","Required skills"]),
    description: 'Exciting opportunity to work on challenging projects. Join our dynamic team.',
    applyLink: 'https://careers.example.com/job73',
    category: 'Business',
    postedDate: new Date('2026-08-26')
  },
  {
    title: 'Content Marketing Manager',
    company: 'Digital Solutions',
    location: 'Pune',
    type: 'Part-time',
    salary: '5-10 LPA',
    experience: '2-5 years',
    skills: JSON.stringify(["Content","Writing","Strategy"]),
    requirements: JSON.stringify(["Relevant degree","2-5 years","Required skills"]),
    description: 'Flexible part-time opportunity with good compensation. Work-life balance.',
    applyLink: 'https://careers.example.com/job74',
    category: 'Business',
    postedDate: new Date('2026-08-26')
  },
  {
    title: 'Content Marketing Manager',
    company: 'AI Labs',
    location: 'Noida',
    type: 'Full-time',
    salary: '5-10 LPA',
    experience: '2-5 years',
    skills: JSON.stringify(["Content","Writing","Strategy"]),
    requirements: JSON.stringify(["Relevant degree","2-5 years","Required skills"]),
    description: 'Exciting opportunity to work on challenging projects. Join our dynamic team.',
    applyLink: 'https://careers.example.com/job75',
    category: 'Business',
    postedDate: new Date('2026-08-12')
  },
  {
    title: 'Graphic Designer',
    company: 'Future Tech',
    location: 'Pune',
    type: 'Full-time',
    salary: '3-7 LPA',
    experience: '1-3 years',
    skills: JSON.stringify(["Photoshop","Illustrator","Design"]),
    requirements: JSON.stringify(["Relevant degree","1-3 years","Required skills"]),
    description: 'Exciting opportunity to work on challenging projects. Join our dynamic team.',
    applyLink: 'https://careers.example.com/job76',
    category: 'Creative',
    postedDate: new Date('2026-08-24')
  },
  {
    title: 'Graphic Designer',
    company: 'AI Labs',
    location: 'Noida',
    type: 'Part-time',
    salary: '3-7 LPA',
    experience: '1-3 years',
    skills: JSON.stringify(["Photoshop","Illustrator","Design"]),
    requirements: JSON.stringify(["Relevant degree","1-3 years","Required skills"]),
    description: 'Flexible part-time opportunity with good compensation. Work-life balance.',
    applyLink: 'https://careers.example.com/job77',
    category: 'Creative',
    postedDate: new Date('2026-08-25')
  },
  {
    title: 'Graphic Designer',
    company: 'Digital Solutions',
    location: 'Kolkata',
    type: 'Full-time',
    salary: '3-7 LPA',
    experience: '1-3 years',
    skills: JSON.stringify(["Photoshop","Illustrator","Design"]),
    requirements: JSON.stringify(["Relevant degree","1-3 years","Required skills"]),
    description: 'Exciting opportunity to work on challenging projects. Join our dynamic team.',
    applyLink: 'https://careers.example.com/job78',
    category: 'Creative',
    postedDate: new Date('2026-08-20')
  },
  {
    title: 'Video Editor',
    company: 'Future Tech',
    location: 'Kolkata',
    type: 'Full-time',
    salary: '4-9 LPA',
    experience: '2-4 years',
    skills: JSON.stringify(["Premiere Pro","After Effects"]),
    requirements: JSON.stringify(["Relevant degree","2-4 years","Required skills"]),
    description: 'Exciting opportunity to work on challenging projects. Join our dynamic team.',
    applyLink: 'https://careers.example.com/job79',
    category: 'Creative',
    postedDate: new Date('2026-08-03')
  },
  {
    title: 'Video Editor',
    company: 'Cloud First',
    location: 'Ahmedabad',
    type: 'Part-time',
    salary: '4-9 LPA',
    experience: '2-4 years',
    skills: JSON.stringify(["Premiere Pro","After Effects"]),
    requirements: JSON.stringify(["Relevant degree","2-4 years","Required skills"]),
    description: 'Flexible part-time opportunity with good compensation. Work-life balance.',
    applyLink: 'https://careers.example.com/job80',
    category: 'Creative',
    postedDate: new Date('2026-08-16')
  },
  {
    title: 'Video Editor',
    company: 'Innovation Ltd',
    location: 'Mumbai',
    type: 'Full-time',
    salary: '4-9 LPA',
    experience: '2-4 years',
    skills: JSON.stringify(["Premiere Pro","After Effects"]),
    requirements: JSON.stringify(["Relevant degree","2-4 years","Required skills"]),
    description: 'Exciting opportunity to work on challenging projects. Join our dynamic team.',
    applyLink: 'https://careers.example.com/job81',
    category: 'Creative',
    postedDate: new Date('2026-08-19')
  },
  {
    title: 'Content Writer',
    company: 'Data Insights',
    location: 'Ahmedabad',
    type: 'Full-time',
    salary: '3-6 LPA',
    experience: '1-3 years',
    skills: JSON.stringify(["Writing","SEO","Content"]),
    requirements: JSON.stringify(["Relevant degree","1-3 years","Required skills"]),
    description: 'Exciting opportunity to work on challenging projects. Join our dynamic team.',
    applyLink: 'https://careers.example.com/job82',
    category: 'Creative',
    postedDate: new Date('2026-08-26')
  },
  {
    title: 'Content Writer',
    company: 'Cloud First',
    location: 'Gurgaon',
    type: 'Part-time',
    salary: '3-6 LPA',
    experience: '1-3 years',
    skills: JSON.stringify(["Writing","SEO","Content"]),
    requirements: JSON.stringify(["Relevant degree","1-3 years","Required skills"]),
    description: 'Flexible part-time opportunity with good compensation. Work-life balance.',
    applyLink: 'https://careers.example.com/job83',
    category: 'Creative',
    postedDate: new Date('2026-08-05')
  },
  {
    title: 'Content Writer',
    company: 'Tech Corp',
    location: 'Pune',
    type: 'Full-time',
    salary: '3-6 LPA',
    experience: '1-3 years',
    skills: JSON.stringify(["Writing","SEO","Content"]),
    requirements: JSON.stringify(["Relevant degree","1-3 years","Required skills"]),
    description: 'Exciting opportunity to work on challenging projects. Join our dynamic team.',
    applyLink: 'https://careers.example.com/job84',
    category: 'Creative',
    postedDate: new Date('2026-08-13')
  },
  {
    title: 'Copywriter',
    company: 'Smart Systems',
    location: 'Chennai',
    type: 'Full-time',
    salary: '4-8 LPA',
    experience: '2-4 years',
    skills: JSON.stringify(["Copywriting","Advertising","Creative"]),
    requirements: JSON.stringify(["Relevant degree","2-4 years","Required skills"]),
    description: 'Exciting opportunity to work on challenging projects. Join our dynamic team.',
    applyLink: 'https://careers.example.com/job85',
    category: 'Creative',
    postedDate: new Date('2026-08-06')
  },
  {
    title: 'Copywriter',
    company: 'Smart Systems',
    location: 'Gurgaon',
    type: 'Part-time',
    salary: '4-8 LPA',
    experience: '2-4 years',
    skills: JSON.stringify(["Copywriting","Advertising","Creative"]),
    requirements: JSON.stringify(["Relevant degree","2-4 years","Required skills"]),
    description: 'Flexible part-time opportunity with good compensation. Work-life balance.',
    applyLink: 'https://careers.example.com/job86',
    category: 'Creative',
    postedDate: new Date('2026-08-05')
  },
  {
    title: 'Copywriter',
    company: 'Digital Solutions',
    location: 'Noida',
    type: 'Full-time',
    salary: '4-8 LPA',
    experience: '2-4 years',
    skills: JSON.stringify(["Copywriting","Advertising","Creative"]),
    requirements: JSON.stringify(["Relevant degree","2-4 years","Required skills"]),
    description: 'Exciting opportunity to work on challenging projects. Join our dynamic team.',
    applyLink: 'https://careers.example.com/job87',
    category: 'Creative',
    postedDate: new Date('2026-08-04')
  },
  {
    title: 'Motion Graphics Designer',
    company: 'Digital Solutions',
    location: 'Noida',
    type: 'Full-time',
    salary: '5-10 LPA',
    experience: '2-5 years',
    skills: JSON.stringify(["After Effects","Animation"]),
    requirements: JSON.stringify(["Relevant degree","2-5 years","Required skills"]),
    description: 'Exciting opportunity to work on challenging projects. Join our dynamic team.',
    applyLink: 'https://careers.example.com/job88',
    category: 'Creative',
    postedDate: new Date('2026-08-27')
  },
  {
    title: 'Motion Graphics Designer',
    company: 'Smart Systems',
    location: 'Kolkata',
    type: 'Part-time',
    salary: '5-10 LPA',
    experience: '2-5 years',
    skills: JSON.stringify(["After Effects","Animation"]),
    requirements: JSON.stringify(["Relevant degree","2-5 years","Required skills"]),
    description: 'Flexible part-time opportunity with good compensation. Work-life balance.',
    applyLink: 'https://careers.example.com/job89',
    category: 'Creative',
    postedDate: new Date('2026-08-04')
  },
  {
    title: 'Motion Graphics Designer',
    company: 'Cloud First',
    location: 'Hyderabad',
    type: 'Full-time',
    salary: '5-10 LPA',
    experience: '2-5 years',
    skills: JSON.stringify(["After Effects","Animation"]),
    requirements: JSON.stringify(["Relevant degree","2-5 years","Required skills"]),
    description: 'Exciting opportunity to work on challenging projects. Join our dynamic team.',
    applyLink: 'https://careers.example.com/job90',
    category: 'Creative',
    postedDate: new Date('2026-08-11')
  },
  {
    title: '3D Artist',
    company: 'Tech Corp',
    location: 'Ahmedabad',
    type: 'Full-time',
    salary: '4-9 LPA',
    experience: '1-4 years',
    skills: JSON.stringify(["Blender","Maya","3D Modeling"]),
    requirements: JSON.stringify(["Relevant degree","1-4 years","Required skills"]),
    description: 'Exciting opportunity to work on challenging projects. Join our dynamic team.',
    applyLink: 'https://careers.example.com/job91',
    category: 'Creative',
    postedDate: new Date('2026-08-23')
  },
  {
    title: '3D Artist',
    company: 'Cloud First',
    location: 'Noida',
    type: 'Part-time',
    salary: '4-9 LPA',
    experience: '1-4 years',
    skills: JSON.stringify(["Blender","Maya","3D Modeling"]),
    requirements: JSON.stringify(["Relevant degree","1-4 years","Required skills"]),
    description: 'Flexible part-time opportunity with good compensation. Work-life balance.',
    applyLink: 'https://careers.example.com/job92',
    category: 'Creative',
    postedDate: new Date('2026-08-17')
  },
  {
    title: '3D Artist',
    company: 'Data Insights',
    location: 'Mumbai',
    type: 'Full-time',
    salary: '4-9 LPA',
    experience: '1-4 years',
    skills: JSON.stringify(["Blender","Maya","3D Modeling"]),
    requirements: JSON.stringify(["Relevant degree","1-4 years","Required skills"]),
    description: 'Exciting opportunity to work on challenging projects. Join our dynamic team.',
    applyLink: 'https://careers.example.com/job93',
    category: 'Creative',
    postedDate: new Date('2026-08-26')
  },
  {
    title: 'Animator',
    company: 'AI Labs',
    location: 'Remote',
    type: 'Full-time',
    salary: '3-7 LPA',
    experience: '1-3 years',
    skills: JSON.stringify(["Animation","2D/3D","Character Design"]),
    requirements: JSON.stringify(["Relevant degree","1-3 years","Required skills"]),
    description: 'Exciting opportunity to work on challenging projects. Join our dynamic team.',
    applyLink: 'https://careers.example.com/job94',
    category: 'Creative',
    postedDate: new Date('2026-08-13')
  },
  {
    title: 'Animator',
    company: 'Data Insights',
    location: 'Kolkata',
    type: 'Part-time',
    salary: '3-7 LPA',
    experience: '1-3 years',
    skills: JSON.stringify(["Animation","2D/3D","Character Design"]),
    requirements: JSON.stringify(["Relevant degree","1-3 years","Required skills"]),
    description: 'Flexible part-time opportunity with good compensation. Work-life balance.',
    applyLink: 'https://careers.example.com/job95',
    category: 'Creative',
    postedDate: new Date('2026-08-21')
  },
  {
    title: 'Animator',
    company: 'Future Tech',
    location: 'Kolkata',
    type: 'Full-time',
    salary: '3-7 LPA',
    experience: '1-3 years',
    skills: JSON.stringify(["Animation","2D/3D","Character Design"]),
    requirements: JSON.stringify(["Relevant degree","1-3 years","Required skills"]),
    description: 'Exciting opportunity to work on challenging projects. Join our dynamic team.',
    applyLink: 'https://careers.example.com/job96',
    category: 'Creative',
    postedDate: new Date('2026-08-05')
  },
  {
    title: 'Interior Designer',
    company: 'Digital Solutions',
    location: 'Noida',
    type: 'Full-time',
    salary: '4-8 LPA',
    experience: '2-5 years',
    skills: JSON.stringify(["Interior Design","AutoCAD","3D"]),
    requirements: JSON.stringify(["Relevant degree","2-5 years","Required skills"]),
    description: 'Exciting opportunity to work on challenging projects. Join our dynamic team.',
    applyLink: 'https://careers.example.com/job97',
    category: 'Creative',
    postedDate: new Date('2026-08-09')
  },
  {
    title: 'Interior Designer',
    company: 'Future Tech',
    location: 'Delhi',
    type: 'Part-time',
    salary: '4-8 LPA',
    experience: '2-5 years',
    skills: JSON.stringify(["Interior Design","AutoCAD","3D"]),
    requirements: JSON.stringify(["Relevant degree","2-5 years","Required skills"]),
    description: 'Flexible part-time opportunity with good compensation. Work-life balance.',
    applyLink: 'https://careers.example.com/job98',
    category: 'Creative',
    postedDate: new Date('2026-08-18')
  },
  {
    title: 'Interior Designer',
    company: 'Cloud First',
    location: 'Chennai',
    type: 'Full-time',
    salary: '4-8 LPA',
    experience: '2-5 years',
    skills: JSON.stringify(["Interior Design","AutoCAD","3D"]),
    requirements: JSON.stringify(["Relevant degree","2-5 years","Required skills"]),
    description: 'Exciting opportunity to work on challenging projects. Join our dynamic team.',
    applyLink: 'https://careers.example.com/job99',
    category: 'Creative',
    postedDate: new Date('2026-08-11')
  },
  {
    title: 'Staff Nurse',
    company: 'Data Insights',
    location: 'Noida',
    type: 'Full-time',
    salary: '3-6 LPA',
    experience: '0-3 years',
    skills: JSON.stringify(["Nursing","Patient Care"]),
    requirements: JSON.stringify(["Relevant degree","0-3 years","Required skills"]),
    description: 'Exciting opportunity to work on challenging projects. Join our dynamic team.',
    applyLink: 'https://careers.example.com/job100',
    category: 'Medical',
    postedDate: new Date('2026-08-03')
  },
  {
    title: 'Staff Nurse',
    company: 'Future Tech',
    location: 'Noida',
    type: 'Part-time',
    salary: '3-6 LPA',
    experience: '0-3 years',
    skills: JSON.stringify(["Nursing","Patient Care"]),
    requirements: JSON.stringify(["Relevant degree","0-3 years","Required skills"]),
    description: 'Flexible part-time opportunity with good compensation. Work-life balance.',
    applyLink: 'https://careers.example.com/job101',
    category: 'Medical',
    postedDate: new Date('2026-08-24')
  },
  {
    title: 'Staff Nurse',
    company: 'Innovation Ltd',
    location: 'Noida',
    type: 'Full-time',
    salary: '3-6 LPA',
    experience: '0-3 years',
    skills: JSON.stringify(["Nursing","Patient Care"]),
    requirements: JSON.stringify(["Relevant degree","0-3 years","Required skills"]),
    description: 'Exciting opportunity to work on challenging projects. Join our dynamic team.',
    applyLink: 'https://careers.example.com/job102',
    category: 'Medical',
    postedDate: new Date('2026-08-11')
  },
  {
    title: 'Pharmacist',
    company: 'Digital Solutions',
    location: 'Delhi',
    type: 'Full-time',
    salary: '3-5 LPA',
    experience: '0-2 years',
    skills: JSON.stringify(["Pharmacy","Drug Knowledge"]),
    requirements: JSON.stringify(["Relevant degree","0-2 years","Required skills"]),
    description: 'Exciting opportunity to work on challenging projects. Join our dynamic team.',
    applyLink: 'https://careers.example.com/job103',
    category: 'Medical',
    postedDate: new Date('2026-08-10')
  },
  {
    title: 'Pharmacist',
    company: 'Data Insights',
    location: 'Chennai',
    type: 'Part-time',
    salary: '3-5 LPA',
    experience: '0-2 years',
    skills: JSON.stringify(["Pharmacy","Drug Knowledge"]),
    requirements: JSON.stringify(["Relevant degree","0-2 years","Required skills"]),
    description: 'Flexible part-time opportunity with good compensation. Work-life balance.',
    applyLink: 'https://careers.example.com/job104',
    category: 'Medical',
    postedDate: new Date('2026-08-27')
  },
  {
    title: 'Pharmacist',
    company: 'Innovation Ltd',
    location: 'Bangalore',
    type: 'Full-time',
    salary: '3-5 LPA',
    experience: '0-2 years',
    skills: JSON.stringify(["Pharmacy","Drug Knowledge"]),
    requirements: JSON.stringify(["Relevant degree","0-2 years","Required skills"]),
    description: 'Exciting opportunity to work on challenging projects. Join our dynamic team.',
    applyLink: 'https://careers.example.com/job105',
    category: 'Medical',
    postedDate: new Date('2026-08-08')
  },
  {
    title: 'Physiotherapist',
    company: 'Future Tech',
    location: 'Remote',
    type: 'Full-time',
    salary: '4-7 LPA',
    experience: '1-4 years',
    skills: JSON.stringify(["Physiotherapy","Rehabilitation"]),
    requirements: JSON.stringify(["Relevant degree","1-4 years","Required skills"]),
    description: 'Exciting opportunity to work on challenging projects. Join our dynamic team.',
    applyLink: 'https://careers.example.com/job106',
    category: 'Medical',
    postedDate: new Date('2026-08-11')
  },
  {
    title: 'Physiotherapist',
    company: 'AI Labs',
    location: 'Ahmedabad',
    type: 'Part-time',
    salary: '4-7 LPA',
    experience: '1-4 years',
    skills: JSON.stringify(["Physiotherapy","Rehabilitation"]),
    requirements: JSON.stringify(["Relevant degree","1-4 years","Required skills"]),
    description: 'Flexible part-time opportunity with good compensation. Work-life balance.',
    applyLink: 'https://careers.example.com/job107',
    category: 'Medical',
    postedDate: new Date('2026-08-25')
  },
  {
    title: 'Physiotherapist',
    company: 'Data Insights',
    location: 'Remote',
    type: 'Full-time',
    salary: '4-7 LPA',
    experience: '1-4 years',
    skills: JSON.stringify(["Physiotherapy","Rehabilitation"]),
    requirements: JSON.stringify(["Relevant degree","1-4 years","Required skills"]),
    description: 'Exciting opportunity to work on challenging projects. Join our dynamic team.',
    applyLink: 'https://careers.example.com/job108',
    category: 'Medical',
    postedDate: new Date('2026-08-28')
  },
  {
    title: 'Lab Technician',
    company: 'Tech Corp',
    location: 'Hyderabad',
    type: 'Full-time',
    salary: '2-4 LPA',
    experience: '0-2 years',
    skills: JSON.stringify(["Lab Testing","Analysis"]),
    requirements: JSON.stringify(["Relevant degree","0-2 years","Required skills"]),
    description: 'Exciting opportunity to work on challenging projects. Join our dynamic team.',
    applyLink: 'https://careers.example.com/job109',
    category: 'Medical',
    postedDate: new Date('2026-08-05')
  },
  {
    title: 'Lab Technician',
    company: 'Smart Systems',
    location: 'Kolkata',
    type: 'Part-time',
    salary: '2-4 LPA',
    experience: '0-2 years',
    skills: JSON.stringify(["Lab Testing","Analysis"]),
    requirements: JSON.stringify(["Relevant degree","0-2 years","Required skills"]),
    description: 'Flexible part-time opportunity with good compensation. Work-life balance.',
    applyLink: 'https://careers.example.com/job110',
    category: 'Medical',
    postedDate: new Date('2026-08-12')
  }
]

module.exports = jobs
