const { PrismaClient } = require('@prisma/client')
const bcrypt = require('bcryptjs')
const careersData = require('./careers-data')
const jobsData = require('./jobs-data')

const prisma = new PrismaClient()

async function main() {
  console.log('🌱 Starting database seeding...')

  // Clear existing data (child tables first because of foreign keys)
  await prisma.recommendation.deleteMany({})
  await prisma.bookmark.deleteMany({})
  await prisma.careerRoadmap.deleteMany({})
  await prisma.fAQ.deleteMany({})
  await prisma.successStory.deleteMany({})
  await prisma.notification.deleteMany({})
  await prisma.feedback.deleteMany({})
  await prisma.report.deleteMany({})
  await prisma.job.deleteMany({})
  await prisma.internship.deleteMany({})
  await prisma.scholarship.deleteMany({})
  await prisma.career.deleteMany({})
  await prisma.exam.deleteMany({})
  await prisma.college.deleteMany({})
  console.log('🗑️  Cleared existing data')

  // Create admin user
  const adminPassword = await bcrypt.hash('admin123', 10)
  const admin = await prisma.user.upsert({
    where: { email: 'admin@careerguide.com' },
    update: {},
    create: {
      email: 'admin@careerguide.com',
      password: adminPassword,
      name: 'Admin User',
      role: 'ADMIN',
    },
  })
  console.log('✅ Admin user created')

  // Create sample student user
  const studentPassword = await bcrypt.hash('student123', 10)
  const student = await prisma.user.upsert({
    where: { email: 'student@example.com' },
    update: {},
    create: {
      email: 'student@example.com',
      password: studentPassword,
      name: 'John Doe',
      role: 'STUDENT',
      currentStatus: '12th Science',
      education: 'High School',
      interests: JSON.stringify(['Technology', 'Problem Solving', 'Innovation']),
      skills: JSON.stringify(['Programming', 'Mathematics', 'Communication']),
    },
  })
  console.log('✅ Sample student created')

  // ====================
  // CAREERS DATA (100+)
  // ====================
  console.log('📊 Seeding careers...')
  for (const careerData of careersData) {
    await prisma.career.upsert({
      where: { slug: careerData.slug },
      update: {},
      create: careerData,
    })
  }
  console.log(`✅ Created ${careersData.length} careers`)

  // ====================
  // JOBS DATA (100+)
  // ====================
  console.log('💼 Seeding jobs...')
  for (const jobData of jobsData) {
    await prisma.job.create({
      data: jobData,
    })
  }
  console.log(`✅ Created ${jobsData.length} jobs`)

  const internships = [
    { title: 'Software Development Intern', company: 'Tata Consultancy Services', location: 'Bangalore', type: 'Hybrid', duration: '6 months', stipend: '₹25,000/month', description: 'Work on real client projects with mentorship from senior engineers.', requirements: JSON.stringify(['Pursuing B.Tech/BCA', 'Basic programming']), skills: JSON.stringify(['Java', 'SQL', 'Git']), applyLink: 'https://www.tcs.com/careers', category: 'Technology' },
    { title: 'Frontend Intern', company: 'Infosys', location: 'Pune', type: 'On-site', duration: '3 months', stipend: '₹20,000/month', description: 'Build user interfaces for enterprise web applications.', requirements: JSON.stringify(['HTML/CSS/JS', 'React basics']), skills: JSON.stringify(['React', 'JavaScript', 'CSS']), applyLink: 'https://www.infosys.com/careers', category: 'Technology' },
    { title: 'Data Analytics Intern', company: 'Wipro', location: 'Hyderabad', type: 'Remote', duration: '4 months', stipend: '₹18,000/month', description: 'Analyze datasets and create dashboards for business teams.', requirements: JSON.stringify(['Excel', 'SQL']), skills: JSON.stringify(['Python', 'Excel', 'SQL']), applyLink: 'https://careers.wipro.com', category: 'Technology' },
    { title: 'Marketing Intern', company: 'Unacademy', location: 'Remote', type: 'Remote', duration: '3 months', stipend: '₹15,000/month', description: 'Support digital campaigns and content for student products.', requirements: JSON.stringify(['Communication skills']), skills: JSON.stringify(['Content', 'Social Media']), applyLink: 'https://unacademy.com/careers', category: 'Business' },
    { title: 'UI/UX Design Intern', company: 'Zoho', location: 'Chennai', type: 'Hybrid', duration: '6 months', stipend: '₹22,000/month', description: 'Design product screens and improve user flows.', requirements: JSON.stringify(['Portfolio required']), skills: JSON.stringify(['Figma', 'Wireframing']), applyLink: 'https://www.zoho.com/careers', category: 'Creative' },
    { title: 'HR Intern', company: 'Deloitte', location: 'Mumbai', type: 'On-site', duration: '3 months', stipend: '₹20,000/month', description: 'Assist campus hiring and employee engagement programs.', requirements: JSON.stringify(['MBA/BBA preferred']), skills: JSON.stringify(['Communication', 'MS Office']), applyLink: 'https://www.deloitte.com/careers', category: 'Business' },
    { title: 'Mechanical Design Intern', company: 'Larsen & Toubro', location: 'Chennai', type: 'On-site', duration: '6 months', stipend: '₹18,000/month', description: 'Support CAD drafting and site documentation.', requirements: JSON.stringify(['Mechanical engineering student']), skills: JSON.stringify(['AutoCAD', 'SolidWorks']), applyLink: 'https://www.larsentoubro.com/careers', category: 'Engineering' },
    { title: 'Content Writing Intern', company: 'Byju\'s', location: 'Remote', type: 'Remote', duration: '3 months', stipend: '₹12,000/month', description: 'Write educational articles and exam preparation content.', requirements: JSON.stringify(['Strong English writing']), skills: JSON.stringify(['Writing', 'Research']), applyLink: 'https://byjus.com/careers', category: 'Creative' },
  ]

  console.log('🎓 Seeding internships...')
  for (const internship of internships) {
    await prisma.internship.create({ data: internship })
  }
  console.log(`✅ Created ${internships.length} internships`)

  const scholarships = [
    { name: 'National Scholarship Portal (NSP)', slug: 'nsp-central', provider: 'Government of India', amount: '₹10,000 - ₹2,00,000/year', description: 'Central and state scholarships for school, college, and professional courses.', eligibility: JSON.stringify(['Indian citizen', 'Income and merit criteria vary by scheme']), applicationProcess: 'Apply on scholarships.gov.in with documents and institute verification.', officialLink: 'https://scholarships.gov.in', category: 'Need-based', targetGroup: 'General' },
    { name: 'INSPIRE Scholarship', slug: 'inspire-scholarship', provider: 'Department of Science & Technology', amount: '₹80,000/year', description: 'Scholarship for students pursuing natural and basic sciences after 12th.', eligibility: JSON.stringify(['Top 1% in 12th boards or JEE/NEET rank holders', 'B.Sc/Integrated M.Sc']), applicationProcess: 'Online application through DST INSPIRE portal.', officialLink: 'https://online-inspire.gov.in', category: 'Merit-based', targetGroup: 'Science students' },
    { name: 'PM Yasasvi Scholarship', slug: 'pm-yasasvi', provider: 'Ministry of Social Justice', amount: 'Up to ₹1,25,000/year', description: 'Pre and post-matric scholarships for OBC, EBC and DNT students.', eligibility: JSON.stringify(['OBC/EBC/DNT', 'Income criteria as notified']), applicationProcess: 'Apply via National Scholarship Portal.', officialLink: 'https://yet.nta.ac.in', category: 'Need-based', targetGroup: 'OBC/EBC/DNT' },
    { name: 'AICTE Pragati Scholarship', slug: 'aicte-pragati', provider: 'AICTE', amount: '₹50,000/year', description: 'Scholarship for girl students in technical education (degree/diploma).', eligibility: JSON.stringify(['Girl student', 'Admitted to AICTE approved course']), applicationProcess: 'Apply on AICTE scholarship portal.', officialLink: 'https://www.aicte-india.org', category: 'Merit-based', targetGroup: 'Female' },
    { name: 'Reliance Foundation Undergraduate Scholarship', slug: 'reliance-ug', provider: 'Reliance Foundation', amount: 'Up to ₹2,00,000/year', description: 'Merit-cum-means scholarship for first-year undergraduate students.', eligibility: JSON.stringify(['First-year UG', 'Family income typically below ₹15 LPA']), applicationProcess: 'Online application with aptitude test.', officialLink: 'https://www.scholarships.reliancefoundation.org', category: 'Merit-based', targetGroup: 'Undergraduate' },
    { name: 'Tata Scholarship for Cornell', slug: 'tata-cornell', provider: 'Tata Education and Development Trust', amount: 'Full need-based funding', description: 'Need-based scholarship for Indian undergraduates at Cornell University.', eligibility: JSON.stringify(['Indian citizen', 'Admitted to Cornell undergraduate program']), applicationProcess: 'Through Cornell financial aid and Tata Trust process.', officialLink: 'https://www.tata.com', category: 'Need-based', targetGroup: 'Undergraduate abroad' },
    { name: 'Sports Authority of India Scholarship', slug: 'sai-scholarship', provider: 'Sports Authority of India', amount: 'Stipend + training support', description: 'Support for promising athletes in recognized sports disciplines.', eligibility: JSON.stringify(['National/state-level sports achievement']), applicationProcess: 'Apply via SAI / Khelo India channels.', officialLink: 'https://sportsauthorityofindia.nic.in', category: 'Sports', targetGroup: 'Athletes' },
    { name: 'UGC NET JRF', slug: 'ugc-net-jrf', provider: 'UGC / NTA', amount: '₹37,000/month + HRA', description: 'Fellowship for research scholars who qualify UGC NET with JRF.', eligibility: JSON.stringify(['Postgraduate', 'Qualified UGC NET JRF']), applicationProcess: 'Qualify UGC NET; fellowship through university.', officialLink: 'https://ugcnet.nta.nic.in', category: 'Research', targetGroup: 'Postgraduate' },
  ]

  console.log('🏅 Seeding scholarships...')
  for (const scholarship of scholarships) {
    await prisma.scholarship.create({ data: scholarship })
  }
  console.log(`✅ Created ${scholarships.length} scholarships`)

  // ====================
  // COLLEGES DATA
  // ====================
  const colleges = [
    // DELHI
    { name: 'Indian Institute of Technology Delhi', slug: 'iit-delhi', type: 'Government', state: 'Delhi', city: 'New Delhi', location: 'Hauz Khas, New Delhi', establishedYear: 1961, affiliation: 'Autonomous', accreditation: JSON.stringify(['NAAC A++', 'NBA']), ranking: JSON.stringify({ nirf: '2', qs: '174' }), coursesOffered: JSON.stringify(['B.Tech', 'M.Tech', 'PhD', 'MBA']), averageFees: '2-3 Lakhs/year', placementRate: '95%', averagePackage: '18 LPA', facilities: JSON.stringify(['Hostel', 'Library', 'Labs', 'Sports']), admissionProcess: 'JEE Advanced', cutoffs: JSON.stringify({ jeeAdvanced: '500-1000 rank' }), contactInfo: JSON.stringify({ phone: '+91-11-2659-1749', email: 'info@admin.iitd.ac.in', website: 'https://home.iitd.ac.in' }), officialWebsite: 'https://home.iitd.ac.in' },
    { name: 'Jawaharlal Nehru University', slug: 'jnu-delhi', type: 'Government', state: 'Delhi', city: 'New Delhi', location: 'New Mehrauli Road, New Delhi', establishedYear: 1969, affiliation: 'Central University', accreditation: JSON.stringify(['NAAC A++']), ranking: JSON.stringify({ nirf: '3', qs: '601-650' }), coursesOffered: JSON.stringify(['BA', 'MA', 'MPhil', 'PhD', 'M.Sc']), averageFees: '400-800/year', placementRate: '70%', averagePackage: '6-8 LPA', facilities: JSON.stringify(['Hostel', 'Library', 'Auditorium']), admissionProcess: 'CUET', cutoffs: JSON.stringify({ cuet: '70-90%' }), contactInfo: JSON.stringify({ phone: '+91-11-2670-4040', website: 'https://www.jnu.ac.in' }), officialWebsite: 'https://www.jnu.ac.in' },
    { name: 'Delhi Technological University', slug: 'dtu-delhi', type: 'Government', state: 'Delhi', city: 'New Delhi', location: 'Bawana Road, Delhi', establishedYear: 1941, affiliation: 'State University', accreditation: JSON.stringify(['NAAC A+', 'NBA']), ranking: JSON.stringify({ nirf: '36' }), coursesOffered: JSON.stringify(['B.Tech', 'M.Tech', 'MBA', 'MCA']), averageFees: '1.5-2 Lakhs/year', placementRate: '90%', averagePackage: '12 LPA', facilities: JSON.stringify(['Hostel', 'Library', 'Labs', 'Gym']), admissionProcess: 'JEE Main', cutoffs: JSON.stringify({ jeeMain: '5000-15000 rank' }), contactInfo: JSON.stringify({ phone: '+91-11-2787-1010', website: 'http://www.dtu.ac.in' }), officialWebsite: 'http://www.dtu.ac.in' },
    { name: 'Netaji Subhas University of Technology', slug: 'nsut-delhi', type: 'Government', state: 'Delhi', city: 'New Delhi', location: 'Dwarka, New Delhi', establishedYear: 1983, affiliation: 'State University', accreditation: JSON.stringify(['NAAC A+', 'NBA']), ranking: JSON.stringify({ nirf: '47' }), coursesOffered: JSON.stringify(['B.Tech', 'M.Tech', 'MBA']), averageFees: '1.5 Lakhs/year', placementRate: '88%', averagePackage: '11 LPA', facilities: JSON.stringify(['Hostel', 'Library', 'Sports']), admissionProcess: 'JEE Main', cutoffs: JSON.stringify({ jeeMain: '8000-20000 rank' }), contactInfo: JSON.stringify({ phone: '+91-11-2590-7325', website: 'http://www.nsut.ac.in' }), officialWebsite: 'http://www.nsut.ac.in' },
    { name: 'Indraprastha Institute of Information Technology', slug: 'iiit-delhi', type: 'Government', state: 'Delhi', city: 'New Delhi', location: 'Okhla, New Delhi', establishedYear: 2008, affiliation: 'State University', accreditation: JSON.stringify(['NAAC A++']), ranking: JSON.stringify({ nirf: '64' }), coursesOffered: JSON.stringify(['B.Tech', 'M.Tech', 'PhD']), averageFees: '3-4 Lakhs/year', placementRate: '100%', averagePackage: '20 LPA', facilities: JSON.stringify(['Hostel', 'Library', 'Research Labs']), admissionProcess: 'JEE Main', cutoffs: JSON.stringify({ jeeMain: '2000-5000 rank' }), contactInfo: JSON.stringify({ phone: '+91-11-2690-7400', website: 'https://www.iiitd.ac.in' }), officialWebsite: 'https://www.iiitd.ac.in' },
    { name: 'Amity University Delhi', slug: 'amity-delhi', type: 'Private', state: 'Delhi', city: 'New Delhi', location: 'Noida, Delhi NCR', establishedYear: 2005, affiliation: 'Private University', accreditation: JSON.stringify(['NAAC A+']), ranking: JSON.stringify({ nirf: '35-40' }), coursesOffered: JSON.stringify(['B.Tech', 'BBA', 'MBA', 'LLB']), averageFees: '3-5 Lakhs/year', placementRate: '85%', averagePackage: '6-8 LPA', facilities: JSON.stringify(['Hostel', 'Library', 'Sports', 'Cafeteria']), admissionProcess: 'Amity JEE', cutoffs: JSON.stringify({ amityJee: '70%' }), contactInfo: JSON.stringify({ phone: '+91-120-471-5000', website: 'https://www.amity.edu' }), officialWebsite: 'https://www.amity.edu' },
    
    // MAHARASHTRA
    { name: 'Indian Institute of Technology Bombay', slug: 'iit-bombay', type: 'Government', state: 'Maharashtra', city: 'Mumbai', location: 'Powai, Mumbai', establishedYear: 1958, affiliation: 'Autonomous', accreditation: JSON.stringify(['NAAC A++', 'NBA']), ranking: JSON.stringify({ nirf: '3', qs: '149' }), coursesOffered: JSON.stringify(['B.Tech', 'M.Tech', 'PhD', 'MBA']), averageFees: '2-3 Lakhs/year', placementRate: '96%', averagePackage: '21 LPA', facilities: JSON.stringify(['Hostel', 'Library', 'Labs', 'Sports Complex']), admissionProcess: 'JEE Advanced', cutoffs: JSON.stringify({ jeeAdvanced: '100-500 rank' }), contactInfo: JSON.stringify({ phone: '+91-22-2576-4545', website: 'https://www.iitb.ac.in' }), officialWebsite: 'https://www.iitb.ac.in' },
    { name: 'College of Engineering Pune', slug: 'coep-pune', type: 'Government', state: 'Maharashtra', city: 'Pune', location: 'Shivajinagar, Pune', establishedYear: 1854, affiliation: 'SPPU', accreditation: JSON.stringify(['NAAC A++', 'NBA']), ranking: JSON.stringify({ nirf: '71' }), coursesOffered: JSON.stringify(['B.Tech', 'M.Tech']), averageFees: '1 Lakh/year', placementRate: '90%', averagePackage: '8 LPA', facilities: JSON.stringify(['Hostel', 'Library', 'Labs']), admissionProcess: 'MHT CET', cutoffs: JSON.stringify({ mhtCet: '98+%ile' }), contactInfo: JSON.stringify({ phone: '+91-20-2553-7206', website: 'https://www.coep.org.in' }), officialWebsite: 'https://www.coep.org.in' },
    { name: 'Veermata Jijabai Technological Institute', slug: 'vjti-mumbai', type: 'Government', state: 'Maharashtra', city: 'Mumbai', location: 'Matunga, Mumbai', establishedYear: 1887, affiliation: 'Autonomous', accreditation: JSON.stringify(['NAAC A+', 'NBA']), ranking: JSON.stringify({ nirf: '58' }), coursesOffered: JSON.stringify(['B.Tech', 'M.Tech', 'MCA']), averageFees: '1 Lakh/year', placementRate: '95%', averagePackage: '10 LPA', facilities: JSON.stringify(['Hostel', 'Library', 'Labs']), admissionProcess: 'MHT CET, JEE Main', cutoffs: JSON.stringify({ mhtCet: '99%ile' }), contactInfo: JSON.stringify({ phone: '+91-22-2419-7101', website: 'https://www.vjti.ac.in' }), officialWebsite: 'https://www.vjti.ac.in' },
    { name: 'Institute of Chemical Technology Mumbai', slug: 'ict-mumbai', type: 'Government', state: 'Maharashtra', city: 'Mumbai', location: 'Matunga, Mumbai', establishedYear: 1933, affiliation: 'Deemed University', accreditation: JSON.stringify(['NAAC A++']), ranking: JSON.stringify({ nirf: '15' }), coursesOffered: JSON.stringify(['B.Tech Chemical', 'M.Tech', 'PhD']), averageFees: '1.5 Lakhs/year', placementRate: '92%', averagePackage: '12 LPA', facilities: JSON.stringify(['Hostel', 'Library', 'Research Labs']), admissionProcess: 'JEE Main', cutoffs: JSON.stringify({ jeeMain: '5000-10000 rank' }), contactInfo: JSON.stringify({ phone: '+91-22-3361-1001', website: 'https://www.ictmumbai.edu.in' }), officialWebsite: 'https://www.ictmumbai.edu.in' },
    { name: 'Symbiosis International University', slug: 'siu-pune', type: 'Deemed', state: 'Maharashtra', city: 'Pune', location: 'Lavale, Pune', establishedYear: 1971, affiliation: 'Deemed University', accreditation: JSON.stringify(['NAAC A++']), ranking: JSON.stringify({ nirf: '25' }), coursesOffered: JSON.stringify(['MBA', 'BBA', 'Law', 'Engineering']), averageFees: '5-10 Lakhs/year', placementRate: '90%', averagePackage: '9 LPA', facilities: JSON.stringify(['Hostel', 'Library', 'Sports', 'International Campus']), admissionProcess: 'SNAP, SET', cutoffs: JSON.stringify({ snap: '90%ile' }), contactInfo: JSON.stringify({ phone: '+91-20-3911-5000', website: 'https://www.siu.edu.in' }), officialWebsite: 'https://www.siu.edu.in' },
    { name: 'MIT World Peace University', slug: 'mitwpu-pune', type: 'Private', state: 'Maharashtra', city: 'Pune', location: 'Kothrud, Pune', establishedYear: 1983, affiliation: 'Private University', accreditation: JSON.stringify(['NAAC A+']), ranking: JSON.stringify({ nirf: '90-100' }), coursesOffered: JSON.stringify(['B.Tech', 'MBA', 'Design', 'Journalism']), averageFees: '4-6 Lakhs/year', placementRate: '85%', averagePackage: '6-7 LPA', facilities: JSON.stringify(['Hostel', 'Library', 'Sports', 'Cafeteria']), admissionProcess: 'MHT CET, MITWPU Entrance', cutoffs: JSON.stringify({ mhtCet: '90%ile' }), contactInfo: JSON.stringify({ phone: '+91-20-6700-1100', website: 'https://www.mitwpu.edu.in' }), officialWebsite: 'https://www.mitwpu.edu.in' },
    { name: 'Savitribai Phule Pune University', slug: 'sppu-pune', type: 'Government', state: 'Maharashtra', city: 'Pune', location: 'Ganeshkhind, Pune', establishedYear: 1949, affiliation: 'State University', accreditation: JSON.stringify(['NAAC A++']), ranking: JSON.stringify({ nirf: '23' }), coursesOffered: JSON.stringify(['BA', 'BSc', 'MA', 'MSc', 'PhD']), averageFees: '10,000-50,000/year', placementRate: '65%', averagePackage: '5 LPA', facilities: JSON.stringify(['Library', 'Research Centers']), admissionProcess: 'Merit/Entrance', cutoffs: JSON.stringify({ merit: '80-90%' }), contactInfo: JSON.stringify({ phone: '+91-20-2560-1001', website: 'http://www.unipune.ac.in' }), officialWebsite: 'http://www.unipune.ac.in' },
    { name: 'Pune Institute of Computer Technology', slug: 'pict-pune', type: 'Private', state: 'Maharashtra', city: 'Pune', location: 'Dhankawadi, Pune', establishedYear: 1983, affiliation: 'SPPU', accreditation: JSON.stringify(['NAAC A', 'NBA']), ranking: JSON.stringify({ nirf: '150-200' }), coursesOffered: JSON.stringify(['B.Tech', 'M.Tech', 'MCA']), averageFees: '1.5 Lakhs/year', placementRate: '92%', averagePackage: '9 LPA', facilities: JSON.stringify(['Hostel', 'Library', 'Labs', 'Cafeteria']), admissionProcess: 'MHT CET', cutoffs: JSON.stringify({ mhtCet: '97%ile' }), contactInfo: JSON.stringify({ phone: '+91-20-2437-1101', website: 'https://pict.edu' }), officialWebsite: 'https://pict.edu' },

    // KARNATAKA
    { name: 'Indian Institute of Science Bangalore', slug: 'iisc-bangalore', type: 'Government', state: 'Karnataka', city: 'Bangalore', location: 'Malleswaram, Bangalore', establishedYear: 1909, affiliation: 'Deemed University', accreditation: JSON.stringify(['NAAC A++']), ranking: JSON.stringify({ nirf: '1', qs: '225' }), coursesOffered: JSON.stringify(['M.Tech', 'PhD', 'Integrated PhD']), averageFees: '50,000-1 Lakh/year', placementRate: '95%', averagePackage: '20 LPA', facilities: JSON.stringify(['Hostel', 'Research Labs', 'Library']), admissionProcess: 'GATE, IIT JAM, KVPY', cutoffs: JSON.stringify({ gate: '700+' }), contactInfo: JSON.stringify({ phone: '+91-80-2293-2001', website: 'https://www.iisc.ac.in' }), officialWebsite: 'https://www.iisc.ac.in' },
    { name: 'National Institute of Technology Karnataka', slug: 'nitk-surathkal', type: 'Government', state: 'Karnataka', city: 'Surathkal', location: 'Surathkal, Mangalore', establishedYear: 1960, affiliation: 'Autonomous', accreditation: JSON.stringify(['NAAC A++']), ranking: JSON.stringify({ nirf: '13' }), coursesOffered: JSON.stringify(['B.Tech', 'M.Tech', 'MBA', 'PhD']), averageFees: '1.5 Lakhs/year', placementRate: '95%', averagePackage: '14 LPA', facilities: JSON.stringify(['Hostel', 'Library', 'Labs', 'Beach']), admissionProcess: 'JEE Main', cutoffs: JSON.stringify({ jeeMain: '1500-10000 rank' }), contactInfo: JSON.stringify({ phone: '+91-824-247-3770', website: 'https://www.nitk.ac.in' }), officialWebsite: 'https://www.nitk.ac.in' },
    { name: 'PES University', slug: 'pes-bangalore', type: 'Private', state: 'Karnataka', city: 'Bangalore', location: 'Electronic City, Bangalore', establishedYear: 1988, affiliation: 'Private University', accreditation: JSON.stringify(['NAAC A++']), ranking: JSON.stringify({ nirf: '97' }), coursesOffered: JSON.stringify(['B.Tech', 'M.Tech', 'MBA', 'MCA']), averageFees: '4-5 Lakhs/year', placementRate: '95%', averagePackage: '10 LPA', facilities: JSON.stringify(['Hostel', 'Library', 'Labs', 'Innovation Center']), admissionProcess: 'PESSAT, JEE Main, KCET', cutoffs: JSON.stringify({ pessat: '80%' }), contactInfo: JSON.stringify({ phone: '+91-80-2672-7000', website: 'https://pes.edu' }), officialWebsite: 'https://pes.edu' },
    { name: 'RV College of Engineering', slug: 'rvce-bangalore', type: 'Private', state: 'Karnataka', city: 'Bangalore', location: 'Mysore Road, Bangalore', establishedYear: 1963, affiliation: 'VTU', accreditation: JSON.stringify(['NAAC A++', 'NBA']), ranking: JSON.stringify({ nirf: '78' }), coursesOffered: JSON.stringify(['B.E', 'M.Tech']), averageFees: '2.5 Lakhs/year', placementRate: '92%', averagePackage: '8 LPA', facilities: JSON.stringify(['Hostel', 'Library', 'Labs']), admissionProcess: 'KCET, COMEDK', cutoffs: JSON.stringify({ kcet: '500-2000 rank' }), contactInfo: JSON.stringify({ phone: '+91-80-2867-2641', website: 'https://www.rvce.edu.in' }), officialWebsite: 'https://www.rvce.edu.in' },
    { name: 'BMS College of Engineering', slug: 'bmsce-bangalore', type: 'Private', state: 'Karnataka', city: 'Bangalore', location: 'Basavanagudi, Bangalore', establishedYear: 1946, affiliation: 'VTU', accreditation: JSON.stringify(['NAAC A++', 'NBA']), ranking: JSON.stringify({ nirf: '89' }), coursesOffered: JSON.stringify(['B.E', 'M.Tech', 'MBA']), averageFees: '2 Lakhs/year', placementRate: '90%', averagePackage: '7.5 LPA', facilities: JSON.stringify(['Hostel', 'Library', 'Labs', 'Sports']), admissionProcess: 'KCET, COMEDK', cutoffs: JSON.stringify({ kcet: '1000-3000 rank' }), contactInfo: JSON.stringify({ phone: '+91-80-2662-1425', website: 'https://www.bmsce.ac.in' }), officialWebsite: 'https://www.bmsce.ac.in' },
    { name: 'Ramaiah Institute of Technology', slug: 'msrit-bangalore', type: 'Private', state: 'Karnataka', city: 'Bangalore', location: 'MSR Nagar, Bangalore', establishedYear: 1962, affiliation: 'VTU', accreditation: JSON.stringify(['NAAC A++', 'NBA']), ranking: JSON.stringify({ nirf: '101' }), coursesOffered: JSON.stringify(['B.E', 'M.Tech', 'MCA']), averageFees: '2.5 Lakhs/year', placementRate: '91%', averagePackage: '8 LPA', facilities: JSON.stringify(['Hostel', 'Library', 'Labs', 'Sports']), admissionProcess: 'KCET, COMEDK', cutoffs: JSON.stringify({ kcet: '800-2500 rank' }), contactInfo: JSON.stringify({ phone: '+91-80-2360-0822', website: 'https://www.msrit.edu' }), officialWebsite: 'https://www.msrit.edu' },
    { name: 'Manipal Institute of Technology', slug: 'mit-manipal', type: 'Deemed', state: 'Karnataka', city: 'Manipal', location: 'Manipal, Udupi', establishedYear: 1957, affiliation: 'Deemed University', accreditation: JSON.stringify(['NAAC A++']), ranking: JSON.stringify({ nirf: '45' }), coursesOffered: JSON.stringify(['B.Tech', 'M.Tech', 'MBA']), averageFees: '5-7 Lakhs/year', placementRate: '88%', averagePackage: '7 LPA', facilities: JSON.stringify(['Hostel', 'Library', 'Labs', 'Hospital']), admissionProcess: 'MET', cutoffs: JSON.stringify({ met: '80%' }), contactInfo: JSON.stringify({ phone: '+91-820-292-3000', website: 'https://manipal.edu/mit.html' }), officialWebsite: 'https://manipal.edu/mit.html' },
    { name: 'Christ University', slug: 'christ-bangalore', type: 'Deemed', state: 'Karnataka', city: 'Bangalore', location: 'Hosur Road, Bangalore', establishedYear: 1969, affiliation: 'Deemed University', accreditation: JSON.stringify(['NAAC A++']), ranking: JSON.stringify({ nirf: '19' }), coursesOffered: JSON.stringify(['BA', 'BSc', 'BBA', 'MBA', 'Engineering']), averageFees: '2-5 Lakhs/year', placementRate: '85%', averagePackage: '6 LPA', facilities: JSON.stringify(['Hostel', 'Library', 'Sports', 'Chapel']), admissionProcess: 'Christ University Entrance', cutoffs: JSON.stringify({ entrance: '75%' }), contactInfo: JSON.stringify({ phone: '+91-80-4012-9292', website: 'https://christuniversity.in' }), officialWebsite: 'https://christuniversity.in' },

    // TAMIL NADU
    { name: 'Indian Institute of Technology Madras', slug: 'iit-madras', type: 'Government', state: 'Tamil Nadu', city: 'Chennai', location: 'Adyar, Chennai', establishedYear: 1959, affiliation: 'Autonomous', accreditation: JSON.stringify(['NAAC A++']), ranking: JSON.stringify({ nirf: '1', qs: '285' }), coursesOffered: JSON.stringify(['B.Tech', 'M.Tech', 'MBA', 'PhD']), averageFees: '2-3 Lakhs/year', placementRate: '97%', averagePackage: '20 LPA', facilities: JSON.stringify(['Hostel', 'Library', 'Research Park', 'Sports']), admissionProcess: 'JEE Advanced', cutoffs: JSON.stringify({ jeeAdvanced: '50-400 rank' }), contactInfo: JSON.stringify({ phone: '+91-44-2257-4896', website: 'https://www.iitm.ac.in' }), officialWebsite: 'https://www.iitm.ac.in' },
    { name: 'Anna University', slug: 'anna-university-chennai', type: 'Government', state: 'Tamil Nadu', city: 'Chennai', location: 'Guindy, Chennai', establishedYear: 1978, affiliation: 'State University', accreditation: JSON.stringify(['NAAC A++']), ranking: JSON.stringify({ nirf: '14' }), coursesOffered: JSON.stringify(['B.E', 'B.Tech', 'M.E', 'M.Tech', 'MBA']), averageFees: '50,000-1 Lakh/year', placementRate: '80%', averagePackage: '6 LPA', facilities: JSON.stringify(['Library', 'Labs', 'Research Centers']), admissionProcess: 'TNEA Counselling', cutoffs: JSON.stringify({ tnea: '190-200' }), contactInfo: JSON.stringify({ phone: '+91-44-2235-8700', website: 'https://www.annauniv.edu' }), officialWebsite: 'https://www.annauniv.edu' },
    { name: 'National Institute of Technology Tiruchirappalli', slug: 'nit-trichy', type: 'Government', state: 'Tamil Nadu', city: 'Tiruchirappalli', location: 'Tiruchirappalli', establishedYear: 1964, affiliation: 'Autonomous', accreditation: JSON.stringify(['NAAC A++']), ranking: JSON.stringify({ nirf: '9' }), coursesOffered: JSON.stringify(['B.Tech', 'M.Tech', 'MBA', 'MSc']), averageFees: '1.5 Lakhs/year', placementRate: '96%', averagePackage: '13 LPA', facilities: JSON.stringify(['Hostel', 'Library', 'Labs', 'Sports']), admissionProcess: 'JEE Main', cutoffs: JSON.stringify({ jeeMain: '500-8000 rank' }), contactInfo: JSON.stringify({ phone: '+91-431-250-1801', website: 'https://www.nitt.edu' }), officialWebsite: 'https://www.nitt.edu' },
    { name: 'VIT University', slug: 'vit-vellore', type: 'Deemed', state: 'Tamil Nadu', city: 'Vellore', location: 'Vellore', establishedYear: 1984, affiliation: 'Deemed University', accreditation: JSON.stringify(['NAAC A++']), ranking: JSON.stringify({ nirf: '11' }), coursesOffered: JSON.stringify(['B.Tech', 'M.Tech', 'MBA', 'Integrated Programs']), averageFees: '4-5 Lakhs/year', placementRate: '94%', averagePackage: '7.5 LPA', facilities: JSON.stringify(['Hostel', 'Library', 'Labs', 'Sports Complex']), admissionProcess: 'VITEEE', cutoffs: JSON.stringify({ viteee: '10000-40000 rank' }), contactInfo: JSON.stringify({ phone: '+91-416-220-2020', website: 'https://vit.ac.in' }), officialWebsite: 'https://vit.ac.in' },
    { name: 'PSG College of Technology', slug: 'psg-coimbatore', type: 'Private', state: 'Tamil Nadu', city: 'Coimbatore', location: 'Avinashi Road, Coimbatore', establishedYear: 1951, affiliation: 'Anna University', accreditation: JSON.stringify(['NAAC A++', 'NBA']), ranking: JSON.stringify({ nirf: '52' }), coursesOffered: JSON.stringify(['B.E', 'B.Tech', 'M.E', 'MBA']), averageFees: '1.5 Lakhs/year', placementRate: '90%', averagePackage: '6.5 LPA', facilities: JSON.stringify(['Hostel', 'Library', 'Labs']), admissionProcess: 'TNEA', cutoffs: JSON.stringify({ tnea: '195+' }), contactInfo: JSON.stringify({ phone: '+91-422-257-2177', website: 'https://www.psgtech.edu' }), officialWebsite: 'https://www.psgtech.edu' },
    { name: 'SRM Institute of Science and Technology', slug: 'srm-chennai', type: 'Deemed', state: 'Tamil Nadu', city: 'Chennai', location: 'Kattankulathur, Chennai', establishedYear: 1985, affiliation: 'Deemed University', accreditation: JSON.stringify(['NAAC A++']), ranking: JSON.stringify({ nirf: '29' }), coursesOffered: JSON.stringify(['B.Tech', 'M.Tech', 'MBA', 'Medical']), averageFees: '3-5 Lakhs/year', placementRate: '88%', averagePackage: '6 LPA', facilities: JSON.stringify(['Hostel', 'Library', 'Hospital', 'Sports']), admissionProcess: 'SRMJEEE', cutoffs: JSON.stringify({ srmjeee: '70%' }), contactInfo: JSON.stringify({ phone: '+91-44-2741-7000', website: 'https://www.srmist.edu.in' }), officialWebsite: 'https://www.srmist.edu.in' },
    { name: 'Thiagarajar College of Engineering', slug: 'tce-madurai', type: 'Private', state: 'Tamil Nadu', city: 'Madurai', location: 'Madurai', establishedYear: 1957, affiliation: 'Anna University', accreditation: JSON.stringify(['NAAC A+', 'NBA']), ranking: JSON.stringify({ nirf: '110' }), coursesOffered: JSON.stringify(['B.E', 'M.E', 'MBA']), averageFees: '1 Lakh/year', placementRate: '85%', averagePackage: '5 LPA', facilities: JSON.stringify(['Hostel', 'Library', 'Labs']), admissionProcess: 'TNEA', cutoffs: JSON.stringify({ tnea: '188+' }), contactInfo: JSON.stringify({ phone: '+91-452-248-2240', website: 'https://www.tce.edu' }), officialWebsite: 'https://www.tce.edu' },

    // GUJARAT
    { name: 'Indian Institute of Technology Gandhinagar', slug: 'iit-gandhinagar', type: 'Government', state: 'Gujarat', city: 'Gandhinagar', location: 'Palaj, Gandhinagar', establishedYear: 2008, affiliation: 'Autonomous', accreditation: JSON.stringify(['NAAC A++']), ranking: JSON.stringify({ nirf: '30' }), coursesOffered: JSON.stringify(['B.Tech', 'M.Tech', 'PhD', 'MSc']), averageFees: '2-3 Lakhs/year', placementRate: '95%', averagePackage: '16 LPA', facilities: JSON.stringify(['Hostel', 'Library', 'Labs', 'Sports']), admissionProcess: 'JEE Advanced', cutoffs: JSON.stringify({ jeeAdvanced: '2000-5000 rank' }), contactInfo: JSON.stringify({ phone: '+91-79-2395-2005', website: 'https://www.iitgn.ac.in' }), officialWebsite: 'https://www.iitgn.ac.in' },
    { name: 'Nirma University', slug: 'nirma-ahmedabad', type: 'Private', state: 'Gujarat', city: 'Ahmedabad', location: 'SG Highway, Ahmedabad', establishedYear: 2003, affiliation: 'Private University', accreditation: JSON.stringify(['NAAC A++']), ranking: JSON.stringify({ nirf: '76' }), coursesOffered: JSON.stringify(['B.Tech', 'MBA', 'Law', 'Pharmacy']), averageFees: '3-5 Lakhs/year', placementRate: '92%', averagePackage: '8 LPA', facilities: JSON.stringify(['Hostel', 'Library', 'Sports', 'Campus']), admissionProcess: 'JEE Main, GUJCET', cutoffs: JSON.stringify({ jeeMain: '20000-50000 rank' }), contactInfo: JSON.stringify({ phone: '+91-2717-241901', website: 'https://nirmauni.ac.in' }), officialWebsite: 'https://nirmauni.ac.in' },
    { name: 'Dhirubhai Ambani Institute of ICT', slug: 'da-iict-gandhinagar', type: 'Government', state: 'Gujarat', city: 'Gandhinagar', location: 'Gandhinagar', establishedYear: 2001, affiliation: 'State University', accreditation: JSON.stringify(['NAAC A+']), ranking: JSON.stringify({ nirf: '65' }), coursesOffered: JSON.stringify(['B.Tech ICT', 'M.Tech', 'PhD']), averageFees: '2 Lakhs/year', placementRate: '98%', averagePackage: '12 LPA', facilities: JSON.stringify(['Hostel', 'Library', 'Labs']), admissionProcess: 'JEE Main', cutoffs: JSON.stringify({ jeeMain: '5000-15000 rank' }), contactInfo: JSON.stringify({ phone: '+91-79-3051-8400', website: 'https://www.daiict.ac.in' }), officialWebsite: 'https://www.daiict.ac.in' },
    { name: 'Sardar Vallabhbhai National Institute of Technology', slug: 'svnit-surat', type: 'Government', state: 'Gujarat', city: 'Surat', location: 'Ichchhanath, Surat', establishedYear: 1961, affiliation: 'Autonomous', accreditation: JSON.stringify(['NAAC A++']), ranking: JSON.stringify({ nirf: '60' }), coursesOffered: JSON.stringify(['B.Tech', 'M.Tech', 'MSc', 'PhD']), averageFees: '1.5 Lakhs/year', placementRate: '94%', averagePackage: '11 LPA', facilities: JSON.stringify(['Hostel', 'Library', 'Labs', 'Sports']), admissionProcess: 'JEE Main', cutoffs: JSON.stringify({ jeeMain: '4000-20000 rank' }), contactInfo: JSON.stringify({ phone: '+91-261-220-1601', website: 'https://www.svnit.ac.in' }), officialWebsite: 'https://www.svnit.ac.in' },
    { name: 'Institute of Infrastructure Technology Research and Management', slug: 'iitram-ahmedabad', type: 'Government', state: 'Gujarat', city: 'Ahmedabad', location: 'Ahmedabad', establishedYear: 2010, affiliation: 'Autonomous', accreditation: JSON.stringify(['NBA']), ranking: JSON.stringify({ nirf: '150+' }), coursesOffered: JSON.stringify(['B.Tech', 'M.Tech', 'PhD']), averageFees: '1.5 Lakhs/year', placementRate: '88%', averagePackage: '7 LPA', facilities: JSON.stringify(['Hostel', 'Library', 'Labs']), admissionProcess: 'JEE Main, GUJCET', cutoffs: JSON.stringify({ jeeMain: '25000+' }), contactInfo: JSON.stringify({ phone: '+91-79-2697-4005', website: 'https://www.iitram.ac.in' }), officialWebsite: 'https://www.iitram.ac.in' },
    { name: 'LD College of Engineering', slug: 'ldce-ahmedabad', type: 'Government', state: 'Gujarat', city: 'Ahmedabad', location: 'Gujarat University Campus', establishedYear: 1948, affiliation: 'Gujarat Technological University', accreditation: JSON.stringify(['NAAC A+', 'NBA']), ranking: JSON.stringify({ nirf: '200+' }), coursesOffered: JSON.stringify(['B.E', 'M.E']), averageFees: '50,000-1 Lakh/year', placementRate: '82%', averagePackage: '5 LPA', facilities: JSON.stringify(['Library', 'Labs', 'Campus']), admissionProcess: 'GUJCET, JEE Main', cutoffs: JSON.stringify({ gujcet: '80%' }), contactInfo: JSON.stringify({ phone: '+91-79-2630-2000', website: 'https://www.ldce.ac.in' }), officialWebsite: 'https://www.ldce.ac.in' },

    // WEST BENGAL
    { name: 'Indian Institute of Technology Kharagpur', slug: 'iit-kharagpur', type: 'Government', state: 'West Bengal', city: 'Kharagpur', location: 'Kharagpur', establishedYear: 1951, affiliation: 'Autonomous', accreditation: JSON.stringify(['NAAC A++']), ranking: JSON.stringify({ nirf: '5', qs: '271' }), coursesOffered: JSON.stringify(['B.Tech', 'M.Tech', 'MBA', 'PhD', 'Medical']), averageFees: '2-3 Lakhs/year', placementRate: '95%', averagePackage: '19 LPA', facilities: JSON.stringify(['Hostel', 'Library', 'Hospital', 'Sports Complex']), admissionProcess: 'JEE Advanced', cutoffs: JSON.stringify({ jeeAdvanced: '200-2000 rank' }), contactInfo: JSON.stringify({ phone: '+91-3222-255221', website: 'http://www.iitkgp.ac.in' }), officialWebsite: 'http://www.iitkgp.ac.in' },
    { name: 'Jadavpur University', slug: 'jadavpur-kolkata', type: 'Government', state: 'West Bengal', city: 'Kolkata', location: 'Jadavpur, Kolkata', establishedYear: 1955, affiliation: 'State University', accreditation: JSON.stringify(['NAAC A++']), ranking: JSON.stringify({ nirf: '12' }), coursesOffered: JSON.stringify(['B.E', 'M.E', 'MA', 'MSc', 'PhD']), averageFees: '10,000-50,000/year', placementRate: '90%', averagePackage: '10 LPA', facilities: JSON.stringify(['Hostel', 'Library', 'Labs']), admissionProcess: 'WBJEE, JECA', cutoffs: JSON.stringify({ wbjee: '500-2000 rank' }), contactInfo: JSON.stringify({ phone: '+91-33-2414-6890', website: 'http://www.jaduniv.edu.in' }), officialWebsite: 'http://www.jaduniv.edu.in' },
    { name: 'National Institute of Technology Durgapur', slug: 'nit-durgapur', type: 'Government', state: 'West Bengal', city: 'Durgapur', location: 'Durgapur', establishedYear: 1960, affiliation: 'Autonomous', accreditation: JSON.stringify(['NAAC A++']), ranking: JSON.stringify({ nirf: '90' }), coursesOffered: JSON.stringify(['B.Tech', 'M.Tech', 'MBA', 'MSc']), averageFees: '1.5 Lakhs/year', placementRate: '88%', averagePackage: '9 LPA', facilities: JSON.stringify(['Hostel', 'Library', 'Labs', 'Sports']), admissionProcess: 'JEE Main', cutoffs: JSON.stringify({ jeeMain: '10000-40000 rank' }), contactInfo: JSON.stringify({ phone: '+91-343-254-7375', website: 'https://nitdgp.ac.in' }), officialWebsite: 'https://nitdgp.ac.in' },
    { name: 'Calcutta University', slug: 'calcutta-university', type: 'Government', state: 'West Bengal', city: 'Kolkata', location: 'College Street, Kolkata', establishedYear: 1857, affiliation: 'State University', accreditation: JSON.stringify(['NAAC A++']), ranking: JSON.stringify({ nirf: '18' }), coursesOffered: JSON.stringify(['BA', 'BSc', 'MA', 'MSc', 'PhD']), averageFees: '5,000-30,000/year', placementRate: '65%', averagePackage: '5 LPA', facilities: JSON.stringify(['Library', 'Research Centers', 'Museum']), admissionProcess: 'Merit Based', cutoffs: JSON.stringify({ merit: '75-90%' }), contactInfo: JSON.stringify({ phone: '+91-33-2241-0071', website: 'https://www.caluniv.ac.in' }), officialWebsite: 'https://www.caluniv.ac.in' },
    { name: 'Heritage Institute of Technology', slug: 'heritage-kolkata', type: 'Private', state: 'West Bengal', city: 'Kolkata', location: 'Anandapur, Kolkata', establishedYear: 2001, affiliation: 'MAKAUT', accreditation: JSON.stringify(['NAAC A', 'NBA']), ranking: JSON.stringify({ nirf: '150-200' }), coursesOffered: JSON.stringify(['B.Tech', 'M.Tech', 'MBA']), averageFees: '1.5-2 Lakhs/year', placementRate: '85%', averagePackage: '6 LPA', facilities: JSON.stringify(['Hostel', 'Library', 'Labs', 'Cafeteria']), admissionProcess: 'WBJEE, JEE Main', cutoffs: JSON.stringify({ wbjee: '5000+' }), contactInfo: JSON.stringify({ phone: '+91-33-2449-7148', website: 'https://heritageit.edu' }), officialWebsite: 'https://heritageit.edu' },
    { name: 'Techno India University', slug: 'techno-india-kolkata', type: 'Private', state: 'West Bengal', city: 'Kolkata', location: 'Salt Lake, Kolkata', establishedYear: 2012, affiliation: 'Private University', accreditation: JSON.stringify(['NAAC A']), ranking: JSON.stringify({ nirf: '200+' }), coursesOffered: JSON.stringify(['B.Tech', 'MBA', 'MCA', 'BBA']), averageFees: '2-3 Lakhs/year', placementRate: '80%', averagePackage: '5 LPA', facilities: JSON.stringify(['Hostel', 'Library', 'Labs', 'Sports']), admissionProcess: 'WBJEE, University Entrance', cutoffs: JSON.stringify({ entrance: '70%' }), contactInfo: JSON.stringify({ phone: '+91-33-6628-1000', website: 'https://www.technoindiauniversity.ac.in' }), officialWebsite: 'https://www.technoindiauniversity.ac.in' },
  ]

  console.log(`Creating ${colleges.length} colleges...`)
  for (const college of colleges) {
    await prisma.college.create({ data: college })
  }
  console.log(`✅ ${colleges.length} colleges created`)

  // ====================
  // EXAMS DATA
  // ====================
  const exams = [
    // ENGINEERING
    { name: 'JEE Main', slug: 'jee-main', fullName: 'Joint Entrance Examination Main', type: 'Entrance', category: 'Engineering', conductedBy: 'National Testing Agency (NTA)', examLevel: 'National', description: 'National level engineering entrance exam for admission to NITs, IIITs, and other centrally funded technical institutions', eligibility: JSON.stringify(['12th with PCM', 'Minimum 75% marks (65% for SC/ST)', 'Age limit: No upper age limit']), examPattern: JSON.stringify({ mode: 'Computer Based Test', papers: 'Paper 1 (B.E/B.Tech), Paper 2 (B.Arch/B.Planning)', duration: '3 hours', sections: 'Physics (30Q), Chemistry (30Q), Mathematics (30Q)', marking: '+4 for correct, -1 for incorrect' }), syllabus: JSON.stringify(['Physics: Mechanics, Thermodynamics, Electromagnetism', 'Chemistry: Physical, Organic, Inorganic', 'Mathematics: Algebra, Calculus, Trigonometry, Coordinate Geometry']), applicationFee: '₹1000 (General), ₹500 (SC/ST/PwD)', importantDates: JSON.stringify({ registration: 'December-January', exam: 'January & April (2 sessions)', result: 'February & May' }), officialWebsite: 'https://jeemain.nta.nic.in', preparationTips: JSON.stringify(['Focus on NCERT textbooks', 'Practice previous year papers', 'Take regular mock tests', 'Time management is crucial']), relatedCourses: JSON.stringify(['B.Tech/B.E in various branches']), relatedCareers: JSON.stringify(['Software Engineer', 'Mechanical Engineer', 'Civil Engineer']) },
    
    { name: 'JEE Advanced', slug: 'jee-advanced', fullName: 'Joint Entrance Examination Advanced', type: 'Entrance', category: 'Engineering', conductedBy: 'IIT (Rotational)', examLevel: 'National', description: 'Gateway to IITs (Indian Institutes of Technology). Top 2.5 lakh JEE Main qualifiers are eligible', eligibility: JSON.stringify(['Qualified JEE Main with top 2.5 lakh rank', 'Maximum 2 consecutive attempts', 'Age limit: Must be born on or after October 1, 1999 (5 year relaxation for SC/ST/PwD)']), examPattern: JSON.stringify({ mode: 'Computer Based Test', papers: 'Paper 1 and Paper 2 (Both compulsory)', duration: '3 hours each paper', sections: 'Physics, Chemistry, Mathematics', marking: 'Variable marking scheme with partial marking' }), syllabus: JSON.stringify(['Advanced topics in PCM', 'Based on Class 11 and 12 syllabus', 'More conceptual and application-based']), applicationFee: '₹2800 (General), ₹1400 (Female/SC/ST/PwD)', importantDates: JSON.stringify({ registration: 'May', exam: 'Late May/Early June', result: 'Mid June' }), officialWebsite: 'https://jeeadv.ac.in', preparationTips: JSON.stringify(['Master JEE Main concepts first', 'Solve IIT-level problems', 'Focus on conceptual clarity', 'Practice time-bound tests']), relatedCourses: JSON.stringify(['B.Tech at IITs']), relatedCareers: JSON.stringify(['Research Scientist', 'Software Engineer', 'Entrepreneur']) },
    
    { name: 'BITSAT', slug: 'bitsat', fullName: 'Birla Institute of Technology and Science Admission Test', type: 'Entrance', category: 'Engineering', conductedBy: 'BITS Pilani', examLevel: 'University', description: 'Online test for admission to integrated first degree programmes at BITS campuses in Pilani, Goa, and Hyderabad', eligibility: JSON.stringify(['12th with PCM', 'Minimum 75% aggregate in PCM', 'Minimum 60% in each subject']), examPattern: JSON.stringify({ mode: 'Computer Based Test', duration: '3 hours', sections: 'Physics (40Q), Chemistry (40Q), Maths/Biology (45Q), English & Logical Reasoning (15Q)', totalQuestions: 150, marking: '+3 for correct, -1 for incorrect' }), syllabus: JSON.stringify(['Class 11 and 12 PCM syllabus', 'English Proficiency', 'Logical Reasoning']), applicationFee: '₹3400 (Male), ₹2900 (Female)', importantDates: JSON.stringify({ registration: 'January-March', exam: 'May-June', result: 'June' }), officialWebsite: 'https://www.bitsadmission.com', preparationTips: JSON.stringify(['Speed and accuracy are crucial', 'Practice on computer', 'Time management for 150 questions', 'Strong in basics of PCM']), relatedCourses: JSON.stringify(['B.E (Hons.) at BITS']), relatedCareers: JSON.stringify(['Software Engineer', 'Data Scientist', 'Product Manager']) },
    
    { name: 'MHT CET', slug: 'mht-cet', fullName: 'Maharashtra Common Entrance Test', type: 'Entrance', category: 'Engineering', conductedBy: 'State Common Entrance Test Cell, Maharashtra', examLevel: 'State', description: 'State level entrance exam for engineering and pharmacy colleges in Maharashtra', eligibility: JSON.stringify(['12th with PCM/PCB', 'Domicile of Maharashtra or All India', 'No age limit']), examPattern: JSON.stringify({ mode: 'Computer Based Test', papers: 'PCM for Engineering, PCB for Pharmacy/Agriculture', duration: '90 minutes per paper', questions: '50 per subject', marking: '+1 for correct, 0 for incorrect' }), syllabus: JSON.stringify(['Physics: Class 11 and 12', 'Chemistry: Class 11 and 12', 'Mathematics: Class 11 and 12']), applicationFee: '₹800 (General), ₹600 (Reserved)', importantDates: JSON.stringify({ registration: 'February-March', exam: 'May', result: 'June', counselling: 'June-July' }), officialWebsite: 'https://cetcell.mahacet.org', preparationTips: JSON.stringify(['Focus on Maharashtra board textbooks', 'Practice speed', 'Previous year papers important', '90 minutes for 50 questions']), relatedCourses: JSON.stringify(['B.Tech/B.E in Maharashtra']), relatedCareers: JSON.stringify(['Engineering careers']) },
    
    { name: 'VITEEE', slug: 'viteee', fullName: 'VIT Engineering Entrance Examination', type: 'Entrance', category: 'Engineering', conductedBy: 'VIT University', examLevel: 'University', description: 'University level entrance exam for admission to B.Tech programs at VIT campuses', eligibility: JSON.stringify(['12th with PCM/PCB', 'Minimum 60% aggregate in PCM', 'English as compulsory subject']), examPattern: JSON.stringify({ mode: 'Computer Based Test', duration: '2.5 hours', sections: 'Physics (35Q), Chemistry (35Q), Maths/Biology (40Q), English (5Q), Aptitude (10Q)', marking: '+1 for correct, 0 for incorrect' }), syllabus: JSON.stringify(['NCERT Class 11 and 12 syllabus', 'Physics, Chemistry, Mathematics', 'English and Aptitude']), applicationFee: '₹1150 (One slot), ₹1550 (Two slots)', importantDates: JSON.stringify({ registration: 'October-February', exam: 'April-May', result: 'May-June' }), officialWebsite: 'https://vit.ac.in/admissions/viteee', preparationTips: JSON.stringify(['NCERT focused preparation', 'Good speed required', 'Practice mock tests', 'English and Aptitude carry less weight']), relatedCourses: JSON.stringify(['B.Tech at VIT']), relatedCareers: JSON.stringify(['Software Development', 'Core Engineering']) },
    
    { name: 'COMEDK', slug: 'comedk', fullName: 'Consortium of Medical Engineering and Dental Colleges of Karnataka', type: 'Entrance', category: 'Engineering', conductedBy: 'COMEDK', examLevel: 'State', description: 'State level entrance exam for private engineering and medical colleges in Karnataka', eligibility: JSON.stringify(['12th with PCM', 'Minimum 45% in PCM individually', 'Domicile: Any state']), examPattern: JSON.stringify({ mode: 'Offline OMR based', duration: '3 hours', sections: 'Physics (60Q), Chemistry (60Q), Mathematics (60Q)', marking: '+1 for correct, 0 for incorrect' }), syllabus: JSON.stringify(['Class 11 and 12 PCM', 'Karnataka state board syllabus preferred']), applicationFee: '₹1800', importantDates: JSON.stringify({ registration: 'March-April', exam: 'May', result: 'May-June' }), officialWebsite: 'https://www.comedk.org', preparationTips: JSON.stringify(['Karnataka board textbooks helpful', 'Practice sample papers', 'Time management crucial', 'No negative marking advantage']), relatedCourses: JSON.stringify(['B.E in Karnataka private colleges']), relatedCareers: JSON.stringify(['Engineering careers']) },
    
    { name: 'WBJEE', slug: 'wbjee', fullName: 'West Bengal Joint Entrance Examination', type: 'Entrance', category: 'Engineering', conductedBy: 'WBJEEB', examLevel: 'State', description: 'State level entrance exam for engineering and architecture colleges in West Bengal', eligibility: JSON.stringify(['12th with PCM', 'Domicile of West Bengal or All India']), examPattern: JSON.stringify({ mode: 'Offline OMR based', papers: 'Paper I (Maths), Paper II (Physics & Chemistry)', duration: '2 hours each', marking: 'Category-wise marks per question' }), syllabus: JSON.stringify(['Class 11 and 12 PCM', 'West Bengal board syllabus']), applicationFee: '₹500 (General), ₹400 (Reserved)', importantDates: JSON.stringify({ registration: 'February-March', exam: 'April', result: 'May', counselling: 'June-July' }), officialWebsite: 'https://wbjeeb.nic.in', preparationTips: JSON.stringify(['Focus on state board syllabus', 'Practice previous year papers', 'Mathematics has more weightage']), relatedCourses: JSON.stringify(['B.Tech/B.E in West Bengal']), relatedCareers: JSON.stringify(['Engineering careers']) },
    
    { name: 'KCET', slug: 'kcet', fullName: 'Karnataka Common Entrance Test', type: 'Entrance', category: 'Engineering', conductedBy: 'Karnataka Examinations Authority', examLevel: 'State', description: 'State level entrance exam for engineering and other professional courses in Karnataka', eligibility: JSON.stringify(['12th with PCM/PCB', 'Domicile of Karnataka preferred']), examPattern: JSON.stringify({ mode: 'Offline OMR based', duration: '80 minutes per subject', sections: 'Physics (60Q), Chemistry (60Q), Mathematics (60Q)', marking: '+1 for correct, 0 for incorrect' }), syllabus: JSON.stringify(['Class 11 and 12 syllabus', 'Karnataka state board focused']), applicationFee: '₹500-650', importantDates: JSON.stringify({ registration: 'February-March', exam: 'April-May', result: 'May', counselling: 'June-July' }), officialWebsite: 'https://cetonline.karnataka.gov.in/kea', preparationTips: JSON.stringify(['Karnataka board textbooks', 'Time management', 'Previous year papers']), relatedCourses: JSON.stringify(['B.E in Karnataka']), relatedCareers: JSON.stringify(['Engineering careers']) },
    
    { name: 'GUJCET', slug: 'gujcet', fullName: 'Gujarat Common Entrance Test', type: 'Entrance', category: 'Engineering', conductedBy: 'GSEB', examLevel: 'State', description: 'State level entrance exam for engineering and pharmacy colleges in Gujarat', eligibility: JSON.stringify(['12th with PCM/PCB', 'Domicile of Gujarat']), examPattern: JSON.stringify({ mode: 'Offline OMR based', papers: 'PCM for Engineering', duration: '3 hours', marking: '+1 for correct, 0 for incorrect' }), syllabus: JSON.stringify(['Class 11 and 12 syllabus', 'Gujarat board syllabus']), applicationFee: '₹350 (General), ₹175 (SC/ST)', importantDates: JSON.stringify({ registration: 'March-April', exam: 'April-May', result: 'May-June' }), officialWebsite: 'https://gujcet.gseb.org', preparationTips: JSON.stringify(['Gujarat board textbooks', 'Practice speed', 'Mock tests important']), relatedCourses: JSON.stringify(['B.E/B.Tech in Gujarat']), relatedCareers: JSON.stringify(['Engineering careers']) },
    
    { name: 'GATE', slug: 'gate', fullName: 'Graduate Aptitude Test in Engineering', type: 'Entrance', category: 'Engineering', conductedBy: 'IITs/IISc (Rotational)', examLevel: 'National', description: 'National level exam for M.Tech admissions and PSU recruitment', eligibility: JSON.stringify(['B.E/B.Tech or equivalent (final year students eligible)', '27 different papers across disciplines']), examPattern: JSON.stringify({ mode: 'Computer Based Test', duration: '3 hours', sections: 'General Aptitude (15 marks), Core Subject (85 marks)', totalMarks: 100, marking: 'Variable for different question types' }), syllabus: JSON.stringify(['Engineering Mathematics', 'Core subject topics (varies by paper)', 'General Aptitude']), applicationFee: '₹1700 (General), ₹900 (SC/ST/PwD)', importantDates: JSON.stringify({ registration: 'August-September', exam: 'February', result: 'March', counselling: 'March-April' }), officialWebsite: 'https://gate.iisc.ac.in', preparationTips: JSON.stringify(['Start early (6-8 months)', 'Focus on fundamentals', 'Previous year analysis', 'Mock tests regularly', 'Formula sheets important']), relatedCourses: JSON.stringify(['M.Tech/ME at IITs, NITs, IIITs']), relatedCareers: JSON.stringify(['Research & Development', 'Higher Education', 'PSU Jobs']) },

    // MEDICAL
    { name: 'NEET UG', slug: 'neet-ug', fullName: 'National Eligibility cum Entrance Test Undergraduate', type: 'Entrance', category: 'Medical', conductedBy: 'National Testing Agency (NTA)', examLevel: 'National', description: 'Single national level entrance exam for MBBS and BDS admissions in India', eligibility: JSON.stringify(['12th with PCB', 'Minimum 50% in PCB (40% for SC/ST/OBC)', 'Age: Minimum 17 years, Maximum 25 years (30 for SC/ST/OBC)', 'English is mandatory']), examPattern: JSON.stringify({ mode: 'Offline OMR based', duration: '3 hours 20 minutes', sections: 'Physics (50Q), Chemistry (50Q), Biology (100Q - 50 Botany + 50 Zoology)', totalQuestions: 200, totalMarks: 720, marking: '+4 for correct, -1 for incorrect' }), syllabus: JSON.stringify(['Physics: Class 11 and 12', 'Chemistry: Class 11 and 12', 'Biology: Class 11 and 12 (Botany + Zoology)']), applicationFee: '₹1700 (General/OBC), ₹1600 (SC/ST/PwD), ₹1000 (Outside India)', importantDates: JSON.stringify({ registration: 'February-March', exam: 'Early May', result: 'June', counselling: 'MCC - July onwards' }), officialWebsite: 'https://neet.nta.nic.in', preparationTips: JSON.stringify(['NCERT is the bible for NEET', '2-3 years preparation ideal', 'Focus on Biology (50% weightage)', 'Previous 10 years papers', 'Daily revision crucial', 'Mock tests weekly']), relatedCourses: JSON.stringify(['MBBS', 'BDS', 'BAMS', 'BHMS', 'BUMS', 'BVSc', 'Nursing']), relatedCareers: JSON.stringify(['Doctor', 'Surgeon', 'Dentist', 'Medical Research']) },
    
    { name: 'NEET PG', slug: 'neet-pg', fullName: 'National Eligibility cum Entrance Test Postgraduate', type: 'Entrance', category: 'Medical', conductedBy: 'National Board of Examinations (NBE)', examLevel: 'National', description: 'National level entrance exam for MD/MS and PG Diploma admissions', eligibility: JSON.stringify(['MBBS degree from MCI recognized college', 'Completed/Final year MBBS students', 'Valid MCI registration']), examPattern: JSON.stringify({ mode: 'Computer Based Test', duration: '3.5 hours', questions: '200 MCQs', totalMarks: 800, marking: '+4 for correct, -1 for incorrect' }), syllabus: JSON.stringify(['All MBBS subjects', 'Pre-clinical, Para-clinical, Clinical subjects', 'Emphasis on Clinical subjects']), applicationFee: '₹4200', importantDates: JSON.stringify({ registration: 'February', exam: 'May', result: 'June', counselling: 'July-September' }), officialWebsite: 'https://nbe.edu.in/neet-pg', preparationTips: JSON.stringify(['Focus on clinical subjects', 'Practice MCQs daily', 'Revision is key', 'Previous year papers']), relatedCourses: JSON.stringify(['MD/MS in various specializations']), relatedCareers: JSON.stringify(['Specialist Doctor', 'Surgeon', 'Medical Professor']) },
    
    { name: 'NEET MDS', slug: 'neet-mds', fullName: 'National Eligibility cum Entrance Test Master of Dental Surgery', type: 'Entrance', category: 'Medical', conductedBy: 'National Board of Examinations (NBE)', examLevel: 'National', description: 'National level entrance exam for MDS (postgraduate dental) admissions', eligibility: JSON.stringify(['BDS degree from DCI recognized college', 'Completed/Final year BDS students', 'Valid DCI registration', 'One year internship completed']), examPattern: JSON.stringify({ mode: 'Computer Based Test', duration: '3 hours', questions: '240 MCQs', totalMarks: 960, marking: '+4 for correct, -1 for incorrect' }), syllabus: JSON.stringify(['All BDS subjects', 'Dental Anatomy', 'Oral Pathology', 'Conservative Dentistry', 'Orthodontics', 'Prosthodontics', 'Oral Surgery', 'Periodontology', 'Pedodontics']), applicationFee: '₹3700', importantDates: JSON.stringify({ registration: 'January-February', exam: 'March', result: 'April', counselling: 'May-June' }), officialWebsite: 'https://nbe.edu.in/neet-mds', preparationTips: JSON.stringify(['Focus on clinical subjects', 'MCQ practice books', 'Previous year analysis', 'Image-based questions important']), relatedCourses: JSON.stringify(['MDS in various dental specializations']), relatedCareers: JSON.stringify(['Specialist Dentist', 'Oral Surgeon', 'Orthodontist']) },
    
    { name: 'INI-CET', slug: 'ini-cet', fullName: 'Institute of National Importance Combined Entrance Test', type: 'Entrance', category: 'Medical', conductedBy: 'AIIMS New Delhi', examLevel: 'National', description: 'Entrance exam for PG medical courses at AIIMS, JIPMER, PGIMER and other INIs', eligibility: JSON.stringify(['MBBS degree holders', 'Valid MCI/NMC registration']), examPattern: JSON.stringify({ mode: 'Computer Based Test', duration: '3 hours', questions: '200 MCQs', marking: '+4 for correct, -1 for incorrect' }), syllabus: JSON.stringify(['All MBBS subjects', 'Similar to NEET PG syllabus']), applicationFee: '₹4000', importantDates: JSON.stringify({ registration: 'October & April', exam: 'November & May (Two sessions)', result: 'Within 2 weeks' }), officialWebsite: 'https://aiimsexams.ac.in', preparationTips: JSON.stringify(['Similar to NEET PG preparation', 'Focus on recent advances', 'Clinical scenarios important']), relatedCourses: JSON.stringify(['MD/MS/DM/MCh at INIs']), relatedCareers: JSON.stringify(['Super Specialist Doctor', 'Medical Researcher']) },
    
    { name: 'FMGE', slug: 'fmge', fullName: 'Foreign Medical Graduate Examination', type: 'Competitive', category: 'Medical', conductedBy: 'National Board of Examinations (NBE)', examLevel: 'National', description: 'Screening test for Indian students who completed MBBS from abroad to practice in India', eligibility: JSON.stringify(['MBBS from foreign university', 'Degree recognized by NMC', 'Indian citizens or OCI card holders']), examPattern: JSON.stringify({ mode: 'Computer Based Test', duration: '3.5 hours', questions: '300 MCQs', totalMarks: 300, passing: '150 marks (50%)', marking: '+1 for correct, 0 for incorrect' }), syllabus: JSON.stringify(['All MBBS subjects', 'Pre-clinical, Para-clinical, Clinical subjects']), applicationFee: '₹3500', importantDates: JSON.stringify({ registration: 'March & September', exam: 'June & December (Two sessions)', result: 'Within a month' }), officialWebsite: 'https://nbe.edu.in/fmge', preparationTips: JSON.stringify(['Thorough MBBS revision needed', 'High difficulty level', 'Multiple attempts common', 'Indian medical system knowledge']), relatedCourses: JSON.stringify(['MBBS from abroad']), relatedCareers: JSON.stringify(['Practice in India', 'NEET PG eligible after clearing']) },

    // GOVERNMENT JOBS
    { name: 'UPSC CSE', slug: 'upsc-cse', fullName: 'Civil Services Examination', type: 'Competitive', category: 'Government Jobs', conductedBy: 'Union Public Service Commission', examLevel: 'National', description: 'Premier exam for recruitment to All India Services and Central Civil Services', eligibility: JSON.stringify(['Graduation in any discipline', 'Age: 21-32 years (relaxation for reserved categories)', 'Number of attempts: 6 (General), 9 (OBC), Unlimited (SC/ST)']), examPattern: JSON.stringify({ stages: '3 stages - Prelims, Mains, Interview', prelims: 'GS Paper I (200 marks) + CSAT Paper II (200 marks - qualifying)', mains: '9 papers (1750 marks)', interview: 'Personality Test (275 marks)', totalMarks: '2025 (Mains + Interview)' }), syllabus: JSON.stringify(['Prelims: Current Affairs, History, Geography, Polity, Economy, Environment', 'Mains: Essay, GS I-IV, Optional Subject (2 papers), Language papers']), applicationFee: '₹100 (Male), No fee (Female/SC/ST/PwD)', importantDates: JSON.stringify({ notification: 'February', prelims: 'May-June', mains: 'September', interview: 'February-May (next year)', finalResult: 'April-May' }), officialWebsite: 'https://upsc.gov.in', preparationTips: JSON.stringify(['Start 1-2 years before', 'NCERT foundation crucial', 'Daily newspaper reading mandatory', 'Current affairs throughout year', 'Optional subject choice critical', 'Multiple mock tests', 'Answer writing practice for Mains', 'Previous toppers strategies']), relatedCourses: JSON.stringify(['Any graduation degree']), relatedCareers: JSON.stringify(['IAS', 'IPS', 'IFS', 'IRS', 'Central Civil Services']) },
    
    { name: 'SSC CGL', slug: 'ssc-cgl', fullName: 'Staff Selection Commission Combined Graduate Level', type: 'Recruitment', category: 'Government Jobs', conductedBy: 'Staff Selection Commission', examLevel: 'National', description: 'Recruitment exam for Group B and C posts in Central Government departments', eligibility: JSON.stringify(['Graduation in any discipline', 'Age: 18-32 years (varies by post)', 'Age relaxation as per rules']), examPattern: JSON.stringify({ tier1: 'Computer Based (100 marks) - Reasoning, QA, English, GK', tier2: 'Computer Based (3 papers)', tier3: 'Descriptive Paper (100 marks)', tier4: 'Computer Proficiency Test/DEST' }), syllabus: JSON.stringify(['Reasoning: Verbal & Non-verbal', 'Quantitative Aptitude', 'English: Grammar, Vocabulary, Comprehension', 'General Awareness: Current Affairs, Static GK']), applicationFee: '₹100 (Male), No fee (Female/SC/ST/ESM)', importantDates: JSON.stringify({ notification: 'September', tier1: 'December', tier2: 'February-March', tier3: 'May', finalResult: 'July-August' }), officialWebsite: 'https://ssc.nic.in', preparationTips: JSON.stringify(['Speed and accuracy crucial', 'Practice quantitative aptitude', 'Previous year papers', 'Daily GK updates', 'Time management', 'Descriptive paper practice']), relatedCourses: JSON.stringify(['Any graduation']), relatedCareers: JSON.stringify(['Inspector', 'Auditor', 'Tax Assistant', 'Accountant', 'Junior Statistical Officer']) },
    
    { name: 'SSC CHSL', slug: 'ssc-chsl', fullName: 'Staff Selection Commission Combined Higher Secondary Level', type: 'Recruitment', category: 'Government Jobs', conductedBy: 'Staff Selection Commission', examLevel: 'National', description: 'Recruitment for 10+2 level posts in Central Government departments', eligibility: JSON.stringify(['12th pass', 'Age: 18-27 years (varies by post)']), examPattern: JSON.stringify({ tier1: 'Computer Based (100 marks) - Reasoning, QA, English, GK', tier2: 'Descriptive Paper (100 marks)', tier3: 'Skill Test/Typing Test' }), syllabus: JSON.stringify(['Similar to CGL but 12th level', 'Reasoning, Quantitative Aptitude, English, General Awareness']), applicationFee: '₹100 (Male), No fee (Female/SC/ST/ESM)', importantDates: JSON.stringify({ notification: 'May', tier1: 'August', tier2: 'November', tier3: 'January', result: 'March-April' }), officialWebsite: 'https://ssc.nic.in', preparationTips: JSON.stringify(['12th level preparation', 'Typing speed important', 'Previous year papers', 'Regular practice']), relatedCourses: JSON.stringify(['12th pass']), relatedCareers: JSON.stringify(['LDC', 'DEO', 'Postal Assistant', 'Court Clerk']) },
    
    { name: 'IBPS PO', slug: 'ibps-po', fullName: 'Institute of Banking Personnel Selection Probationary Officer', type: 'Recruitment', category: 'Government Jobs', conductedBy: 'Institute of Banking Personnel Selection', examLevel: 'National', description: 'Common recruitment process for Probationary Officers in Public Sector Banks', eligibility: JSON.stringify(['Graduation (60% for General, 55% for SC/ST)', 'Age: 20-30 years', 'Computer literacy required']), examPattern: JSON.stringify({ prelims: 'English, Reasoning, Quantitative Aptitude (100 marks, 60 minutes)', mains: '5 sections (200 marks, 3 hours)', interview: '100 marks' }), syllabus: JSON.stringify(['Reasoning: Puzzles, Seating, Syllogism', 'Quantitative Aptitude: Data Interpretation, Number Series', 'English: Reading Comprehension, Grammar', 'General Awareness: Banking & Current Affairs', 'Computer Knowledge']), applicationFee: '₹850 (General/OBC), ₹175 (SC/ST/PwD)', importantDates: JSON.stringify({ notification: 'August-September', prelims: 'October', mains: 'November-December', interview: 'February-March', result: 'April' }), officialWebsite: 'https://www.ibps.in', preparationTips: JSON.stringify(['Banking awareness crucial', 'Speed in prelims', 'Data interpretation focus', 'Current affairs daily', 'Mock tests regularly']), relatedCourses: JSON.stringify(['Any graduation']), relatedCareers: JSON.stringify(['Bank PO', 'Branch Manager', 'Bank Officer']) },
    
    { name: 'SBI PO', slug: 'sbi-po', fullName: 'State Bank of India Probationary Officer', type: 'Recruitment', category: 'Government Jobs', conductedBy: 'State Bank of India', examLevel: 'National', description: 'Recruitment for Probationary Officers in State Bank of India', eligibility: JSON.stringify(['Graduation (60% for General, 55% for SC/ST)', 'Age: 21-30 years', 'Computer literacy required']), examPattern: JSON.stringify({ prelims: 'English, Reasoning, Quantitative Aptitude (100 marks, 60 minutes)', mains: '4 sections (200 marks, 3 hours)', interview: '50 marks' }), syllabus: JSON.stringify(['Similar to IBPS PO', 'Reasoning, QA, English, GK, Computer']), applicationFee: '₹750 (General/OBC/EWS), ₹125 (SC/ST/PwD)', importantDates: JSON.stringify({ notification: 'March-April', prelims: 'June', mains: 'July-August', interview: 'September-October', result: 'November' }), officialWebsite: 'https://sbi.co.in/careers', preparationTips: JSON.stringify(['Similar to IBPS preparation', 'SBI specific awareness', 'Group exercises in interview']), relatedCourses: JSON.stringify(['Any graduation']), relatedCareers: JSON.stringify(['SBI PO', 'Bank Manager']) },
    
    { name: 'RRB NTPC', slug: 'rrb-ntpc', fullName: 'Railway Recruitment Board Non-Technical Popular Categories', type: 'Recruitment', category: 'Government Jobs', conductedBy: 'Railway Recruitment Boards', examLevel: 'National', description: 'Recruitment for non-technical posts in Indian Railways', eligibility: JSON.stringify(['Graduation for some posts, 12th for others', 'Age: 18-33 years (varies by post)']), examPattern: JSON.stringify({ cbt1: 'Computer Based Test (100 marks, 90 minutes)', cbt2: 'Computer Based Test (varies by post)', typing: 'Skill Test/Document Verification' }), syllabus: JSON.stringify(['General Awareness', 'Mathematics', 'Reasoning', 'General Intelligence']), applicationFee: '₹500 (General/OBC), ₹250 (SC/ST)', importantDates: JSON.stringify({ notification: 'Irregular (once in 2-3 years)', cbt1: '3-4 months after notification', cbt2: '2 months after CBT1', result: '8-12 months from notification' }), officialWebsite: 'https://rrbonlinereg.in', preparationTips: JSON.stringify(['Railway specific GK', 'Speed in calculations', 'Previous year papers', 'Current affairs focus']), relatedCourses: JSON.stringify(['12th/Graduation depending on post']), relatedCareers: JSON.stringify(['Station Master', 'Commercial Clerk', 'Accounts Clerk', 'Traffic Assistant']) },
    
    { name: 'SSC JE', slug: 'ssc-je', fullName: 'Staff Selection Commission Junior Engineer', type: 'Recruitment', category: 'Government Jobs', conductedBy: 'Staff Selection Commission', examLevel: 'National', description: 'Recruitment for Junior Engineer posts in various government departments', eligibility: JSON.stringify(['Diploma/B.Tech in relevant engineering branch', 'Age: 18-32 years']), examPattern: JSON.stringify({ paper1: 'Computer Based (200 marks) - General Intelligence, GK, General Engineering', paper2: 'Conventional (300 marks) - Engineering subject specific' }), syllabus: JSON.stringify(['General Engineering: Civil, Electrical, Mechanical basics', 'Reasoning & GK', 'Subject specific detailed engineering']), applicationFee: '₹100 (Male), No fee (Female/SC/ST/ESM)', importantDates: JSON.stringify({ notification: 'August-September', paper1: 'October-November', paper2: 'February-March', result: 'April-May' }), officialWebsite: 'https://ssc.nic.in', preparationTips: JSON.stringify(['Focus on core engineering subjects', 'Previous year papers crucial', 'Time management in Paper 1', 'Detailed preparation for Paper 2']), relatedCourses: JSON.stringify(['Diploma/B.Tech in Civil/Electrical/Mechanical']), relatedCareers: JSON.stringify(['Junior Engineer in CPWD, MES, CWC, etc.']) },
    
    { name: 'NDA', slug: 'nda', fullName: 'National Defence Academy', type: 'Entrance', category: 'Government Jobs', conductedBy: 'Union Public Service Commission', examLevel: 'National', description: 'Entrance exam for joining Army, Navy and Air Force through National Defence Academy', eligibility: JSON.stringify(['12th pass (PCM for Air Force and Navy)', 'Unmarried male candidates', 'Age: 16.5-19.5 years', 'Physical and medical standards apply']), examPattern: JSON.stringify({ written: 'Maths (300 marks, 2.5 hours) + GAT (600 marks, 2.5 hours)', ssb: 'Services Selection Board (900 marks)', totalMarks: '900 (Written) + 900 (SSB) = 1800' }), syllabus: JSON.stringify(['Mathematics: 12th level', 'GAT: English, GK, Physics, Chemistry, Geography, History, Current Affairs']), applicationFee: '₹100 (No fee for female candidates - recently allowed)', importantDates: JSON.stringify({ notification: 'June & December (twice a year)', exam: 'September & April', ssb: 'Throughout the year for qualified candidates', finalResult: 'December & July' }), officialWebsite: 'https://upsc.gov.in', preparationTips: JSON.stringify(['Mathematics practice crucial', 'Physical fitness equally important', 'General knowledge from newspapers', 'SSB preparation separately', 'Previous year papers', 'Mock tests']), relatedCourses: JSON.stringify(['12th with PCM']), relatedCareers: JSON.stringify(['Army Officer', 'Navy Officer', 'Air Force Officer']) },
    
    { name: 'CDS', slug: 'cds', fullName: 'Combined Defence Services', type: 'Entrance', category: 'Government Jobs', conductedBy: 'Union Public Service Commission', examLevel: 'National', description: 'Exam for graduates to join Indian Military Academy, Naval Academy, Air Force Academy, and Officers Training Academy', eligibility: JSON.stringify(['Graduation for IMA, OTA', 'B.Tech for INA', 'Age varies: IMA 19-24, INA 19-25, IAFA 19-24, OTA 19-25']), examPattern: JSON.stringify({ written: 'English (100), GK (100), Maths (100 - optional for OTA)', ssb: 'Services Selection Board interview' }), syllabus: JSON.stringify(['English: Grammar, vocabulary, comprehension', 'GK: Current events, History, Geography, Polity, Science', 'Mathematics: Graduation level (for IMA, INA, IAFA)']), applicationFee: '₹200 (No fee for female candidates)', importantDates: JSON.stringify({ notification: 'June & October (twice a year)', exam: 'September & February', ssb: 'Throughout year', result: 'November & May' }), officialWebsite: 'https://upsc.gov.in', preparationTips: JSON.stringify(['Graduation level preparation', 'Physical fitness mandatory', 'SSB is crucial phase', 'Current affairs important']), relatedCourses: JSON.stringify(['Any graduation (B.Tech for Naval)']), relatedCareers: JSON.stringify(['Defence Officer in Army/Navy/Air Force']) },
    
    { name: 'RBI Grade B', slug: 'rbi-grade-b', fullName: 'Reserve Bank of India Grade B Officer', type: 'Recruitment', category: 'Government Jobs', conductedBy: 'Reserve Bank of India', examLevel: 'National', description: 'Direct recruitment for Grade B Officers in Reserve Bank of India', eligibility: JSON.stringify(['Graduation (60% for General, 55% for SC/ST)', 'Age: 21-30 years', 'Specific subject requirements for some posts']), examPattern: JSON.stringify({ phase1: 'General Awareness, Reasoning, QA, English (200 marks)', phase2: 'Economic & Social Issues, English, Finance & Management (300 marks)', interview: '50 marks' }), syllabus: JSON.stringify(['Economic & Social Issues', 'English Writing Skills', 'Finance and Management', 'General Awareness', 'Reasoning, QA']), applicationFee: '₹850 (General/OBC), ₹100 (SC/ST/PwD)', importantDates: JSON.stringify({ notification: 'June', phase1: 'July-August', phase2: 'September', interview: 'October-November', result: 'December' }), officialWebsite: 'https://opportunities.rbi.org.in', preparationTips: JSON.stringify(['Economic concepts crucial', 'Essay and precis writing', 'Current banking affairs', 'Interview preparation important', 'Previous year papers']), relatedCourses: JSON.stringify(['Any graduation, Economics/Finance background helpful']), relatedCareers: JSON.stringify(['RBI Grade B Officer', 'Banking Regulator']) },

    // MANAGEMENT
    { name: 'CAT', slug: 'cat', fullName: 'Common Admission Test', type: 'Entrance', category: 'Management', conductedBy: 'IIMs (Rotational)', examLevel: 'National', description: 'Premier management entrance exam for admission to IIMs and other top B-schools', eligibility: JSON.stringify(['Graduation (50% for General, 45% for SC/ST)', 'Final year students eligible', 'No age limit']), examPattern: JSON.stringify({ mode: 'Computer Based Test', duration: '2 hours (40 minutes per section)', sections: 'VARC (26Q), DILR (20Q), QA (22Q)', totalQuestions: 68, totalMarks: 204, marking: '+3 for correct, -1 for incorrect' }), syllabus: JSON.stringify(['VARC: Reading Comprehension, Verbal Ability', 'DILR: Data Interpretation, Logical Reasoning', 'QA: Number Systems, Algebra, Geometry, Modern Maths']), applicationFee: '₹2400 (General/NC-OBC), ₹1200 (SC/ST/PwD)', importantDates: JSON.stringify({ registration: 'August', exam: 'Last Sunday of November', result: 'January', interviews: 'February-April', finalAdmissions: 'May-June' }), officialWebsite: 'https://iimcat.ac.in', preparationTips: JSON.stringify(['Start 6-12 months before', 'Sectional time limits crucial', 'Reading comprehension practice daily', 'Shortcut techniques for QA', 'Mock tests from Sept onwards', 'Previous 10 years papers', 'Non-MCQs in DILR/QA difficult', 'Percentile vs Marks understanding']), relatedCourses: JSON.stringify(['Any graduation']), relatedCareers: JSON.stringify(['MBA from IIMs/top B-schools', 'Management Consultant', 'Product Manager', 'Investment Banker']) },
    
    { name: 'XAT', slug: 'xat', fullName: 'Xavier Aptitude Test', type: 'Entrance', category: 'Management', conductedBy: 'XLRI Jamshedpur', examLevel: 'National', description: 'Management entrance exam for XLRI and other Xavier Associate institutions', eligibility: JSON.stringify(['Graduation (no minimum percentage)', 'Final year students eligible', 'No age limit']), examPattern: JSON.stringify({ mode: 'Computer Based Test', duration: '3 hours 10 minutes', sections: 'Verbal & Logical (26Q), Decision Making (21Q), QA & DI (28Q), GK (25Q - 15 minutes separate)', totalQuestions: 100, marking: '+1 for correct, -0.25 for incorrect, -0.1 for unattempted' }), syllabus: JSON.stringify(['Similar to CAT but with Decision Making', 'Verbal Ability & Logical Reasoning', 'Decision Making (Unique to XAT)', 'Quantitative Ability & Data Interpretation', 'General Knowledge']), applicationFee: '₹2000 (Plus additional for each program)', importantDates: JSON.stringify({ registration: 'August-November', exam: 'First Sunday of January', result: 'January end', interviews: 'February-March' }), officialWebsite: 'https://xatonline.in', preparationTips: JSON.stringify(['Decision Making is unique', 'GK section separately timed', 'Essay writing important', 'Penalty for unattempted questions', 'Lengthy paper', 'Previous year papers']), relatedCourses: JSON.stringify(['Any graduation']), relatedCareers: JSON.stringify(['MBA from XLRI and Xavier institutes']) },
    
    { name: 'CMAT', slug: 'cmat', fullName: 'Common Management Admission Test', type: 'Entrance', category: 'Management', conductedBy: 'National Testing Agency', examLevel: 'National', description: 'National level management entrance exam for AICTE approved MBA/PGDM programs', eligibility: JSON.stringify(['Graduation (50% for General, 45% for SC/ST)', 'Final year students eligible']), examPattern: JSON.stringify({ mode: 'Computer Based Test', duration: '3 hours', sections: 'QA & DI (25Q), Logical Reasoning (25Q), Language Comprehension (25Q), GK (25Q), Innovation & Entrepreneurship (Optional - 15Q)', totalQuestions: 100, marking: '+4 for correct, -1 for incorrect' }), syllabus: JSON.stringify(['Quantitative Aptitude & Data Interpretation', 'Logical Reasoning', 'Language Comprehension', 'General Awareness']), applicationFee: '₹2200 (General), ₹1100 (SC/ST/PwD)', importantDates: JSON.stringify({ registration: 'January-February', exam: 'March-April', result: 'April-May' }), officialWebsite: 'https://cmat.nta.nic.in', preparationTips: JSON.stringify(['Easier than CAT/XAT', 'Good for backup', 'Innovation section optional', 'Speed important', 'Previous year papers']), relatedCourses: JSON.stringify(['Any graduation']), relatedCareers: JSON.stringify(['MBA/PGDM from AICTE colleges']) },
    
    { name: 'MAT', slug: 'mat', fullName: 'Management Aptitude Test', type: 'Entrance', category: 'Management', conductedBy: 'AIMA (All India Management Association)', examLevel: 'National', description: 'Management entrance exam conducted 4 times a year for various MBA programs', eligibility: JSON.stringify(['Graduation (50% for General)', 'Final year students eligible']), examPattern: JSON.stringify({ modes: 'PBT (Paper Based), CBT (Computer Based), IBT (Internet Based)', duration: '2.5 hours', sections: 'Language Comprehension (40Q), Mathematical Skills (40Q), Data Analysis (40Q), Intelligence & Critical Reasoning (40Q), Indian & Global Environment (40Q)', totalQuestions: 200, marking: '+1 for correct, -0.25 for incorrect' }), syllabus: JSON.stringify(['Language Comprehension', 'Mathematical Skills', 'Data Analysis & Sufficiency', 'Intelligence & Critical Reasoning', 'Indian & Global Environment']), applicationFee: '₹1650 (PBT), ₹1550 (CBT), ₹1350 (IBT)', importantDates: JSON.stringify({ exams: 'February, May, September, December (4 times a year)' }), officialWebsite: 'https://www.aima.in/mat', preparationTips: JSON.stringify(['4 attempts per year', 'Comparatively easier', 'Good for Tier-2/3 colleges', 'Multiple modes available']), relatedCourses: JSON.stringify(['Any graduation']), relatedCareers: JSON.stringify(['MBA from various colleges']) },
    
    { name: 'SNAP', slug: 'snap', fullName: 'Symbiosis National Aptitude Test', type: 'Entrance', category: 'Management', conductedBy: 'Symbiosis International University', examLevel: 'University', description: 'Entrance exam for MBA programs at Symbiosis institutes', eligibility: JSON.stringify(['Graduation (50% for General)', 'Final year students eligible']), examPattern: JSON.stringify({ mode: 'Computer Based Test', duration: '1 hour', sections: 'General English (15Q), QA & DI (20Q), Analytical & Logical Reasoning (25Q)', totalQuestions: 60, marking: '+1 for correct, -0.25 for incorrect' }), syllabus: JSON.stringify(['General English', 'Quantitative Aptitude', 'Data Interpretation', 'Analytical & Logical Reasoning']), applicationFee: '₹2200 (Plus application fee for each institute)', importantDates: JSON.stringify({ registration: 'August-November', exam: 'December (multiple slots)', result: 'January' }), officialWebsite: 'https://www.snaptest.org', preparationTips: JSON.stringify(['Short duration paper', 'Speed crucial', 'Best of attempts considered', 'Multiple test dates']), relatedCourses: JSON.stringify(['Any graduation']), relatedCareers: JSON.stringify(['MBA from Symbiosis institutes']) },
    
    { name: 'NMAT', slug: 'nmat', fullName: 'NMIMS Management Aptitude Test', type: 'Entrance', category: 'Management', conductedBy: 'GMAC (Graduate Management Admission Council)', examLevel: 'University', description: 'Management aptitude test for NMIMS and other participating B-schools', eligibility: JSON.stringify(['Graduation (50% for General)', 'Final year students eligible']), examPattern: JSON.stringify({ mode: 'Computer Based Test', duration: '2 hours', sections: 'Language Skills (32 min, 24Q), Quantitative Skills (48 min, 24Q), Logical Reasoning (40 min, 36Q)', totalQuestions: 108, totalMarks: 360, marking: 'No negative marking' }), syllabus: JSON.stringify(['Language Skills: Verbal Ability, Reading Comprehension', 'Quantitative Skills: Arithmetic, Algebra, Geometry', 'Logical Reasoning: Puzzles, Pattern Recognition']), applicationFee: '₹2300 + ₹200 per retake', importantDates: JSON.stringify({ registration: 'July-October', exam: 'October-January (retakes allowed)', result: 'February', interviews: 'February-April' }), officialWebsite: 'https://www.nmat.org', preparationTips: JSON.stringify(['No negative marking advantage', 'Retakes allowed', 'Section-wise time limits', 'Easier than CAT']), relatedCourses: JSON.stringify(['Any graduation']), relatedCareers: JSON.stringify(['MBA from NMIMS and partner colleges']) },
    
    { name: 'ATMA', slug: 'atma', fullName: 'AIMS Test for Management Admissions', type: 'Entrance', category: 'Management', conductedBy: 'AIMS (Association of Indian Management Schools)', examLevel: 'National', description: 'National level management entrance exam conducted multiple times a year', eligibility: JSON.stringify(['Graduation in any discipline', 'Final year students eligible']), examPattern: JSON.stringify({ mode: 'Computer Based Test', duration: '3 hours', sections: 'Analytical Reasoning (30Q), Verbal Skills (30Q), Quantitative Skills (30Q)', totalQuestions: 90, marking: '+1 for correct, -0.25 for incorrect' }), syllabus: JSON.stringify(['Analytical Reasoning Skills', 'Verbal Skills', 'Quantitative Skills']), applicationFee: '₹1250', importantDates: JSON.stringify({ exams: '3-4 times a year (February, May, July)' }), officialWebsite: 'https://www.atmaaims.com', preparationTips: JSON.stringify(['Multiple attempts available', 'Tier-2/3 colleges', 'Comparatively easier']), relatedCourses: JSON.stringify(['Any graduation']), relatedCareers: JSON.stringify(['MBA from participating colleges']) },

    // LAW
    { name: 'CLAT', slug: 'clat', fullName: 'Common Law Admission Test', type: 'Entrance', category: 'Law', conductedBy: 'Consortium of NLUs (Rotational)', examLevel: 'National', description: 'National level law entrance exam for admission to 22 NLUs in India', eligibility: JSON.stringify(['UG: 12th with 45% (40% for SC/ST)', 'PG: LLB degree with 50% (45% for SC/ST)', 'Age limit: No upper age limit']), examPattern: JSON.stringify({ mode: 'Offline OMR based', duration: '2 hours', sections: 'English (28-32Q), Current Affairs & GK (35-39Q), Legal Reasoning (35-39Q), Logical Reasoning (28-32Q), Quantitative Techniques (13-17Q)', totalQuestions: 150, totalMarks: 150, marking: '+1 for correct, -0.25 for incorrect' }), syllabus: JSON.stringify(['English: Comprehension passages', 'Current Affairs: Last one year', 'General Knowledge: Static GK', 'Legal Reasoning: Legal principles and situations', 'Logical Reasoning: Analytical ability', 'Quantitative Techniques: Basic maths']), applicationFee: '₹4000 (General), ₹3500 (SC/ST/BPL/PwD)', importantDates: JSON.stringify({ registration: 'January-April', exam: 'First Sunday of December', result: 'December end', counselling: 'January' }), officialWebsite: 'https://consortiumofnlus.ac.in', preparationTips: JSON.stringify(['Current affairs last 12 months crucial', 'English comprehension practice', 'Legal reasoning can be learned', 'Hindu editorials helpful', 'Previous year papers', 'Mock tests from October', 'Time management critical']), relatedCourses: JSON.stringify(['BA LLB (5 year), LLB (3 year), LLM']), relatedCareers: JSON.stringify(['Lawyer', 'Judge', 'Legal Advisor', 'Corporate Lawyer']) },
    
    { name: 'AILET', slug: 'ailet', fullName: 'All India Law Entrance Test', type: 'Entrance', category: 'Law', conductedBy: 'National Law University Delhi', examLevel: 'University', description: 'Entrance exam specifically for admission to NLU Delhi', eligibility: JSON.stringify(['UG: 12th with 50% (45% for SC/ST)', 'PG: LLB degree', 'Age: 20 years for UG']), examPattern: JSON.stringify({ mode: 'Offline OMR based', duration: '90 minutes', sections: 'English (35Q), GK (35Q), Legal Aptitude (35Q), Reasoning (25Q), Maths (10Q)', totalQuestions: 140, totalMarks: 140, marking: '+1 for correct, -0.25 for incorrect' }), syllabus: JSON.stringify(['Similar to CLAT', 'English, GK, Legal Aptitude, Reasoning, Elementary Mathematics']), applicationFee: '₹3500 (General), ₹2800 (Reserved)', importantDates: JSON.stringify({ registration: 'March-May', exam: 'Mid December', result: 'Late December' }), officialWebsite: 'https://nludelhi.ac.in', preparationTips: JSON.stringify(['Similar to CLAT preparation', 'NLU Delhi specific', 'Slightly easier than CLAT']), relatedCourses: JSON.stringify(['BA LLB from NLU Delhi']), relatedCareers: JSON.stringify(['Law careers']) },
    
    { name: 'SLAT', slug: 'slat', fullName: 'Symbiosis Law Admission Test', type: 'Entrance', category: 'Law', conductedBy: 'Symbiosis International University', examLevel: 'University', description: 'Entrance exam for law programs at Symbiosis Law School', eligibility: JSON.stringify(['12th pass (45% for General)', 'For LLB: Graduation required']), examPattern: JSON.stringify({ mode: 'Computer Based Test', duration: '1 hour', sections: 'Logical Reasoning, Legal Reasoning, Analytical Reasoning, Reading Comprehension, GK', totalQuestions: 60, marking: '+1 for correct, -0.25 for incorrect' }), syllabus: JSON.stringify(['Logical & Legal Reasoning', 'Reading Comprehension', 'General Knowledge']), applicationFee: '₹2250', importantDates: JSON.stringify({ registration: 'November-April', exam: 'May-June', result: 'June' }), officialWebsite: 'https://www.set-test.org', preparationTips: JSON.stringify(['Similar to CLAT but shorter', 'Symbiosis specific']), relatedCourses: JSON.stringify(['BA LLB, BBA LLB from Symbiosis']), relatedCareers: JSON.stringify(['Law careers']) },
    
    { name: 'MH CET Law', slug: 'mh-cet-law', fullName: 'Maharashtra Common Entrance Test for Law', type: 'Entrance', category: 'Law', conductedBy: 'State CET Cell, Maharashtra', examLevel: 'State', description: 'State level law entrance for 3-year and 5-year LLB programs in Maharashtra', eligibility: JSON.stringify(['For 5-year: 12th pass (45% for General)', 'For 3-year: Graduation (45% for General)']), examPattern: JSON.stringify({ mode: 'Computer Based Test', duration: '2 hours', sections: 'Legal Aptitude, Logical Reasoning, General Knowledge, English', totalQuestions: 150, marking: '+1 for correct, 0 for incorrect' }), syllabus: JSON.stringify(['Legal Aptitude & Reasoning', 'Logical Reasoning', 'General Knowledge with Current Affairs', 'English']), applicationFee: '₹800 (General), ₹600 (Reserved)', importantDates: JSON.stringify({ registration: 'March-April', exam: 'June', result: 'July', counselling: 'August' }), officialWebsite: 'https://cetcell.mahacet.org', preparationTips: JSON.stringify(['Maharashtra specific', 'No negative marking', 'Current affairs important']), relatedCourses: JSON.stringify(['LLB 3-year, LLB 5-year in Maharashtra']), relatedCareers: JSON.stringify(['Law careers in Maharashtra']) },

    // DESIGN
    { name: 'NID DAT', slug: 'nid-dat', fullName: 'National Institute of Design - Design Aptitude Test', type: 'Entrance', category: 'Design', conductedBy: 'National Institute of Design', examLevel: 'National', description: 'Entrance exam for B.Des and M.Des programs at NID campuses', eligibility: JSON.stringify(['For B.Des: 12th pass', 'For M.Des: Graduation in any field']), examPattern: JSON.stringify({ prelims: 'Studio Test - Creativity, Visualization, Observation', mains: 'Portfolio & Interview' }), syllabus: JSON.stringify(['Creative thinking', 'Visualization', 'Observation', 'Design sensitivity', 'Communication skills']), applicationFee: '₹2000-2500', importantDates: JSON.stringify({ registration: 'October-December', prelims: 'January', mains: 'March-April' }), officialWebsite: 'https://www.nid.edu', preparationTips: JSON.stringify(['Portfolio preparation crucial', 'Creativity and observation', 'Sketching practice', 'Design awareness']), relatedCourses: JSON.stringify(['B.Des, M.Des at NID']), relatedCareers: JSON.stringify(['Product Designer', 'UI/UX Designer', 'Industrial Designer']) },
    
    { name: 'UCEED', slug: 'uceed', fullName: 'Undergraduate Common Entrance Examination for Design', type: 'Entrance', category: 'Design', conductedBy: 'IIT Bombay', examLevel: 'National', description: 'Entrance exam for B.Des programs at IIT Bombay, IIT Guwahati, IIITDM Jabalpur', eligibility: JSON.stringify(['12th pass or appearing', 'No age limit']), examPattern: JSON.stringify({ mode: 'Computer Based Test', duration: '3 hours', parts: 'Part A: Numerical, Verbal, Spatial (NAT & MCQ) | Part B: Drawing (Hand drawing uploaded)' }), syllabus: JSON.stringify(['Visualization and spatial ability', 'Observation and design sensitivity', 'Drawing', 'Environmental and social awareness', 'Analytical and logical reasoning', 'Language and creativity']), applicationFee: '₹2200 (General), ₹1100 (Female/SC/ST/PwD)', importantDates: JSON.stringify({ registration: 'October', exam: 'January', result: 'March' }), officialWebsite: 'https://uceed.iitb.ac.in', preparationTips: JSON.stringify(['Drawing skills important', 'Observation practice', 'Spatial visualization', 'Design sensitivity']), relatedCourses: JSON.stringify(['B.Des from IITs']), relatedCareers: JSON.stringify(['Designer', 'Design Researcher']) },
    
    { name: 'CEED', slug: 'ceed', fullName: 'Common Entrance Examination for Design', type: 'Entrance', category: 'Design', conductedBy: 'IIT Bombay', examLevel: 'National', description: 'Entrance exam for M.Des and PhD programs at IITs and IISc', eligibility: JSON.stringify(['Graduation in any discipline', 'Final year students eligible']), examPattern: JSON.stringify({ mode: 'Computer Based Test', duration: '3 hours', parts: 'Part A: Visualization, Communication, Design Thinking (MCQ) | Part B: Drawing and Design (Hand sketches uploaded)' }), syllabus: JSON.stringify(['Visualization and spatial ability', 'Environmental and social awareness', 'Design thinking and problem solving', 'Observation and design sensitivity', 'Communication skills']), applicationFee: '₹2200 (General), ₹1100 (Female/SC/ST/PwD)', importantDates: JSON.stringify({ registration: 'August-September', exam: 'January', result: 'March', interview: 'April-May' }), officialWebsite: 'https://ceed.iitb.ac.in', preparationTips: JSON.stringify(['Portfolio important', 'Conceptual thinking', 'Problem-solving approach', 'Interview preparation']), relatedCourses: JSON.stringify(['M.Des, PhD at IITs, IISc']), relatedCareers: JSON.stringify(['Senior Designer', 'Design Researcher', 'Design Educator']) },
    
    { name: 'NIFT', slug: 'nift', fullName: 'National Institute of Fashion Technology Entrance', type: 'Entrance', category: 'Design', conductedBy: 'National Institute of Fashion Technology', examLevel: 'National', description: 'Entrance exam for fashion and design programs at NIFT campuses', eligibility: JSON.stringify(['For UG: 12th pass', 'For PG: Graduation in relevant field']), examPattern: JSON.stringify({ for: 'B.Des/B.FTech: CAT (Creative Ability Test) + GAT (General Ability Test) + Situation Test', forPG: 'M.Des/M.FTech/M.FM: GAT + CAT (varies by program)' }), syllabus: JSON.stringify(['Creative Ability Test: Design, Drawing', 'General Ability Test: Verbal, Quantitative, GK', 'Situation Test: Material handling and innovation']), applicationFee: '₹2000-2500', importantDates: JSON.stringify({ registration: 'December-January', exam: 'February-March', result: 'April' }), officialWebsite: 'https://www.nift.ac.in', preparationTips: JSON.stringify(['Fashion awareness', 'Drawing and sketching', 'Material understanding', 'Current affairs in fashion']), relatedCourses: JSON.stringify(['B.Des Fashion Design, B.FTech, M.Des at NIFT']), relatedCareers: JSON.stringify(['Fashion Designer', 'Textile Designer', 'Merchandiser']) },
  ]

  console.log(`Creating ${exams.length} exams...`)
  for (const exam of exams) {
    await prisma.exam.create({ data: exam })
  }
  console.log(`✅ ${exams.length} exams created`)

  // Create sample test (only if not exists)
  const testCount = await prisma.test.count()
  if (testCount === 0) {
    await prisma.test.create({
      data: {
        title: 'Career Personality Assessment',
        type: 'Personality',
        description: 'Discover your personality type and find suitable career paths',
        duration: 15,
        questions: JSON.stringify([
          {
            id: 1,
            question: 'I enjoy analyzing data and solving complex problems',
            options: ['Strongly Disagree', 'Disagree', 'Neutral', 'Agree', 'Strongly Agree'],
            trait: 'Analytical'
          },
          {
            id: 2,
            question: 'I am comfortable taking on leadership roles and guiding others',
            options: ['Strongly Disagree', 'Disagree', 'Neutral', 'Agree', 'Strongly Agree'],
            trait: 'Leadership'
          },
          {
            id: 3,
            question: 'I prefer working with creative ideas and artistic concepts',
            options: ['Strongly Disagree', 'Disagree', 'Neutral', 'Agree', 'Strongly Agree'],
            trait: 'Creative'
          },
          {
            id: 4,
            question: 'I enjoy helping others and working in teams',
            options: ['Strongly Disagree', 'Disagree', 'Neutral', 'Agree', 'Strongly Agree'],
            trait: 'Social'
          },
          {
            id: 5,
            question: 'I prefer structured tasks with clear instructions',
            options: ['Strongly Disagree', 'Disagree', 'Neutral', 'Agree', 'Strongly Agree'],
            trait: 'Practical'
          },
          {
            id: 6,
            question: 'I thrive in dynamic environments with constant change',
            options: ['Strongly Disagree', 'Disagree', 'Neutral', 'Agree', 'Strongly Agree'],
            trait: 'Adventurous'
          },
          {
            id: 7,
            question: 'I excel at logical reasoning and critical thinking',
            options: ['Strongly Disagree', 'Disagree', 'Neutral', 'Agree', 'Strongly Agree'],
            trait: 'Analytical'
          },
          {
            id: 8,
            question: 'I am good at motivating and inspiring people',
            options: ['Strongly Disagree', 'Disagree', 'Neutral', 'Agree', 'Strongly Agree'],
            trait: 'Leadership'
          },
          {
            id: 9,
            question: 'I enjoy designing and creating new things',
            options: ['Strongly Disagree', 'Disagree', 'Neutral', 'Agree', 'Strongly Agree'],
            trait: 'Creative'
          },
          {
            id: 10,
            question: 'I am empathetic and understand others emotions well',
            options: ['Strongly Disagree', 'Disagree', 'Neutral', 'Agree', 'Strongly Agree'],
            trait: 'Social'
          },
          {
            id: 11,
            question: 'I prefer hands-on work and practical solutions',
            options: ['Strongly Disagree', 'Disagree', 'Neutral', 'Agree', 'Strongly Agree'],
            trait: 'Practical'
          },
          {
            id: 12,
            question: 'I am willing to take risks for potential rewards',
            options: ['Strongly Disagree', 'Disagree', 'Neutral', 'Agree', 'Strongly Agree'],
            trait: 'Adventurous'
          },
          {
            id: 13,
            question: 'I pay close attention to details and accuracy',
            options: ['Strongly Disagree', 'Disagree', 'Neutral', 'Agree', 'Strongly Agree'],
            trait: 'Analytical'
          },
          {
            id: 14,
            question: 'I am confident in making important decisions',
            options: ['Strongly Disagree', 'Disagree', 'Neutral', 'Agree', 'Strongly Agree'],
            trait: 'Leadership'
          },
          {
            id: 15,
            question: 'I think outside the box and come up with innovative ideas',
            options: ['Strongly Disagree', 'Disagree', 'Neutral', 'Agree', 'Strongly Agree'],
            trait: 'Creative'
          }
        ]),
        scoring: JSON.stringify({
          Analytical: 'Strong analytical and problem-solving skills',
          Leadership: 'Natural leadership and management abilities',
          Creative: 'Creative thinking and innovation',
          Social: 'Interpersonal and collaborative skills',
          Practical: 'Practical and hands-on approach',
          Adventurous: 'Dynamic and adaptable personality'
        }),
        isActive: true,
      }
    })
    console.log('✅ Test created')
  }

  console.log('🎉 Database seeding completed!')
  console.log(`📊 Final counts: ${colleges.length} colleges, ${exams.length} exams`)
}

main()
  .catch((e) => {
    console.error('❌ Error seeding database:', e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
